package language

// Code generated by gen/scripts.go DO NOT EDIT.

const (
	Old_Sogdian            = Script(0x536f676f)
	Tifinagh               = Script(0x54666e67)
	Tagalog                = Script(0x54676c67)
	Unknown                = Script(0x5a7a7a7a)
	Khojki                 = Script(0x4b686f6a)
	Latin                  = Script(0x4c61746e)
	Mende_Kikakui          = Script(0x4d656e64)
	Miao                   = Script(0x506c7264)
	Thaana                 = Script(0x54686161)
	Han                    = Script(0x48616e69)
	Lycian                 = Script(0x4c796369)
	Ogham                  = Script(0x4f67616d)
	Cypriot                = Script(0x43707274)
	Limbu                  = Script(0x4c696d62)
	Wancho                 = Script(0x5763686f)
	Lepcha                 = Script(0x4c657063)
	Nandinagari            = Script(0x4e616e64)
	Nabataean              = Script(0x4e626174)
	Phags_Pa               = Script(0x50686167)
	SignWriting            = Script(0x53676e77)
	Arabic                 = Script(0x41726162)
	Hebrew                 = Script(0x48656272)
	Anatolian_Hieroglyphs  = Script(0x486c7577)
	Sundanese              = Script(0x53756e64)
	Tibetan                = Script(0x54696274)
	Zanabazar_Square       = Script(0x5a616e62)
	Buginese               = Script(0x42756769)
	Gothic                 = Script(0x476f7468)
	Shavian                = Script(0x53686177)
	Dives_Akuru            = Script(0x4469616b)
	Hanunoo                = Script(0x48616e6f)
	Tai_Tham               = Script(0x4c616e61)
	Lao                    = Script(0x4c616f6f)
	Telugu                 = Script(0x54656c75)
	Batak                  = Script(0x4261746b)
	Bengali                = Script(0x42656e67)
	Carian                 = Script(0x43617269)
	Georgian               = Script(0x47656f72)
	Makasar                = Script(0x4d616b61)
	Old_Italic             = Script(0x4974616c)
	Linear_A               = Script(0x4c696e61)
	Meetei_Mayek           = Script(0x4d746569)
	Hanifi_Rohingya        = Script(0x526f6867)
	Common                 = Script(0x5a797979)
	Adlam                  = Script(0x41646c6d)
	Balinese               = Script(0x42616c69)
	Elymaic                = Script(0x456c796d)
	Cuneiform              = Script(0x58737578)
	Imperial_Aramaic       = Script(0x41726d69)
	Grantha                = Script(0x4772616e)
	Psalter_Pahlavi        = Script(0x50686c70)
	Takri                  = Script(0x54616b72)
	Armenian               = Script(0x41726d6e)
	Khitan_Small_Script    = Script(0x4b697473)
	Meroitic_Cursive       = Script(0x4d657263)
	Myanmar                = Script(0x4d796d72)
	Tamil                  = Script(0x54616d6c)
	Hatran                 = Script(0x48617472)
	Kharoshthi             = Script(0x4b686172)
	Multani                = Script(0x4d756c74)
	Bhaiksuki              = Script(0x42686b73)
	Kannada                = Script(0x4b6e6461)
	Osmanya                = Script(0x4f736d61)
	Pau_Cin_Hau            = Script(0x50617563)
	Sharada                = Script(0x53687264)
	Syloti_Nagri           = Script(0x53796c6f)
	Brahmi                 = Script(0x42726168)
	Chakma                 = Script(0x43616b6d)
	Javanese               = Script(0x4a617661)
	Lisu                   = Script(0x4c697375)
	Siddham                = Script(0x53696464)
	Tai_Le                 = Script(0x54616c65)
	Yezidi                 = Script(0x59657a69)
	Egyptian_Hieroglyphs   = Script(0x45677970)
	Gujarati               = Script(0x47756a72)
	Kayah_Li               = Script(0x4b616c69)
	Nyiakeng_Puachue_Hmong = Script(0x486d6e70)
	Warang_Citi            = Script(0x57617261)
	Chorasmian             = Script(0x43687273)
	Old_Hungarian          = Script(0x48756e67)
	Sogdian                = Script(0x536f6764)
	Osage                  = Script(0x4f736765)
	Old_Permic             = Script(0x5065726d)
	Inscriptional_Parthian = Script(0x50727469)
	Rejang                 = Script(0x526a6e67)
	Cham                   = Script(0x4368616d)
	Hangul                 = Script(0x48616e67)
	Mandaic                = Script(0x4d616e64)
	Ugaritic               = Script(0x55676172)
	Vai                    = Script(0x56616969)
	Old_Persian            = Script(0x5870656f)
	Ahom                   = Script(0x41686f6d)
	Newa                   = Script(0x4e657761)
	Tirhuta                = Script(0x54697268)
	Modi                   = Script(0x4d6f6469)
	Old_South_Arabian      = Script(0x53617262)
	Yi                     = Script(0x59696969)
	Lydian                 = Script(0x4c796469)
	Tangut                 = Script(0x54616e67)
	Ol_Chiki               = Script(0x4f6c636b)
	Palmyrene              = Script(0x50616c6d)
	Soyombo                = Script(0x536f796f)
	Nushu                  = Script(0x4e736875)
	Bassa_Vah              = Script(0x42617373)
	Pahawh_Hmong           = Script(0x486d6e67)
	Katakana               = Script(0x4b616e61)
	Avestan                = Script(0x41767374)
	Devanagari             = Script(0x44657661)
	Gurmukhi               = Script(0x47757275)
	Manichaean             = Script(0x4d616e69)
	Inherited              = Script(0x5a696e68)
	Canadian_Aboriginal    = Script(0x43616e73)
	Dogra                  = Script(0x446f6772)
	Ethiopic               = Script(0x45746869)
	Greek                  = Script(0x4772656b)
	Sora_Sompeng           = Script(0x536f7261)
	Tai_Viet               = Script(0x54617674)
	Thai                   = Script(0x54686169)
	Caucasian_Albanian     = Script(0x41676862)
	Coptic                 = Script(0x436f7074)
	Deseret                = Script(0x44737274)
	Kaithi                 = Script(0x4b746869)
	Inscriptional_Pahlavi  = Script(0x50686c69)
	Syriac                 = Script(0x53797263)
	New_Tai_Lue            = Script(0x54616c75)
	Buhid                  = Script(0x42756864)
	Cherokee               = Script(0x43686572)
	Cyrillic               = Script(0x4379726c)
	Marchen                = Script(0x4d617263)
	Sinhala                = Script(0x53696e68)
	Bamum                  = Script(0x42616d75)
	Braille                = Script(0x42726169)
	Masaram_Gondi          = Script(0x476f6e6d)
	Duployan               = Script(0x4475706c)
	Oriya                  = Script(0x4f727961)
	Khudawadi              = Script(0x53696e64)
	Tagbanwa               = Script(0x54616762)
	Glagolitic             = Script(0x476c6167)
	Mro                    = Script(0x4d726f6f)
	Phoenician             = Script(0x50686e78)
	Katakana_Or_Hiragana   = Script(0x48726b74)
	Linear_B               = Script(0x4c696e62)
	Mahajani               = Script(0x4d61686a)
	Medefaidrin            = Script(0x4d656466)
	Old_North_Arabian      = Script(0x4e617262)
	Elbasan                = Script(0x456c6261)
	Gunjala_Gondi          = Script(0x476f6e67)
	Hiragana               = Script(0x48697261)
	Old_Turkic             = Script(0x4f726b68)
	Samaritan              = Script(0x53616d72)
	Saurashtra             = Script(0x53617572)
	Meroitic_Hieroglyphs   = Script(0x4d65726f)
	Mongolian              = Script(0x4d6f6e67)
	Nko                    = Script(0x4e6b6f6f)
	Runic                  = Script(0x52756e72)
	Bopomofo               = Script(0x426f706f)
	Khmer                  = Script(0x4b686d72)
	Malayalam              = Script(0x4d6c796d)
)

var scriptToTag = map[string]Script{
	"Imperial_Aramaic":       Imperial_Aramaic,
	"Grantha":                Grantha,
	"Psalter_Pahlavi":        Psalter_Pahlavi,
	"Cuneiform":              Cuneiform,
	"Armenian":               Armenian,
	"Khitan_Small_Script":    Khitan_Small_Script,
	"Meroitic_Cursive":       Meroitic_Cursive,
	"Takri":                  Takri,
	"Hatran":                 Hatran,
	"Kharoshthi":             Kharoshthi,
	"Multani":                Multani,
	"Myanmar":                Myanmar,
	"Tamil":                  Tamil,
	"Bhaiksuki":              Bhaiksuki,
	"Syloti_Nagri":           Syloti_Nagri,
	"Brahmi":                 Brahmi,
	"Chakma":                 Chakma,
	"Javanese":               Javanese,
	"Kannada":                Kannada,
	"Osmanya":                Osmanya,
	"Pau_Cin_Hau":            Pau_Cin_Hau,
	"Sharada":                Sharada,
	"Egyptian_Hieroglyphs":   Egyptian_Hieroglyphs,
	"Gujarati":               Gujarati,
	"Kayah_Li":               Kayah_Li,
	"Lisu":                   Lisu,
	"Siddham":                Siddham,
	"Tai_Le":                 Tai_Le,
	"Yezidi":                 Yezidi,
	"Nyiakeng_Puachue_Hmong": Nyiakeng_Puachue_Hmong,
	"Chorasmian":             Chorasmian,
	"Old_Hungarian":          Old_Hungarian,
	"Sogdian":                Sogdian,
	"Warang_Citi":            Warang_Citi,
	"Cham":                   Cham,
	"Hangul":                 Hangul,
	"Mandaic":                Mandaic,
	"Osage":                  Osage,
	"Old_Permic":             Old_Permic,
	"Inscriptional_Parthian": Inscriptional_Parthian,
	"Rejang":                 Rejang,
	"Ahom":                   Ahom,
	"Newa":                   Newa,
	"Tirhuta":                Tirhuta,
	"Ugaritic":               Ugaritic,
	"Vai":                    Vai,
	"Old_Persian":            Old_Persian,
	"Modi":                   Modi,
	"Old_South_Arabian":      Old_South_Arabian,
	"Yi":                     Yi,
	"Lydian":                 Lydian,
	"Tangut":                 Tangut,
	"Ol_Chiki":               Ol_Chiki,
	"Palmyrene":              Palmyrene,
	"Soyombo":                Soyombo,
	"Bassa_Vah":              Bassa_Vah,
	"Pahawh_Hmong":           Pahawh_Hmong,
	"Katakana":               Katakana,
	"Nushu":                  Nushu,
	"Avestan":                Avestan,
	"Devanagari":             Devanagari,
	"Canadian_Aboriginal":    Canadian_Aboriginal,
	"Dogra":                  Dogra,
	"Ethiopic":               Ethiopic,
	"Gurmukhi":               Gurmukhi,
	"Manichaean":             Manichaean,
	"Inherited":              Inherited,
	"Caucasian_Albanian":     Caucasian_Albanian,
	"Coptic":                 Coptic,
	"Deseret":                Deseret,
	"Greek":                  Greek,
	"Sora_Sompeng":           Sora_Sompeng,
	"Tai_Viet":               Tai_Viet,
	"Thai":                   Thai,
	"Buhid":                  Buhid,
	"Cherokee":               Cherokee,
	"Cyrillic":               Cyrillic,
	"Kaithi":                 Kaithi,
	"Inscriptional_Pahlavi":  Inscriptional_Pahlavi,
	"Syriac":                 Syriac,
	"New_Tai_Lue":            New_Tai_Lue,
	"Bamum":                  Bamum,
	"Braille":                Braille,
	"Masaram_Gondi":          Masaram_Gondi,
	"Marchen":                Marchen,
	"Sinhala":                Sinhala,
	"Duployan":               Duployan,
	"Oriya":                  Oriya,
	"Glagolitic":             Glagolitic,
	"Mro":                    Mro,
	"Phoenician":             Phoenician,
	"Khudawadi":              Khudawadi,
	"Tagbanwa":               Tagbanwa,
	"Old_North_Arabian":      Old_North_Arabian,
	"Elbasan":                Elbasan,
	"Gunjala_Gondi":          Gunjala_Gondi,
	"Hiragana":               Hiragana,
	"Katakana_Or_Hiragana":   Katakana_Or_Hiragana,
	"Linear_B":               Linear_B,
	"Mahajani":               Mahajani,
	"Medefaidrin":            Medefaidrin,
	"Meroitic_Hieroglyphs":   Meroitic_Hieroglyphs,
	"Mongolian":              Mongolian,
	"Nko":                    Nko,
	"Old_Turkic":             Old_Turkic,
	"Samaritan":              Samaritan,
	"Saurashtra":             Saurashtra,
	"Bopomofo":               Bopomofo,
	"Khmer":                  Khmer,
	"Malayalam":              Malayalam,
	"Runic":                  Runic,
	"Khojki":                 Khojki,
	"Latin":                  Latin,
	"Mende_Kikakui":          Mende_Kikakui,
	"Old_Sogdian":            Old_Sogdian,
	"Tifinagh":               Tifinagh,
	"Tagalog":                Tagalog,
	"Unknown":                Unknown,
	"Han":                    Han,
	"Lycian":                 Lycian,
	"Ogham":                  Ogham,
	"Miao":                   Miao,
	"Thaana":                 Thaana,
	"Cypriot":                Cypriot,
	"Limbu":                  Limbu,
	"Wancho":                 Wancho,
	"SignWriting":            SignWriting,
	"Arabic":                 Arabic,
	"Hebrew":                 Hebrew,
	"Anatolian_Hieroglyphs":  Anatolian_Hieroglyphs,
	"Lepcha":                 Lepcha,
	"Nandinagari":            Nandinagari,
	"Nabataean":              Nabataean,
	"Phags_Pa":               Phags_Pa,
	"Buginese":               Buginese,
	"Gothic":                 Gothic,
	"Shavian":                Shavian,
	"Sundanese":              Sundanese,
	"Tibetan":                Tibetan,
	"Zanabazar_Square":       Zanabazar_Square,
	"Telugu":                 Telugu,
	"Batak":                  Batak,
	"Bengali":                Bengali,
	"Carian":                 Carian,
	"Dives_Akuru":            Dives_Akuru,
	"Hanunoo":                Hanunoo,
	"Tai_Tham":               Tai_Tham,
	"Lao":                    Lao,
	"Georgian":               Georgian,
	"Makasar":                Makasar,
	"Common":                 Common,
	"Adlam":                  Adlam,
	"Balinese":               Balinese,
	"Elymaic":                Elymaic,
	"Old_Italic":             Old_Italic,
	"Linear_A":               Linear_A,
	"Meetei_Mayek":           Meetei_Mayek,
	"Hanifi_Rohingya":        Hanifi_Rohingya,
}
