package language

// Code generated by gen/scripts.go DO NOT EDIT.

const (
	Adlam                  = Script(0x61646c6d)
	Caucasian_Albanian     = Script(0x61676862)
	Ahom                   = Script(0x61686f6d)
	Arabic                 = Script(0x61726162)
	Imperial_Aramaic       = Script(0x61726d69)
	Armenian               = Script(0x61726d6e)
	Avestan                = Script(0x61767374)
	Balinese               = Script(0x62616c69)
	Bamum                  = Script(0x62616d75)
	Bassa_Vah              = Script(0x62617373)
	Batak                  = Script(0x6261746b)
	Bengali                = Script(0x62656e67)
	Bhaiksuki              = Script(0x62686b73)
	Bopomofo               = Script(0x626f706f)
	Brahmi                 = Script(0x62726168)
	Braille                = Script(0x62726169)
	Buginese               = Script(0x62756769)
	Buhid                  = Script(0x62756864)
	Chakma                 = Script(0x63616b6d)
	Canadian_Aboriginal    = Script(0x63616e73)
	Carian                 = Script(0x63617269)
	Cham                   = Script(0x6368616d)
	Cherokee               = Script(0x63686572)
	Chorasmian             = Script(0x63687273)
	Coptic                 = Script(0x636f7074)
	Cypriot                = Script(0x63707274)
	Cyrillic               = Script(0x6379726c)
	Devanagari             = Script(0x64657661)
	Dives_Akuru            = Script(0x6469616b)
	Dogra                  = Script(0x646f6772)
	Deseret                = Script(0x64737274)
	Duployan               = Script(0x6475706c)
	Egyptian_Hieroglyphs   = Script(0x65677970)
	Elbasan                = Script(0x656c6261)
	Elymaic                = Script(0x656c796d)
	Ethiopic               = Script(0x65746869)
	Georgian               = Script(0x67656f72)
	Glagolitic             = Script(0x676c6167)
	Gunjala_Gondi          = Script(0x676f6e67)
	Masaram_Gondi          = Script(0x676f6e6d)
	Gothic                 = Script(0x676f7468)
	Grantha                = Script(0x6772616e)
	Greek                  = Script(0x6772656b)
	Gujarati               = Script(0x67756a72)
	Gurmukhi               = Script(0x67757275)
	Hangul                 = Script(0x68616e67)
	Han                    = Script(0x68616e69)
	Hanunoo                = Script(0x68616e6f)
	Hatran                 = Script(0x68617472)
	Hebrew                 = Script(0x68656272)
	Hiragana               = Script(0x68697261)
	Anatolian_Hieroglyphs  = Script(0x686c7577)
	Pahawh_Hmong           = Script(0x686d6e67)
	Nyiakeng_Puachue_Hmong = Script(0x686d6e70)
	Katakana_Or_Hiragana   = Script(0x68726b74)
	Old_Hungarian          = Script(0x68756e67)
	Old_Italic             = Script(0x6974616c)
	Javanese               = Script(0x6a617661)
	Kayah_Li               = Script(0x6b616c69)
	Katakana               = Script(0x6b616e61)
	Kharoshthi             = Script(0x6b686172)
	Khmer                  = Script(0x6b686d72)
	Khojki                 = Script(0x6b686f6a)
	Khitan_Small_Script    = Script(0x6b697473)
	Kannada                = Script(0x6b6e6461)
	Kaithi                 = Script(0x6b746869)
	Tai_Tham               = Script(0x6c616e61)
	Lao                    = Script(0x6c616f6f)
	Latin                  = Script(0x6c61746e)
	Lepcha                 = Script(0x6c657063)
	Limbu                  = Script(0x6c696d62)
	Linear_A               = Script(0x6c696e61)
	Linear_B               = Script(0x6c696e62)
	Lisu                   = Script(0x6c697375)
	Lycian                 = Script(0x6c796369)
	Lydian                 = Script(0x6c796469)
	Mahajani               = Script(0x6d61686a)
	Makasar                = Script(0x6d616b61)
	Mandaic                = Script(0x6d616e64)
	Manichaean             = Script(0x6d616e69)
	Marchen                = Script(0x6d617263)
	Medefaidrin            = Script(0x6d656466)
	Mende_Kikakui          = Script(0x6d656e64)
	Meroitic_Cursive       = Script(0x6d657263)
	Meroitic_Hieroglyphs   = Script(0x6d65726f)
	Malayalam              = Script(0x6d6c796d)
	Modi                   = Script(0x6d6f6469)
	Mongolian              = Script(0x6d6f6e67)
	Mro                    = Script(0x6d726f6f)
	Meetei_Mayek           = Script(0x6d746569)
	Multani                = Script(0x6d756c74)
	Myanmar                = Script(0x6d796d72)
	Nandinagari            = Script(0x6e616e64)
	Old_North_Arabian      = Script(0x6e617262)
	Nabataean              = Script(0x6e626174)
	Newa                   = Script(0x6e657761)
	Nko                    = Script(0x6e6b6f6f)
	Nushu                  = Script(0x6e736875)
	Ogham                  = Script(0x6f67616d)
	Ol_Chiki               = Script(0x6f6c636b)
	Old_Turkic             = Script(0x6f726b68)
	Oriya                  = Script(0x6f727961)
	Osage                  = Script(0x6f736765)
	Osmanya                = Script(0x6f736d61)
	Palmyrene              = Script(0x70616c6d)
	Pau_Cin_Hau            = Script(0x70617563)
	Old_Permic             = Script(0x7065726d)
	Phags_Pa               = Script(0x70686167)
	Inscriptional_Pahlavi  = Script(0x70686c69)
	Psalter_Pahlavi        = Script(0x70686c70)
	Phoenician             = Script(0x70686e78)
	Miao                   = Script(0x706c7264)
	Inscriptional_Parthian = Script(0x70727469)
	Rejang                 = Script(0x726a6e67)
	Hanifi_Rohingya        = Script(0x726f6867)
	Runic                  = Script(0x72756e72)
	Samaritan              = Script(0x73616d72)
	Old_South_Arabian      = Script(0x73617262)
	Saurashtra             = Script(0x73617572)
	SignWriting            = Script(0x73676e77)
	Shavian                = Script(0x73686177)
	Sharada                = Script(0x73687264)
	Siddham                = Script(0x73696464)
	Khudawadi              = Script(0x73696e64)
	Sinhala                = Script(0x73696e68)
	Sogdian                = Script(0x736f6764)
	Old_Sogdian            = Script(0x736f676f)
	Sora_Sompeng           = Script(0x736f7261)
	Soyombo                = Script(0x736f796f)
	Sundanese              = Script(0x73756e64)
	Syloti_Nagri           = Script(0x73796c6f)
	Syriac                 = Script(0x73797263)
	Tagbanwa               = Script(0x74616762)
	Takri                  = Script(0x74616b72)
	Tai_Le                 = Script(0x74616c65)
	New_Tai_Lue            = Script(0x74616c75)
	Tamil                  = Script(0x74616d6c)
	Tangut                 = Script(0x74616e67)
	Tai_Viet               = Script(0x74617674)
	Telugu                 = Script(0x74656c75)
	Tifinagh               = Script(0x74666e67)
	Tagalog                = Script(0x74676c67)
	Thaana                 = Script(0x74686161)
	Thai                   = Script(0x74686169)
	Tibetan                = Script(0x74696274)
	Tirhuta                = Script(0x74697268)
	Ugaritic               = Script(0x75676172)
	Vai                    = Script(0x76616969)
	Warang_Citi            = Script(0x77617261)
	Wancho                 = Script(0x7763686f)
	Old_Persian            = Script(0x7870656f)
	Cuneiform              = Script(0x78737578)
	Yezidi                 = Script(0x79657a69)
	Yi                     = Script(0x79696969)
	Zanabazar_Square       = Script(0x7a616e62)
	Inherited              = Script(0x7a696e68)
	Common                 = Script(0x7a797979)
	Unknown                = Script(0x7a7a7a7a)
)

var scriptToTag = map[string]Script{
	"Adlam":                  Adlam,
	"Caucasian_Albanian":     Caucasian_Albanian,
	"Ahom":                   Ahom,
	"Arabic":                 Arabic,
	"Imperial_Aramaic":       Imperial_Aramaic,
	"Armenian":               Armenian,
	"Avestan":                Avestan,
	"Balinese":               Balinese,
	"Bamum":                  Bamum,
	"Bassa_Vah":              Bassa_Vah,
	"Batak":                  Batak,
	"Bengali":                Bengali,
	"Bhaiksuki":              Bhaiksuki,
	"Bopomofo":               Bopomofo,
	"Brahmi":                 Brahmi,
	"Braille":                Braille,
	"Buginese":               Buginese,
	"Buhid":                  Buhid,
	"Chakma":                 Chakma,
	"Canadian_Aboriginal":    Canadian_Aboriginal,
	"Carian":                 Carian,
	"Cham":                   Cham,
	"Cherokee":               Cherokee,
	"Chorasmian":             Chorasmian,
	"Coptic":                 Coptic,
	"Cypriot":                Cypriot,
	"Cyrillic":               Cyrillic,
	"Devanagari":             Devanagari,
	"Dives_Akuru":            Dives_Akuru,
	"Dogra":                  Dogra,
	"Deseret":                Deseret,
	"Duployan":               Duployan,
	"Egyptian_Hieroglyphs":   Egyptian_Hieroglyphs,
	"Elbasan":                Elbasan,
	"Elymaic":                Elymaic,
	"Ethiopic":               Ethiopic,
	"Georgian":               Georgian,
	"Glagolitic":             Glagolitic,
	"Gunjala_Gondi":          Gunjala_Gondi,
	"Masaram_Gondi":          Masaram_Gondi,
	"Gothic":                 Gothic,
	"Grantha":                Grantha,
	"Greek":                  Greek,
	"Gujarati":               Gujarati,
	"Gurmukhi":               Gurmukhi,
	"Hangul":                 Hangul,
	"Han":                    Han,
	"Hanunoo":                Hanunoo,
	"Hatran":                 Hatran,
	"Hebrew":                 Hebrew,
	"Hiragana":               Hiragana,
	"Anatolian_Hieroglyphs":  Anatolian_Hieroglyphs,
	"Pahawh_Hmong":           Pahawh_Hmong,
	"Nyiakeng_Puachue_Hmong": Nyiakeng_Puachue_Hmong,
	"Katakana_Or_Hiragana":   Katakana_Or_Hiragana,
	"Old_Hungarian":          Old_Hungarian,
	"Old_Italic":             Old_Italic,
	"Javanese":               Javanese,
	"Kayah_Li":               Kayah_Li,
	"Katakana":               Katakana,
	"Kharoshthi":             Kharoshthi,
	"Khmer":                  Khmer,
	"Khojki":                 Khojki,
	"Khitan_Small_Script":    Khitan_Small_Script,
	"Kannada":                Kannada,
	"Kaithi":                 Kaithi,
	"Tai_Tham":               Tai_Tham,
	"Lao":                    Lao,
	"Latin":                  Latin,
	"Lepcha":                 Lepcha,
	"Limbu":                  Limbu,
	"Linear_A":               Linear_A,
	"Linear_B":               Linear_B,
	"Lisu":                   Lisu,
	"Lycian":                 Lycian,
	"Lydian":                 Lydian,
	"Mahajani":               Mahajani,
	"Makasar":                Makasar,
	"Mandaic":                Mandaic,
	"Manichaean":             Manichaean,
	"Marchen":                Marchen,
	"Medefaidrin":            Medefaidrin,
	"Mende_Kikakui":          Mende_Kikakui,
	"Meroitic_Cursive":       Meroitic_Cursive,
	"Meroitic_Hieroglyphs":   Meroitic_Hieroglyphs,
	"Malayalam":              Malayalam,
	"Modi":                   Modi,
	"Mongolian":              Mongolian,
	"Mro":                    Mro,
	"Meetei_Mayek":           Meetei_Mayek,
	"Multani":                Multani,
	"Myanmar":                Myanmar,
	"Nandinagari":            Nandinagari,
	"Old_North_Arabian":      Old_North_Arabian,
	"Nabataean":              Nabataean,
	"Newa":                   Newa,
	"Nko":                    Nko,
	"Nushu":                  Nushu,
	"Ogham":                  Ogham,
	"Ol_Chiki":               Ol_Chiki,
	"Old_Turkic":             Old_Turkic,
	"Oriya":                  Oriya,
	"Osage":                  Osage,
	"Osmanya":                Osmanya,
	"Palmyrene":              Palmyrene,
	"Pau_Cin_Hau":            Pau_Cin_Hau,
	"Old_Permic":             Old_Permic,
	"Phags_Pa":               Phags_Pa,
	"Inscriptional_Pahlavi":  Inscriptional_Pahlavi,
	"Psalter_Pahlavi":        Psalter_Pahlavi,
	"Phoenician":             Phoenician,
	"Miao":                   Miao,
	"Inscriptional_Parthian": Inscriptional_Parthian,
	"Rejang":                 Rejang,
	"Hanifi_Rohingya":        Hanifi_Rohingya,
	"Runic":                  Runic,
	"Samaritan":              Samaritan,
	"Old_South_Arabian":      Old_South_Arabian,
	"Saurashtra":             Saurashtra,
	"SignWriting":            SignWriting,
	"Shavian":                Shavian,
	"Sharada":                Sharada,
	"Siddham":                Siddham,
	"Khudawadi":              Khudawadi,
	"Sinhala":                Sinhala,
	"Sogdian":                Sogdian,
	"Old_Sogdian":            Old_Sogdian,
	"Sora_Sompeng":           Sora_Sompeng,
	"Soyombo":                Soyombo,
	"Sundanese":              Sundanese,
	"Syloti_Nagri":           Syloti_Nagri,
	"Syriac":                 Syriac,
	"Tagbanwa":               Tagbanwa,
	"Takri":                  Takri,
	"Tai_Le":                 Tai_Le,
	"New_Tai_Lue":            New_Tai_Lue,
	"Tamil":                  Tamil,
	"Tangut":                 Tangut,
	"Tai_Viet":               Tai_Viet,
	"Telugu":                 Telugu,
	"Tifinagh":               Tifinagh,
	"Tagalog":                Tagalog,
	"Thaana":                 Thaana,
	"Thai":                   Thai,
	"Tibetan":                Tibetan,
	"Tirhuta":                Tirhuta,
	"Ugaritic":               Ugaritic,
	"Vai":                    Vai,
	"Warang_Citi":            Warang_Citi,
	"Wancho":                 Wancho,
	"Old_Persian":            Old_Persian,
	"Cuneiform":              Cuneiform,
	"Yezidi":                 Yezidi,
	"Yi":                     Yi,
	"Zanabazar_Square":       Zanabazar_Square,
	"Inherited":              Inherited,
	"Common":                 Common,
	"Unknown":                Unknown,
}
