package unicodedata

import "github.com/benoitkugler/textlayout/language"

// Code generated by generate/main.go DO NOT EDIT.

func JoinArabic(char rune) ArabicJoining { // 775 entries
	switch char {
	case 0x0600:
		return 'U'
	case 0x0601:
		return 'U'
	case 0x0602:
		return 'U'
	case 0x0603:
		return 'U'
	case 0x0604:
		return 'U'
	case 0x0605:
		return 'U'
	case 0x0608:
		return 'U'
	case 0x060b:
		return 'U'
	case 0x0620:
		return 'D'
	case 0x0621:
		return 'U'
	case 0x0622:
		return 'R'
	case 0x0623:
		return 'R'
	case 0x0624:
		return 'R'
	case 0x0625:
		return 'R'
	case 0x0626:
		return 'D'
	case 0x0627:
		return 'R'
	case 0x0628:
		return 'D'
	case 0x0629:
		return 'R'
	case 0x062a:
		return 'D'
	case 0x062b:
		return 'D'
	case 0x062c:
		return 'D'
	case 0x062d:
		return 'D'
	case 0x062e:
		return 'D'
	case 0x062f:
		return 'R'
	case 0x0630:
		return 'R'
	case 0x0631:
		return 'R'
	case 0x0632:
		return 'R'
	case 0x0633:
		return 'D'
	case 0x0634:
		return 'D'
	case 0x0635:
		return 'D'
	case 0x0636:
		return 'D'
	case 0x0637:
		return 'D'
	case 0x0638:
		return 'D'
	case 0x0639:
		return 'D'
	case 0x063a:
		return 'D'
	case 0x063b:
		return 'D'
	case 0x063c:
		return 'D'
	case 0x063d:
		return 'D'
	case 0x063e:
		return 'D'
	case 0x063f:
		return 'D'
	case 0x0640:
		return 'C'
	case 0x0641:
		return 'D'
	case 0x0642:
		return 'D'
	case 0x0643:
		return 'D'
	case 0x0644:
		return 'D'
	case 0x0645:
		return 'D'
	case 0x0646:
		return 'D'
	case 0x0647:
		return 'D'
	case 0x0648:
		return 'R'
	case 0x0649:
		return 'D'
	case 0x064a:
		return 'D'
	case 0x066e:
		return 'D'
	case 0x066f:
		return 'D'
	case 0x0671:
		return 'R'
	case 0x0672:
		return 'R'
	case 0x0673:
		return 'R'
	case 0x0674:
		return 'U'
	case 0x0675:
		return 'R'
	case 0x0676:
		return 'R'
	case 0x0677:
		return 'R'
	case 0x0678:
		return 'D'
	case 0x0679:
		return 'D'
	case 0x067a:
		return 'D'
	case 0x067b:
		return 'D'
	case 0x067c:
		return 'D'
	case 0x067d:
		return 'D'
	case 0x067e:
		return 'D'
	case 0x067f:
		return 'D'
	case 0x0680:
		return 'D'
	case 0x0681:
		return 'D'
	case 0x0682:
		return 'D'
	case 0x0683:
		return 'D'
	case 0x0684:
		return 'D'
	case 0x0685:
		return 'D'
	case 0x0686:
		return 'D'
	case 0x0687:
		return 'D'
	case 0x0688:
		return 'R'
	case 0x0689:
		return 'R'
	case 0x068a:
		return 'R'
	case 0x068b:
		return 'R'
	case 0x068c:
		return 'R'
	case 0x068d:
		return 'R'
	case 0x068e:
		return 'R'
	case 0x068f:
		return 'R'
	case 0x0690:
		return 'R'
	case 0x0691:
		return 'R'
	case 0x0692:
		return 'R'
	case 0x0693:
		return 'R'
	case 0x0694:
		return 'R'
	case 0x0695:
		return 'R'
	case 0x0696:
		return 'R'
	case 0x0697:
		return 'R'
	case 0x0698:
		return 'R'
	case 0x0699:
		return 'R'
	case 0x069a:
		return 'D'
	case 0x069b:
		return 'D'
	case 0x069c:
		return 'D'
	case 0x069d:
		return 'D'
	case 0x069e:
		return 'D'
	case 0x069f:
		return 'D'
	case 0x06a0:
		return 'D'
	case 0x06a1:
		return 'D'
	case 0x06a2:
		return 'D'
	case 0x06a3:
		return 'D'
	case 0x06a4:
		return 'D'
	case 0x06a5:
		return 'D'
	case 0x06a6:
		return 'D'
	case 0x06a7:
		return 'D'
	case 0x06a8:
		return 'D'
	case 0x06a9:
		return 'D'
	case 0x06aa:
		return 'D'
	case 0x06ab:
		return 'D'
	case 0x06ac:
		return 'D'
	case 0x06ad:
		return 'D'
	case 0x06ae:
		return 'D'
	case 0x06af:
		return 'D'
	case 0x06b0:
		return 'D'
	case 0x06b1:
		return 'D'
	case 0x06b2:
		return 'D'
	case 0x06b3:
		return 'D'
	case 0x06b4:
		return 'D'
	case 0x06b5:
		return 'D'
	case 0x06b6:
		return 'D'
	case 0x06b7:
		return 'D'
	case 0x06b8:
		return 'D'
	case 0x06b9:
		return 'D'
	case 0x06ba:
		return 'D'
	case 0x06bb:
		return 'D'
	case 0x06bc:
		return 'D'
	case 0x06bd:
		return 'D'
	case 0x06be:
		return 'D'
	case 0x06bf:
		return 'D'
	case 0x06c0:
		return 'R'
	case 0x06c1:
		return 'D'
	case 0x06c2:
		return 'D'
	case 0x06c3:
		return 'R'
	case 0x06c4:
		return 'R'
	case 0x06c5:
		return 'R'
	case 0x06c6:
		return 'R'
	case 0x06c7:
		return 'R'
	case 0x06c8:
		return 'R'
	case 0x06c9:
		return 'R'
	case 0x06ca:
		return 'R'
	case 0x06cb:
		return 'R'
	case 0x06cc:
		return 'D'
	case 0x06cd:
		return 'R'
	case 0x06ce:
		return 'D'
	case 0x06cf:
		return 'R'
	case 0x06d0:
		return 'D'
	case 0x06d1:
		return 'D'
	case 0x06d2:
		return 'R'
	case 0x06d3:
		return 'R'
	case 0x06d5:
		return 'R'
	case 0x06dd:
		return 'U'
	case 0x06ee:
		return 'R'
	case 0x06ef:
		return 'R'
	case 0x06fa:
		return 'D'
	case 0x06fb:
		return 'D'
	case 0x06fc:
		return 'D'
	case 0x06ff:
		return 'D'
	case 0x070f:
		return 'T'
	case 0x0710:
		return 'a'
	case 0x0712:
		return 'D'
	case 0x0713:
		return 'D'
	case 0x0714:
		return 'D'
	case 0x0715:
		return 'd'
	case 0x0716:
		return 'd'
	case 0x0717:
		return 'R'
	case 0x0718:
		return 'R'
	case 0x0719:
		return 'R'
	case 0x071a:
		return 'D'
	case 0x071b:
		return 'D'
	case 0x071c:
		return 'D'
	case 0x071d:
		return 'D'
	case 0x071e:
		return 'R'
	case 0x071f:
		return 'D'
	case 0x0720:
		return 'D'
	case 0x0721:
		return 'D'
	case 0x0722:
		return 'D'
	case 0x0723:
		return 'D'
	case 0x0724:
		return 'D'
	case 0x0725:
		return 'D'
	case 0x0726:
		return 'D'
	case 0x0727:
		return 'D'
	case 0x0728:
		return 'R'
	case 0x0729:
		return 'D'
	case 0x072a:
		return 'd'
	case 0x072b:
		return 'D'
	case 0x072c:
		return 'R'
	case 0x072d:
		return 'D'
	case 0x072e:
		return 'D'
	case 0x072f:
		return 'd'
	case 0x074d:
		return 'R'
	case 0x074e:
		return 'D'
	case 0x074f:
		return 'D'
	case 0x0750:
		return 'D'
	case 0x0751:
		return 'D'
	case 0x0752:
		return 'D'
	case 0x0753:
		return 'D'
	case 0x0754:
		return 'D'
	case 0x0755:
		return 'D'
	case 0x0756:
		return 'D'
	case 0x0757:
		return 'D'
	case 0x0758:
		return 'D'
	case 0x0759:
		return 'R'
	case 0x075a:
		return 'R'
	case 0x075b:
		return 'R'
	case 0x075c:
		return 'D'
	case 0x075d:
		return 'D'
	case 0x075e:
		return 'D'
	case 0x075f:
		return 'D'
	case 0x0760:
		return 'D'
	case 0x0761:
		return 'D'
	case 0x0762:
		return 'D'
	case 0x0763:
		return 'D'
	case 0x0764:
		return 'D'
	case 0x0765:
		return 'D'
	case 0x0766:
		return 'D'
	case 0x0767:
		return 'D'
	case 0x0768:
		return 'D'
	case 0x0769:
		return 'D'
	case 0x076a:
		return 'D'
	case 0x076b:
		return 'R'
	case 0x076c:
		return 'R'
	case 0x076d:
		return 'D'
	case 0x076e:
		return 'D'
	case 0x076f:
		return 'D'
	case 0x0770:
		return 'D'
	case 0x0771:
		return 'R'
	case 0x0772:
		return 'D'
	case 0x0773:
		return 'R'
	case 0x0774:
		return 'R'
	case 0x0775:
		return 'D'
	case 0x0776:
		return 'D'
	case 0x0777:
		return 'D'
	case 0x0778:
		return 'R'
	case 0x0779:
		return 'R'
	case 0x077a:
		return 'D'
	case 0x077b:
		return 'D'
	case 0x077c:
		return 'D'
	case 0x077d:
		return 'D'
	case 0x077e:
		return 'D'
	case 0x077f:
		return 'D'
	case 0x07ca:
		return 'D'
	case 0x07cb:
		return 'D'
	case 0x07cc:
		return 'D'
	case 0x07cd:
		return 'D'
	case 0x07ce:
		return 'D'
	case 0x07cf:
		return 'D'
	case 0x07d0:
		return 'D'
	case 0x07d1:
		return 'D'
	case 0x07d2:
		return 'D'
	case 0x07d3:
		return 'D'
	case 0x07d4:
		return 'D'
	case 0x07d5:
		return 'D'
	case 0x07d6:
		return 'D'
	case 0x07d7:
		return 'D'
	case 0x07d8:
		return 'D'
	case 0x07d9:
		return 'D'
	case 0x07da:
		return 'D'
	case 0x07db:
		return 'D'
	case 0x07dc:
		return 'D'
	case 0x07dd:
		return 'D'
	case 0x07de:
		return 'D'
	case 0x07df:
		return 'D'
	case 0x07e0:
		return 'D'
	case 0x07e1:
		return 'D'
	case 0x07e2:
		return 'D'
	case 0x07e3:
		return 'D'
	case 0x07e4:
		return 'D'
	case 0x07e5:
		return 'D'
	case 0x07e6:
		return 'D'
	case 0x07e7:
		return 'D'
	case 0x07e8:
		return 'D'
	case 0x07e9:
		return 'D'
	case 0x07ea:
		return 'D'
	case 0x07fa:
		return 'C'
	case 0x0840:
		return 'R'
	case 0x0841:
		return 'D'
	case 0x0842:
		return 'D'
	case 0x0843:
		return 'D'
	case 0x0844:
		return 'D'
	case 0x0845:
		return 'D'
	case 0x0846:
		return 'R'
	case 0x0847:
		return 'R'
	case 0x0848:
		return 'D'
	case 0x0849:
		return 'R'
	case 0x084a:
		return 'D'
	case 0x084b:
		return 'D'
	case 0x084c:
		return 'D'
	case 0x084d:
		return 'D'
	case 0x084e:
		return 'D'
	case 0x084f:
		return 'D'
	case 0x0850:
		return 'D'
	case 0x0851:
		return 'D'
	case 0x0852:
		return 'D'
	case 0x0853:
		return 'D'
	case 0x0854:
		return 'R'
	case 0x0855:
		return 'D'
	case 0x0856:
		return 'R'
	case 0x0857:
		return 'R'
	case 0x0858:
		return 'R'
	case 0x0860:
		return 'D'
	case 0x0861:
		return 'U'
	case 0x0862:
		return 'D'
	case 0x0863:
		return 'D'
	case 0x0864:
		return 'D'
	case 0x0865:
		return 'D'
	case 0x0866:
		return 'U'
	case 0x0867:
		return 'R'
	case 0x0868:
		return 'D'
	case 0x0869:
		return 'R'
	case 0x086a:
		return 'R'
	case 0x08a0:
		return 'D'
	case 0x08a1:
		return 'D'
	case 0x08a2:
		return 'D'
	case 0x08a3:
		return 'D'
	case 0x08a4:
		return 'D'
	case 0x08a5:
		return 'D'
	case 0x08a6:
		return 'D'
	case 0x08a7:
		return 'D'
	case 0x08a8:
		return 'D'
	case 0x08a9:
		return 'D'
	case 0x08aa:
		return 'R'
	case 0x08ab:
		return 'R'
	case 0x08ac:
		return 'R'
	case 0x08ad:
		return 'U'
	case 0x08ae:
		return 'R'
	case 0x08af:
		return 'D'
	case 0x08b0:
		return 'D'
	case 0x08b1:
		return 'R'
	case 0x08b2:
		return 'R'
	case 0x08b3:
		return 'D'
	case 0x08b4:
		return 'D'
	case 0x08b6:
		return 'D'
	case 0x08b7:
		return 'D'
	case 0x08b8:
		return 'D'
	case 0x08b9:
		return 'R'
	case 0x08ba:
		return 'D'
	case 0x08bb:
		return 'D'
	case 0x08bc:
		return 'D'
	case 0x08bd:
		return 'D'
	case 0x08be:
		return 'D'
	case 0x08bf:
		return 'D'
	case 0x08c0:
		return 'D'
	case 0x08c1:
		return 'D'
	case 0x08c2:
		return 'D'
	case 0x08c3:
		return 'D'
	case 0x08c4:
		return 'D'
	case 0x08c5:
		return 'D'
	case 0x08c6:
		return 'D'
	case 0x08c7:
		return 'D'
	case 0x08e2:
		return 'U'
	case 0x1806:
		return 'U'
	case 0x1807:
		return 'D'
	case 0x180a:
		return 'C'
	case 0x180e:
		return 'U'
	case 0x1820:
		return 'D'
	case 0x1821:
		return 'D'
	case 0x1822:
		return 'D'
	case 0x1823:
		return 'D'
	case 0x1824:
		return 'D'
	case 0x1825:
		return 'D'
	case 0x1826:
		return 'D'
	case 0x1827:
		return 'D'
	case 0x1828:
		return 'D'
	case 0x1829:
		return 'D'
	case 0x182a:
		return 'D'
	case 0x182b:
		return 'D'
	case 0x182c:
		return 'D'
	case 0x182d:
		return 'D'
	case 0x182e:
		return 'D'
	case 0x182f:
		return 'D'
	case 0x1830:
		return 'D'
	case 0x1831:
		return 'D'
	case 0x1832:
		return 'D'
	case 0x1833:
		return 'D'
	case 0x1834:
		return 'D'
	case 0x1835:
		return 'D'
	case 0x1836:
		return 'D'
	case 0x1837:
		return 'D'
	case 0x1838:
		return 'D'
	case 0x1839:
		return 'D'
	case 0x183a:
		return 'D'
	case 0x183b:
		return 'D'
	case 0x183c:
		return 'D'
	case 0x183d:
		return 'D'
	case 0x183e:
		return 'D'
	case 0x183f:
		return 'D'
	case 0x1840:
		return 'D'
	case 0x1841:
		return 'D'
	case 0x1842:
		return 'D'
	case 0x1843:
		return 'D'
	case 0x1844:
		return 'D'
	case 0x1845:
		return 'D'
	case 0x1846:
		return 'D'
	case 0x1847:
		return 'D'
	case 0x1848:
		return 'D'
	case 0x1849:
		return 'D'
	case 0x184a:
		return 'D'
	case 0x184b:
		return 'D'
	case 0x184c:
		return 'D'
	case 0x184d:
		return 'D'
	case 0x184e:
		return 'D'
	case 0x184f:
		return 'D'
	case 0x1850:
		return 'D'
	case 0x1851:
		return 'D'
	case 0x1852:
		return 'D'
	case 0x1853:
		return 'D'
	case 0x1854:
		return 'D'
	case 0x1855:
		return 'D'
	case 0x1856:
		return 'D'
	case 0x1857:
		return 'D'
	case 0x1858:
		return 'D'
	case 0x1859:
		return 'D'
	case 0x185a:
		return 'D'
	case 0x185b:
		return 'D'
	case 0x185c:
		return 'D'
	case 0x185d:
		return 'D'
	case 0x185e:
		return 'D'
	case 0x185f:
		return 'D'
	case 0x1860:
		return 'D'
	case 0x1861:
		return 'D'
	case 0x1862:
		return 'D'
	case 0x1863:
		return 'D'
	case 0x1864:
		return 'D'
	case 0x1865:
		return 'D'
	case 0x1866:
		return 'D'
	case 0x1867:
		return 'D'
	case 0x1868:
		return 'D'
	case 0x1869:
		return 'D'
	case 0x186a:
		return 'D'
	case 0x186b:
		return 'D'
	case 0x186c:
		return 'D'
	case 0x186d:
		return 'D'
	case 0x186e:
		return 'D'
	case 0x186f:
		return 'D'
	case 0x1870:
		return 'D'
	case 0x1871:
		return 'D'
	case 0x1872:
		return 'D'
	case 0x1873:
		return 'D'
	case 0x1874:
		return 'D'
	case 0x1875:
		return 'D'
	case 0x1876:
		return 'D'
	case 0x1877:
		return 'D'
	case 0x1878:
		return 'D'
	case 0x1880:
		return 'U'
	case 0x1881:
		return 'U'
	case 0x1882:
		return 'U'
	case 0x1883:
		return 'U'
	case 0x1884:
		return 'U'
	case 0x1885:
		return 'T'
	case 0x1886:
		return 'T'
	case 0x1887:
		return 'D'
	case 0x1888:
		return 'D'
	case 0x1889:
		return 'D'
	case 0x188a:
		return 'D'
	case 0x188b:
		return 'D'
	case 0x188c:
		return 'D'
	case 0x188d:
		return 'D'
	case 0x188e:
		return 'D'
	case 0x188f:
		return 'D'
	case 0x1890:
		return 'D'
	case 0x1891:
		return 'D'
	case 0x1892:
		return 'D'
	case 0x1893:
		return 'D'
	case 0x1894:
		return 'D'
	case 0x1895:
		return 'D'
	case 0x1896:
		return 'D'
	case 0x1897:
		return 'D'
	case 0x1898:
		return 'D'
	case 0x1899:
		return 'D'
	case 0x189a:
		return 'D'
	case 0x189b:
		return 'D'
	case 0x189c:
		return 'D'
	case 0x189d:
		return 'D'
	case 0x189e:
		return 'D'
	case 0x189f:
		return 'D'
	case 0x18a0:
		return 'D'
	case 0x18a1:
		return 'D'
	case 0x18a2:
		return 'D'
	case 0x18a3:
		return 'D'
	case 0x18a4:
		return 'D'
	case 0x18a5:
		return 'D'
	case 0x18a6:
		return 'D'
	case 0x18a7:
		return 'D'
	case 0x18a8:
		return 'D'
	case 0x18aa:
		return 'D'
	case 0x200c:
		return 'U'
	case 0x200d:
		return 'C'
	case 0x202f:
		return 'U'
	case 0x2066:
		return 'U'
	case 0x2067:
		return 'U'
	case 0x2068:
		return 'U'
	case 0x2069:
		return 'U'
	case 0xa840:
		return 'D'
	case 0xa841:
		return 'D'
	case 0xa842:
		return 'D'
	case 0xa843:
		return 'D'
	case 0xa844:
		return 'D'
	case 0xa845:
		return 'D'
	case 0xa846:
		return 'D'
	case 0xa847:
		return 'D'
	case 0xa848:
		return 'D'
	case 0xa849:
		return 'D'
	case 0xa84a:
		return 'D'
	case 0xa84b:
		return 'D'
	case 0xa84c:
		return 'D'
	case 0xa84d:
		return 'D'
	case 0xa84e:
		return 'D'
	case 0xa84f:
		return 'D'
	case 0xa850:
		return 'D'
	case 0xa851:
		return 'D'
	case 0xa852:
		return 'D'
	case 0xa853:
		return 'D'
	case 0xa854:
		return 'D'
	case 0xa855:
		return 'D'
	case 0xa856:
		return 'D'
	case 0xa857:
		return 'D'
	case 0xa858:
		return 'D'
	case 0xa859:
		return 'D'
	case 0xa85a:
		return 'D'
	case 0xa85b:
		return 'D'
	case 0xa85c:
		return 'D'
	case 0xa85d:
		return 'D'
	case 0xa85e:
		return 'D'
	case 0xa85f:
		return 'D'
	case 0xa860:
		return 'D'
	case 0xa861:
		return 'D'
	case 0xa862:
		return 'D'
	case 0xa863:
		return 'D'
	case 0xa864:
		return 'D'
	case 0xa865:
		return 'D'
	case 0xa866:
		return 'D'
	case 0xa867:
		return 'D'
	case 0xa868:
		return 'D'
	case 0xa869:
		return 'D'
	case 0xa86a:
		return 'D'
	case 0xa86b:
		return 'D'
	case 0xa86c:
		return 'D'
	case 0xa86d:
		return 'D'
	case 0xa86e:
		return 'D'
	case 0xa86f:
		return 'D'
	case 0xa870:
		return 'D'
	case 0xa871:
		return 'D'
	case 0xa872:
		return 'L'
	case 0xa873:
		return 'U'
	case 0x10ac0:
		return 'D'
	case 0x10ac1:
		return 'D'
	case 0x10ac2:
		return 'D'
	case 0x10ac3:
		return 'D'
	case 0x10ac4:
		return 'D'
	case 0x10ac5:
		return 'R'
	case 0x10ac6:
		return 'U'
	case 0x10ac7:
		return 'R'
	case 0x10ac8:
		return 'U'
	case 0x10ac9:
		return 'R'
	case 0x10aca:
		return 'R'
	case 0x10acb:
		return 'U'
	case 0x10acc:
		return 'U'
	case 0x10acd:
		return 'L'
	case 0x10ace:
		return 'R'
	case 0x10acf:
		return 'R'
	case 0x10ad0:
		return 'R'
	case 0x10ad1:
		return 'R'
	case 0x10ad2:
		return 'R'
	case 0x10ad3:
		return 'D'
	case 0x10ad4:
		return 'D'
	case 0x10ad5:
		return 'D'
	case 0x10ad6:
		return 'D'
	case 0x10ad7:
		return 'L'
	case 0x10ad8:
		return 'D'
	case 0x10ad9:
		return 'D'
	case 0x10ada:
		return 'D'
	case 0x10adb:
		return 'D'
	case 0x10adc:
		return 'D'
	case 0x10add:
		return 'R'
	case 0x10ade:
		return 'D'
	case 0x10adf:
		return 'D'
	case 0x10ae0:
		return 'D'
	case 0x10ae1:
		return 'R'
	case 0x10ae2:
		return 'U'
	case 0x10ae3:
		return 'U'
	case 0x10ae4:
		return 'R'
	case 0x10aeb:
		return 'D'
	case 0x10aec:
		return 'D'
	case 0x10aed:
		return 'D'
	case 0x10aee:
		return 'D'
	case 0x10aef:
		return 'R'
	case 0x10b80:
		return 'D'
	case 0x10b81:
		return 'R'
	case 0x10b82:
		return 'D'
	case 0x10b83:
		return 'R'
	case 0x10b84:
		return 'R'
	case 0x10b85:
		return 'R'
	case 0x10b86:
		return 'D'
	case 0x10b87:
		return 'D'
	case 0x10b88:
		return 'D'
	case 0x10b89:
		return 'R'
	case 0x10b8a:
		return 'D'
	case 0x10b8b:
		return 'D'
	case 0x10b8c:
		return 'R'
	case 0x10b8d:
		return 'D'
	case 0x10b8e:
		return 'R'
	case 0x10b8f:
		return 'R'
	case 0x10b90:
		return 'D'
	case 0x10b91:
		return 'R'
	case 0x10ba9:
		return 'R'
	case 0x10baa:
		return 'R'
	case 0x10bab:
		return 'R'
	case 0x10bac:
		return 'R'
	case 0x10bad:
		return 'D'
	case 0x10bae:
		return 'D'
	case 0x10baf:
		return 'U'
	case 0x10d00:
		return 'L'
	case 0x10d01:
		return 'D'
	case 0x10d02:
		return 'D'
	case 0x10d03:
		return 'D'
	case 0x10d04:
		return 'D'
	case 0x10d05:
		return 'D'
	case 0x10d06:
		return 'D'
	case 0x10d07:
		return 'D'
	case 0x10d08:
		return 'D'
	case 0x10d09:
		return 'D'
	case 0x10d0a:
		return 'D'
	case 0x10d0b:
		return 'D'
	case 0x10d0c:
		return 'D'
	case 0x10d0d:
		return 'D'
	case 0x10d0e:
		return 'D'
	case 0x10d0f:
		return 'D'
	case 0x10d10:
		return 'D'
	case 0x10d11:
		return 'D'
	case 0x10d12:
		return 'D'
	case 0x10d13:
		return 'D'
	case 0x10d14:
		return 'D'
	case 0x10d15:
		return 'D'
	case 0x10d16:
		return 'D'
	case 0x10d17:
		return 'D'
	case 0x10d18:
		return 'D'
	case 0x10d19:
		return 'D'
	case 0x10d1a:
		return 'D'
	case 0x10d1b:
		return 'D'
	case 0x10d1c:
		return 'D'
	case 0x10d1d:
		return 'D'
	case 0x10d1e:
		return 'D'
	case 0x10d1f:
		return 'D'
	case 0x10d20:
		return 'D'
	case 0x10d21:
		return 'D'
	case 0x10d22:
		return 'R'
	case 0x10d23:
		return 'D'
	case 0x10f30:
		return 'D'
	case 0x10f31:
		return 'D'
	case 0x10f32:
		return 'D'
	case 0x10f33:
		return 'R'
	case 0x10f34:
		return 'D'
	case 0x10f35:
		return 'D'
	case 0x10f36:
		return 'D'
	case 0x10f37:
		return 'D'
	case 0x10f38:
		return 'D'
	case 0x10f39:
		return 'D'
	case 0x10f3a:
		return 'D'
	case 0x10f3b:
		return 'D'
	case 0x10f3c:
		return 'D'
	case 0x10f3d:
		return 'D'
	case 0x10f3e:
		return 'D'
	case 0x10f3f:
		return 'D'
	case 0x10f40:
		return 'D'
	case 0x10f41:
		return 'D'
	case 0x10f42:
		return 'D'
	case 0x10f43:
		return 'D'
	case 0x10f44:
		return 'D'
	case 0x10f45:
		return 'U'
	case 0x10f51:
		return 'D'
	case 0x10f52:
		return 'D'
	case 0x10f53:
		return 'D'
	case 0x10f54:
		return 'R'
	case 0x10fb0:
		return 'D'
	case 0x10fb1:
		return 'U'
	case 0x10fb2:
		return 'D'
	case 0x10fb3:
		return 'D'
	case 0x10fb4:
		return 'R'
	case 0x10fb5:
		return 'R'
	case 0x10fb6:
		return 'R'
	case 0x10fb7:
		return 'U'
	case 0x10fb8:
		return 'D'
	case 0x10fb9:
		return 'R'
	case 0x10fba:
		return 'R'
	case 0x10fbb:
		return 'D'
	case 0x10fbc:
		return 'D'
	case 0x10fbd:
		return 'R'
	case 0x10fbe:
		return 'D'
	case 0x10fbf:
		return 'D'
	case 0x10fc0:
		return 'U'
	case 0x10fc1:
		return 'D'
	case 0x10fc2:
		return 'R'
	case 0x10fc3:
		return 'R'
	case 0x10fc4:
		return 'D'
	case 0x10fc5:
		return 'U'
	case 0x10fc6:
		return 'U'
	case 0x10fc7:
		return 'U'
	case 0x10fc8:
		return 'U'
	case 0x10fc9:
		return 'R'
	case 0x10fca:
		return 'D'
	case 0x10fcb:
		return 'L'
	case 0x110bd:
		return 'U'
	case 0x110cd:
		return 'U'
	case 0x1e900:
		return 'D'
	case 0x1e901:
		return 'D'
	case 0x1e902:
		return 'D'
	case 0x1e903:
		return 'D'
	case 0x1e904:
		return 'D'
	case 0x1e905:
		return 'D'
	case 0x1e906:
		return 'D'
	case 0x1e907:
		return 'D'
	case 0x1e908:
		return 'D'
	case 0x1e909:
		return 'D'
	case 0x1e90a:
		return 'D'
	case 0x1e90b:
		return 'D'
	case 0x1e90c:
		return 'D'
	case 0x1e90d:
		return 'D'
	case 0x1e90e:
		return 'D'
	case 0x1e90f:
		return 'D'
	case 0x1e910:
		return 'D'
	case 0x1e911:
		return 'D'
	case 0x1e912:
		return 'D'
	case 0x1e913:
		return 'D'
	case 0x1e914:
		return 'D'
	case 0x1e915:
		return 'D'
	case 0x1e916:
		return 'D'
	case 0x1e917:
		return 'D'
	case 0x1e918:
		return 'D'
	case 0x1e919:
		return 'D'
	case 0x1e91a:
		return 'D'
	case 0x1e91b:
		return 'D'
	case 0x1e91c:
		return 'D'
	case 0x1e91d:
		return 'D'
	case 0x1e91e:
		return 'D'
	case 0x1e91f:
		return 'D'
	case 0x1e920:
		return 'D'
	case 0x1e921:
		return 'D'
	case 0x1e922:
		return 'D'
	case 0x1e923:
		return 'D'
	case 0x1e924:
		return 'D'
	case 0x1e925:
		return 'D'
	case 0x1e926:
		return 'D'
	case 0x1e927:
		return 'D'
	case 0x1e928:
		return 'D'
	case 0x1e929:
		return 'D'
	case 0x1e92a:
		return 'D'
	case 0x1e92b:
		return 'D'
	case 0x1e92c:
		return 'D'
	case 0x1e92d:
		return 'D'
	case 0x1e92e:
		return 'D'
	case 0x1e92f:
		return 'D'
	case 0x1e930:
		return 'D'
	case 0x1e931:
		return 'D'
	case 0x1e932:
		return 'D'
	case 0x1e933:
		return 'D'
	case 0x1e934:
		return 'D'
	case 0x1e935:
		return 'D'
	case 0x1e936:
		return 'D'
	case 0x1e937:
		return 'D'
	case 0x1e938:
		return 'D'
	case 0x1e939:
		return 'D'
	case 0x1e93a:
		return 'D'
	case 0x1e93b:
		return 'D'
	case 0x1e93c:
		return 'D'
	case 0x1e93d:
		return 'D'
	case 0x1e93e:
		return 'D'
	case 0x1e93f:
		return 'D'
	case 0x1e940:
		return 'D'
	case 0x1e941:
		return 'D'
	case 0x1e942:
		return 'D'
	case 0x1e943:
		return 'D'
	case 0x1e94b:
		return 'T'
	}
	return 0
}

const FirstArabicShape = 0x0621
const LastArabicShape = 0x06d3

// ArabicShaping defines the shaping for arabic runes. Each entry is indexed by
// the shape, between 0 and 3:
//   - 0: isolated
//   - 1: final
//   - 2: initial
//   - 3: medial
//
// See also the bounds given by FirstArabicShape and LastArabicShape.
var ArabicShaping = [...][4]uint16{ // required memory: 2 KB
	{65152, 1569, 1569, 1569},
	{65153, 65154, 1570, 1570},
	{65155, 65156, 1571, 1571},
	{65157, 65158, 1572, 1572},
	{65159, 65160, 1573, 1573},
	{65161, 65162, 65163, 65164},
	{65165, 65166, 1575, 1575},
	{65167, 65168, 65169, 65170},
	{65171, 65172, 1577, 1577},
	{65173, 65174, 65175, 65176},
	{65177, 65178, 65179, 65180},
	{65181, 65182, 65183, 65184},
	{65185, 65186, 65187, 65188},
	{65189, 65190, 65191, 65192},
	{65193, 65194, 1583, 1583},
	{65195, 65196, 1584, 1584},
	{65197, 65198, 1585, 1585},
	{65199, 65200, 1586, 1586},
	{65201, 65202, 65203, 65204},
	{65205, 65206, 65207, 65208},
	{65209, 65210, 65211, 65212},
	{65213, 65214, 65215, 65216},
	{65217, 65218, 65219, 65220},
	{65221, 65222, 65223, 65224},
	{65225, 65226, 65227, 65228},
	{65229, 65230, 65231, 65232},
	{1595, 1595, 1595, 1595},
	{1596, 1596, 1596, 1596},
	{1597, 1597, 1597, 1597},
	{1598, 1598, 1598, 1598},
	{1599, 1599, 1599, 1599},
	{1600, 1600, 1600, 1600},
	{65233, 65234, 65235, 65236},
	{65237, 65238, 65239, 65240},
	{65241, 65242, 65243, 65244},
	{65245, 65246, 65247, 65248},
	{65249, 65250, 65251, 65252},
	{65253, 65254, 65255, 65256},
	{65257, 65258, 65259, 65260},
	{65261, 65262, 1608, 1608},
	{65263, 65264, 64488, 64489},
	{65265, 65266, 65267, 65268},
	{1611, 1611, 1611, 1611},
	{1612, 1612, 1612, 1612},
	{1613, 1613, 1613, 1613},
	{1614, 1614, 1614, 1614},
	{1615, 1615, 1615, 1615},
	{1616, 1616, 1616, 1616},
	{1617, 1617, 1617, 1617},
	{1618, 1618, 1618, 1618},
	{1619, 1619, 1619, 1619},
	{1620, 1620, 1620, 1620},
	{1621, 1621, 1621, 1621},
	{1622, 1622, 1622, 1622},
	{1623, 1623, 1623, 1623},
	{1624, 1624, 1624, 1624},
	{1625, 1625, 1625, 1625},
	{1626, 1626, 1626, 1626},
	{1627, 1627, 1627, 1627},
	{1628, 1628, 1628, 1628},
	{1629, 1629, 1629, 1629},
	{1630, 1630, 1630, 1630},
	{1631, 1631, 1631, 1631},
	{1632, 1632, 1632, 1632},
	{1633, 1633, 1633, 1633},
	{1634, 1634, 1634, 1634},
	{1635, 1635, 1635, 1635},
	{1636, 1636, 1636, 1636},
	{1637, 1637, 1637, 1637},
	{1638, 1638, 1638, 1638},
	{1639, 1639, 1639, 1639},
	{1640, 1640, 1640, 1640},
	{1641, 1641, 1641, 1641},
	{1642, 1642, 1642, 1642},
	{1643, 1643, 1643, 1643},
	{1644, 1644, 1644, 1644},
	{1645, 1645, 1645, 1645},
	{1646, 1646, 1646, 1646},
	{1647, 1647, 1647, 1647},
	{1648, 1648, 1648, 1648},
	{64336, 64337, 1649, 1649},
	{1650, 1650, 1650, 1650},
	{1651, 1651, 1651, 1651},
	{1652, 1652, 1652, 1652},
	{1653, 1653, 1653, 1653},
	{1654, 1654, 1654, 1654},
	{64477, 1655, 1655, 1655},
	{1656, 1656, 1656, 1656},
	{64358, 64359, 64360, 64361},
	{64350, 64351, 64352, 64353},
	{64338, 64339, 64340, 64341},
	{1660, 1660, 1660, 1660},
	{1661, 1661, 1661, 1661},
	{64342, 64343, 64344, 64345},
	{64354, 64355, 64356, 64357},
	{64346, 64347, 64348, 64349},
	{1665, 1665, 1665, 1665},
	{1666, 1666, 1666, 1666},
	{64374, 64375, 64376, 64377},
	{64370, 64371, 64372, 64373},
	{1669, 1669, 1669, 1669},
	{64378, 64379, 64380, 64381},
	{64382, 64383, 64384, 64385},
	{64392, 64393, 1672, 1672},
	{1673, 1673, 1673, 1673},
	{1674, 1674, 1674, 1674},
	{1675, 1675, 1675, 1675},
	{64388, 64389, 1676, 1676},
	{64386, 64387, 1677, 1677},
	{64390, 64391, 1678, 1678},
	{1679, 1679, 1679, 1679},
	{1680, 1680, 1680, 1680},
	{64396, 64397, 1681, 1681},
	{1682, 1682, 1682, 1682},
	{1683, 1683, 1683, 1683},
	{1684, 1684, 1684, 1684},
	{1685, 1685, 1685, 1685},
	{1686, 1686, 1686, 1686},
	{1687, 1687, 1687, 1687},
	{64394, 64395, 1688, 1688},
	{1689, 1689, 1689, 1689},
	{1690, 1690, 1690, 1690},
	{1691, 1691, 1691, 1691},
	{1692, 1692, 1692, 1692},
	{1693, 1693, 1693, 1693},
	{1694, 1694, 1694, 1694},
	{1695, 1695, 1695, 1695},
	{1696, 1696, 1696, 1696},
	{1697, 1697, 1697, 1697},
	{1698, 1698, 1698, 1698},
	{1699, 1699, 1699, 1699},
	{64362, 64363, 64364, 64365},
	{1701, 1701, 1701, 1701},
	{64366, 64367, 64368, 64369},
	{1703, 1703, 1703, 1703},
	{1704, 1704, 1704, 1704},
	{64398, 64399, 64400, 64401},
	{1706, 1706, 1706, 1706},
	{1707, 1707, 1707, 1707},
	{1708, 1708, 1708, 1708},
	{64467, 64468, 64469, 64470},
	{1710, 1710, 1710, 1710},
	{64402, 64403, 64404, 64405},
	{1712, 1712, 1712, 1712},
	{64410, 64411, 64412, 64413},
	{1714, 1714, 1714, 1714},
	{64406, 64407, 64408, 64409},
	{1716, 1716, 1716, 1716},
	{1717, 1717, 1717, 1717},
	{1718, 1718, 1718, 1718},
	{1719, 1719, 1719, 1719},
	{1720, 1720, 1720, 1720},
	{1721, 1721, 1721, 1721},
	{64414, 64415, 1722, 1722},
	{64416, 64417, 64418, 64419},
	{1724, 1724, 1724, 1724},
	{1725, 1725, 1725, 1725},
	{64426, 64427, 64428, 64429},
	{1727, 1727, 1727, 1727},
	{64420, 64421, 1728, 1728},
	{64422, 64423, 64424, 64425},
	{1730, 1730, 1730, 1730},
	{1731, 1731, 1731, 1731},
	{1732, 1732, 1732, 1732},
	{64480, 64481, 1733, 1733},
	{64473, 64474, 1734, 1734},
	{64471, 64472, 1735, 1735},
	{64475, 64476, 1736, 1736},
	{64482, 64483, 1737, 1737},
	{1738, 1738, 1738, 1738},
	{64478, 64479, 1739, 1739},
	{64508, 64509, 64510, 64511},
	{1741, 1741, 1741, 1741},
	{1742, 1742, 1742, 1742},
	{1743, 1743, 1743, 1743},
	{64484, 64485, 64486, 64487},
	{1745, 1745, 1745, 1745},
	{64430, 64431, 1746, 1746},
	{64432, 64433, 1747, 1747},
}

// ArabicLigatures exposes lam-alef ligatures
var ArabicLigatures = [...]struct {
	First     rune
	Ligatures [4][2]rune // {second, ligature}
}{
	{0xfedf, [4][2]rune{
		{0xfe82, 0xfef5},
		{0xfe84, 0xfef7},
		{0xfe88, 0xfef9},
		{0xfe8e, 0xfefb},
	}},
	{0xfee0, [4][2]rune{
		{0xfe82, 0xfef6},
		{0xfe84, 0xfef8},
		{0xfe88, 0xfefa},
		{0xfe8e, 0xfefc},
	}},
}

// HasArabicJoining return 'true' if the given script has arabic joining.
func HasArabicJoining(script language.Script) bool {
	switch script {
	case language.Adlam, language.Arabic, language.Chorasmian, language.Hanifi_Rohingya, language.Mandaic, language.Manichaean, language.Mongolian, language.Nko, language.Phags_Pa, language.Psalter_Pahlavi, language.Sogdian, language.Syriac:
		return true
	default:
		return false
	}
}
