package harfbuzz

import "github.com/benoitkugler/textlayout/fonts/truetype"

// ported from harfbuzz/src/hb-aat-layout.h  Copyright © 2018 Ebrahim Byagowi, Behdad Esfahbod

// The possible feature types defined for AAT shaping,
// from https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html
type hb_aat_layout_feature_type_t uint16

const (
	// Initial, unset feature type
	HB_AAT_LAYOUT_FEATURE_TYPE_INVALID = 0xFFFF
	// [All Typographic Features](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type0)
	HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC = 0
	// [Ligatures](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type1)
	HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES = 1
	// [Cursive Connection](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type2)
	HB_AAT_LAYOUT_FEATURE_TYPE_CURISVE_CONNECTION = 2
	// [Letter Case](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type3)
	HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE = 3
	// [Vertical Substitution](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type4)
	HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION = 4
	// [Linguistic Rearrangement](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type5)
	HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT = 5
	// [Number Spacing](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type6)
	HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING = 6
	// [Smart Swash](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type8)
	HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE = 8
	// [Diacritics](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type9)
	HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE = 9
	// [Vertical Position](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type10)
	HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION = 10
	// [Fractions](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type11)
	HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS = 11
	// [Overlapping Characters](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type13)
	HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE = 13
	// [Typographic Extras](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type14)
	HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS = 14
	// [Mathematical Extras](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type15)
	HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS = 15
	// [Ornament Sets](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type16)
	HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE = 16
	// [Character Alternatives](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type17)
	HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES = 17
	// [Design Complexity](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type18)
	HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE = 18
	// [Style Options](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type19)
	HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS = 19
	// [Character Shape](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type20)
	HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE = 20
	// [Number Case](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type21)
	HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE = 21
	// [Text Spacing](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type22)
	HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING = 22
	// [Transliteration](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type23)
	HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION = 23
	// [Annotation](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type24)
	HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE = 24
	// [Kana Spacing](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type25)
	HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE = 25
	// [Ideographic Spacing](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type26)
	HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE = 26
	// [Unicode Decomposition](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type27)
	HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE = 27
	// [Ruby Kana](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type28)
	HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA = 28
	// [CJK Symbol Alternatives](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type29)
	HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE = 29
	// [Ideographic Alternatives](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type30)
	HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE = 30
	// [CJK Vertical Roman Placement](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type31)
	HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE = 31
	// [Italic CJK Roman](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type32)
	HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN = 32
	// [Case Sensitive Layout](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type33)
	HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT = 33
	// [Alternate Kana](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type34)
	HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA = 34
	// [Stylistic Alternatives](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type35)
	HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES = 35
	// [Contextual Alternatives](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type36)
	HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES = 36
	// [Lower Case](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type37)
	HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE = 37
	// [Upper Case](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type38)
	HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE = 38
	// [Language Tag](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type39)
	HB_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE = 39
	// [CJK Roman Spacing](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type103)
	HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE = 103
)

// The selectors defined for specifying AAT feature settings.
type hb_aat_layout_feature_selector_t uint16

const (
	// Initial, unset feature selector
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INVALID = 0xFFFF

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_OFF = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_ON = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_OFF = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_ON = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_OFF = 9
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_ON = 10
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_OFF = 11
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_ON = 12
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_OFF = 13
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_ON = 14
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_OFF = 15
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_ON = 16
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_OFF = 17
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON = 18
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF = 19
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON = 20
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF = 21

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_UNCONNECTED = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PARTIALLY_CONNECTED = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CURSIVE = 2

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE */
	// Deprecated
	HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_AND_LOWER_CASE = 0 /* deprecated */
	// Deprecated
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_CAPS = 1 /* deprecated */
	// Deprecated
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_LOWER_CASE = 2 /* deprecated */
	// Deprecated
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SMALL_CAPS = 3 /* deprecated */
	// Deprecated
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS = 4 /* deprecated */
	// Deprecated
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS_AND_SMALL_CAPS = 5 /* deprecated */

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_OFF = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_NUMBERS = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_NUMBERS = 3

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_OFF = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_ON = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_OFF = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_ON = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_OFF = 9

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SHOW_DIACRITICS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HIDE_DIACRITICS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DECOMPOSE_DIACRITICS = 2

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS = 4

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS = 2

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_OFF = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_ON = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_OFF = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_ON = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_OFF = 9
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_ON = 10
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_OFF = 11

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_OFF = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_ON = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_OFF = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_ON = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_OFF = 9
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON = 10
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF = 11

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ORNAMENTS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DINGBATS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PI_CHARACTERS = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_FLEURONS = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DECORATIVE_BORDERS = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INTERNATIONAL_SYMBOLS = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_MATH_SYMBOLS = 6

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ALTERNATES = 0

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL1 = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL2 = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL3 = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL4 = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL5 = 4

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DISPLAY_TEXT = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ENGRAVED_TEXT = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ILLUMINATED_CAPS = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TALL_CAPS = 5

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_ONE = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_TWO = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_THREE = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FOUR = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FIVE = 9
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS = 10
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS = 11
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS = 12
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS = 13
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS = 14

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT = 6

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HIRAGANA_TO_KATAKANA = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_KATAKANA_TO_HIRAGANA = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_KANA_TO_ROMANIZATION = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_HIRAGANA = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_KATAKANA = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_ONE = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_TWO = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_THREE = 9

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ANNOTATION = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_BOX_ANNOTATION = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ROUNDED_BOX_ANNOTATION = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CIRCLE_ANNOTATION = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_CIRCLE_ANNOTATION = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PARENTHESIS_ANNOTATION = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIOD_ANNOTATION = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMAN_NUMERAL_ANNOTATION = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAMOND_ANNOTATION = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_BOX_ANNOTATION = 9
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_ROUNDED_BOX_ANNOTATION = 10

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_KANA = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_KANA = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_IDEOGRAPHS = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_IDEOGRAPHS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_IDEOGRAPHS = 2

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_OFF = 5

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA */
	// Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF instead
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_RUBY_KANA = 0 /* deprecated - use RUBY_KANA_OFF instead */
	// Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON instead
	HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA = 1 /* deprecated - use RUBY_KANA_ON instead */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA
	HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA
	HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF = 3

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_SYMBOL_ALTERNATIVES = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_ONE = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_TWO = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_THREE = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FOUR = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FIVE = 5

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_IDEOGRAPHIC_ALTERNATIVES = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_ONE = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_TWO = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_THREE = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FOUR = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FIVE = 5

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_CENTERED = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_HBASELINE = 1

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN */
	// Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF instead
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_ITALIC_ROMAN = 0 /* deprecated - use CJK_ITALIC_ROMAN_OFF instead */
	// Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON instead
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN = 1 /* deprecated - use CJK_ITALIC_ROMAN_ON instead */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF = 3

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF = 3

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
	HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF = 3

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLISTIC_ALTERNATES = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF = 5
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON = 6
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF = 7
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON = 8
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF = 9
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON = 10
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF = 11
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON = 12
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF = 13
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON = 14
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF = 15
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON = 16
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF = 17
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON = 18
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF = 19
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON = 20
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF = 21
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON = 22
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF = 23
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON = 24
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF = 25
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON = 26
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF = 27
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON = 28
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF = 29
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON = 30
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF = 31
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON = 32
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF = 33
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON = 34
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF = 35
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON = 36
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF = 37
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON = 38
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF = 39
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON = 40
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF = 41

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF = 3
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON = 4
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
	HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF = 5

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS = 2

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS = 2

	/* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE */
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_CJK_ROMAN = 0
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_CJK_ROMAN = 1
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_CJK_ROMAN = 2
	// for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
	HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_CJK_ROMAN = 3
)

/* Mapping from OpenType feature tags to AAT feature names and selectors.
 *
 * Table data courtesy of Apple.  Converted from mnemonics to integers
 * when moving to this file. */
var feature_mappings = [...]hb_aat_feature_mapping_t{
	{newTag('a', 'f', 'r', 'c'), HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS, HB_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS},
	{newTag('c', '2', 'p', 'c'), HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE, HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS, HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE},
	{newTag('c', '2', 's', 'c'), HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE, HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS, HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE},
	{newTag('c', 'a', 'l', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF},
	{newTag('c', 'a', 's', 'e'), HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT, HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF},
	{newTag('c', 'l', 'i', 'g'), HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES, HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF},
	{newTag('c', 'p', 's', 'p'), HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT, HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF},
	{newTag('c', 's', 'w', 'h'), HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF},
	{newTag('d', 'l', 'i', 'g'), HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES, HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF},
	{newTag('e', 'x', 'p', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS, 16},
	{newTag('f', 'r', 'a', 'c'), HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS, HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS},
	{newTag('f', 'w', 'i', 'd'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT, 7},
	{newTag('h', 'a', 'l', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT, 7},
	{newTag('h', 'i', 's', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES, HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF},
	{newTag('h', 'k', 'n', 'a'), HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF},
	{newTag('h', 'l', 'i', 'g'), HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES, HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF},
	{newTag('h', 'n', 'g', 'l'), HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION, HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL, HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION},
	{newTag('h', 'o', 'j', 'o'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS, 16},
	{newTag('h', 'w', 'i', 'd'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT, 7},
	{newTag('i', 't', 'a', 'l'), HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN, HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF},
	{newTag('j', 'p', '0', '4'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS, 16},
	{newTag('j', 'p', '7', '8'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS, 16},
	{newTag('j', 'p', '8', '3'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS, 16},
	{newTag('j', 'p', '9', '0'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS, 16},
	{newTag('l', 'i', 'g', 'a'), HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES, HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF},
	{newTag('l', 'n', 'u', 'm'), HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE, HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS, 2},
	{newTag('m', 'g', 'r', 'k'), HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS, HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF},
	{newTag('n', 'l', 'c', 'k'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS, 16},
	{newTag('o', 'n', 'u', 'm'), HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE, HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS, 2},
	{newTag('o', 'r', 'd', 'n'), HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION, HB_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION},
	{newTag('p', 'a', 'l', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT, 7},
	{newTag('p', 'c', 'a', 'p'), HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE, HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS, HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE},
	{newTag('p', 'k', 'n', 'a'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT, 7},
	{newTag('p', 'n', 'u', 'm'), HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS, 4},
	{newTag('p', 'w', 'i', 'd'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT, 7},
	{newTag('q', 'w', 'i', 'd'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT, 7},
	{newTag('r', 'u', 'b', 'y'), HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA, HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF},
	{newTag('s', 'i', 'n', 'f'), HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION, HB_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION},
	{newTag('s', 'm', 'c', 'p'), HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE, HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS, HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE},
	{newTag('s', 'm', 'p', 'l'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS, 16},
	{newTag('s', 's', '0', '1'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF},
	{newTag('s', 's', '0', '2'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF},
	{newTag('s', 's', '0', '3'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF},
	{newTag('s', 's', '0', '4'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF},
	{newTag('s', 's', '0', '5'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF},
	{newTag('s', 's', '0', '6'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF},
	{newTag('s', 's', '0', '7'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF},
	{newTag('s', 's', '0', '8'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF},
	{newTag('s', 's', '0', '9'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF},
	{newTag('s', 's', '1', '0'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF},
	{newTag('s', 's', '1', '1'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF},
	{newTag('s', 's', '1', '2'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF},
	{newTag('s', 's', '1', '3'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF},
	{newTag('s', 's', '1', '4'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF},
	{newTag('s', 's', '1', '5'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF},
	{newTag('s', 's', '1', '6'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF},
	{newTag('s', 's', '1', '7'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF},
	{newTag('s', 's', '1', '8'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF},
	{newTag('s', 's', '1', '9'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF},
	{newTag('s', 's', '2', '0'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF},
	{newTag('s', 'u', 'b', 's'), HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION, HB_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION},
	{newTag('s', 'u', 'p', 's'), HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION, HB_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION},
	{newTag('s', 'w', 's', 'h'), HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES, HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF},
	{newTag('t', 'i', 't', 'l'), HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS, HB_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS, HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS},
	{newTag('t', 'n', 'a', 'm'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS, 16},
	{newTag('t', 'n', 'u', 'm'), HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS, 4},
	{newTag('t', 'r', 'a', 'd'), HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE, HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS, 16},
	{newTag('t', 'w', 'i', 'd'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT, 7},
	{newTag('u', 'n', 'i', 'c'), HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE, 14, 15},
	{newTag('v', 'a', 'l', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT, 7},
	{newTag('v', 'e', 'r', 't'), HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION, HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF},
	{newTag('v', 'h', 'a', 'l'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT, 7},
	{newTag('v', 'k', 'n', 'a'), HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF},
	{newTag('v', 'p', 'a', 'l'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING, HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT, 7},
	{newTag('v', 'r', 't', '2'), HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION, HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF},
	{newTag('z', 'e', 'r', 'o'), HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS, HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON, HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF},
}

// hb_aat_layout_feature_selector_info_t represents a setting for an `hb_aat_layout_feature_type_t`.
type hb_aat_layout_feature_selector_info_t struct {
	name_id truetype.NameID                  // selector's name identifier
	enable  hb_aat_layout_feature_selector_t // value to turn the selector on
	disable hb_aat_layout_feature_selector_t // value to turn the selector off
}

// Used when getting or setting AAT feature selectors. Indicates that
// there is no selector index corresponding to the selector of interest.
const HB_AAT_LAYOUT_NO_SELECTOR_INDEX = 0xFFFF

/* Note: This context is used for kerning, even without AAT, hence the condition. */

//  AAT::hb_aat_apply_context_t::hb_aat_apply_context_t (const hb_ot_shape_plan_t *plan_,
// 							  hb_font_t *font_,
// 							  hb_buffer_t *buffer_,
// 							  hb_blob_t *blob) :
// 								plan (plan_),
// 								font (font_),
// 								face (font.face),
// 								buffer (buffer_),
// 								sanitizer (),
// 								ankr_table (&Null (AAT::ankr)),
// 								lookup_index (0)
//  {
//    sanitizer.init (blob);
//    sanitizer.set_num_glyphs (face.get_num_glyphs ());
//    sanitizer.start_processing ();
//    sanitizer.set_max_ops (HB_SANITIZE_MAX_OPS_MAX);
//  }

//  AAT::hb_aat_apply_context_t::~hb_aat_apply_context_t ()
//  { sanitizer.end_processing (); }

//  void
//  AAT::hb_aat_apply_context_t::set_ankr_table (const AAT::ankr *ankr_table_)
//  { ankr_table = ankr_table_; }

/**
 * SECTION:hb-aat-layout
 * @title: hb-aat-layout
 * @short_description: Apple Advanced Typography Layout
 * @include: hb-aat.h
 *
 * Functions for querying AAT Layout features in the font face.
 *
 * HarfBuzz supports all of the AAT tables used to implement shaping. Other
 * AAT tables and their associated features are not supported.
 **/

type hb_aat_feature_mapping_t struct {
	otFeatureTag      hb_tag_t
	aatFeatureType    hb_aat_layout_feature_type_t
	selectorToEnable  hb_aat_layout_feature_selector_t
	selectorToDisable hb_aat_layout_feature_selector_t

	//   int cmp (hb_tag_t key) const
	//   { return key < otFeatureTag ? -1 : key > otFeatureTag ? 1 : 0; }
}

/**
 * hb_aat_layout_find_feature_mapping:
 * @tag: The requested #hb_tag_t feature tag
 *
 * Fetches the AAT feature-and-selector combination that corresponds
 * to a given OpenType feature tag.
 *
 * Return value: the AAT features and selectors corresponding to the
 * OpenType feature tag queried
 *
 **/
func hb_aat_layout_find_feature_mapping(tag hb_tag_t) *hb_aat_feature_mapping_t {
	low, high := 0, len(feature_mappings)
	for low < high {
		mid := low + (high-low)/2 // avoid overflow when computing mid
		p := feature_mappings[mid].otFeatureTag
		if tag < p {
			high = mid
		} else if tag > p {
			low = mid + 1
		} else {
			return &feature_mappings[mid]
		}
	}
	return nil
}

func (mapper *hb_aat_map_builder_t) hb_aat_layout_compile_map(map_ *hb_aat_map_t) {
	morx := mapper.face.table.morx
	if morx.has_data() {
		morx.compile_flags(mapper, map_)
		return
	}

	mort := mapper.face.table.mort
	if mort.has_data() {
		mort.compile_flags(mapper, map_)
		return
	}
}

/**
 * hb_aat_layout_has_substitution:
 * @face: #hb_face_t to work upon
 *
 * Tests whether the specified face includes any substitutions in the
 * `morx` or `mort` tables.
 *
 * <note>Note: does not examine the `GSUB` table.</note>
 *
 * Return value: %true if data found, %false otherwise
 *
 * Since: 2.3.0
 */
func hb_aat_layout_has_substitution(hb_face_t *face) bool {
	return face.table.morx.has_data() || face.table.mort.has_data()
}

//  void
//  hb_aat_layout_substitute (const hb_ot_shape_plan_t *plan,
// 			   hb_font_t *font,
// 			   hb_buffer_t *buffer)
//  {
//    hb_blob_t *morx_blob = font.face.table.morx.get_blob ();
//    const AAT::morx& morx = *morx_blob.as<AAT::morx> ();
//    if (morx.has_data ())
//    {
// 	 AAT::hb_aat_apply_context_t c (plan, font, buffer, morx_blob);
// 	 morx.apply (&c);
// 	 return;
//    }

//    hb_blob_t *mort_blob = font.face.table.mort.get_blob ();
//    const AAT::mort& mort = *mort_blob.as<AAT::mort> ();
//    if (mort.has_data ())
//    {
// 	 AAT::hb_aat_apply_context_t c (plan, font, buffer, mort_blob);
// 	 mort.apply (&c);
// 	 return;
//    }
//  }

//  void
//  hb_aat_layout_zero_width_deleted_glyphs (hb_buffer_t *buffer)
//  {
//    unsigned int count = buffer.len;
//    hb_glyph_info_t *info = buffer.info;
//    hb_glyph_position_t *pos = buffer.pos;
//    for (unsigned int i = 0; i < count; i++)
// 	 if (unlikely (info[i].codepoint == AAT::DELETED_GLYPH))
// 	   pos[i].x_advance = pos[i].y_advance = pos[i].x_offset = pos[i].y_offset = 0;
//  }

//  static bool
//  is_deleted_glyph (const hb_glyph_info_t *info)
//  {
//    return info.codepoint == AAT::DELETED_GLYPH;
//  }

//  void
//  hb_aat_layout_remove_deleted_glyphs (hb_buffer_t *buffer)
//  {
//    hb_ot_layout_delete_glyphs_inplace (buffer, is_deleted_glyph);
//  }

//  void
//  hb_aat_layout_position (const hb_ot_shape_plan_t *plan,
// 			 hb_font_t *font,
// 			 hb_buffer_t *buffer)
//  {
//    hb_blob_t *kerx_blob = font.face.table.kerx.get_blob ();
//    const AAT::kerx& kerx = *kerx_blob.as<AAT::kerx> ();

//    AAT::hb_aat_apply_context_t c (plan, font, buffer, kerx_blob);
//    c.set_ankr_table (font.face.table.ankr.get ());
//    kerx.apply (&c);
//  }

//  /**
//   * hb_aat_layout_has_tracking:
//   * @face:: #hb_face_t to work upon
//   *
//   * Tests whether the specified face includes any tracking information
//   * in the `trak` table.
//   *
//   * Return value: %true if data found, %false otherwise
//   *
//   * Since: 2.3.0
//   */
//  hb_bool_t
//  hb_aat_layout_has_tracking (hb_face_t *face)
//  {
//    return face.table.trak.has_data ();
//  }

//  void
//  hb_aat_layout_track (const hb_ot_shape_plan_t *plan,
// 			  hb_font_t *font,
// 			  hb_buffer_t *buffer)
//  {
//    const AAT::trak& trak = *font.face.table.trak;

//    AAT::hb_aat_apply_context_t c (plan, font, buffer);
//    trak.apply (&c);
//  }

/**
 * hb_aat_layout_get_feature_types:
 * @face: #hb_face_t to work upon
 * @start_offset: offset of the first feature type to retrieve
 * @feature_count: (inout) (optional): Input = the maximum number of feature types to return;
 *                 Output = the actual number of feature types returned (may be zero)
 * @features: (out caller-allocates) (array length=feature_count): Array of feature types found
 *
 * Fetches a list of the AAT feature types included in the specified face.
 *
 * Return value: Number of all available feature types.
 *
 * Since: 2.2.0
 */
//  unsigned int
//  hb_aat_layout_get_feature_types (hb_face_t                    *face,
// 				  unsigned int                  start_offset,
// 				  unsigned int                 *feature_count, /* IN/OUT.  May be NULL. */
// 				  hb_aat_layout_feature_type_t *features       /* OUT.     May be NULL. */)
//  {
//    return face.table.feat.get_feature_types (start_offset, feature_count, features);
//  }

/**
 * hb_aat_layout_feature_type_get_name_id:
 * @face: #hb_face_t to work upon
 * @feature_type: The #hb_aat_layout_feature_type_t of the requested feature type
 *
 * Fetches the name identifier of the specified feature type in the face's `name` table.
 *
 * Return value: Name identifier of the requested feature type
 *
 * Since: 2.2.0
 */
//  hb_ot_name_id_t
//  hb_aat_layout_feature_type_get_name_id (hb_face_t                    *face,
// 					 hb_aat_layout_feature_type_t  feature_type)
//  {
//    return face.table.feat.get_feature_name_id (feature_type);
//  }

/**
 * hb_aat_layout_feature_type_get_selector_infos:
 * @face: #hb_face_t to work upon
 * @feature_type: The #hb_aat_layout_feature_type_t of the requested feature type
 * @start_offset: offset of the first feature type to retrieve
 * @selector_count: (inout) (optional): Input = the maximum number of selectors to return;
 *                  Output = the actual number of selectors returned (may be zero)
 * @selectors: (out caller-allocates) (array length=selector_count) (optional):
 *             A buffer pointer. The selectors available for the feature type queries.
 * @default_index: (out) (optional): The index of the feature's default selector, if any
 *
 * Fetches a list of the selectors available for the specified feature in the given face.
 *
 * If upon return, @default_index is set to #HB_AAT_LAYOUT_NO_SELECTOR_INDEX, then
 * the feature type is non-exclusive.  Otherwise, @default_index is the index of
 * the selector that is selected by default.
 *
 * Return value: Number of all available feature selectors
 *
 * Since: 2.2.0
 */
//  unsigned int
//  hb_aat_layout_feature_type_get_selector_infos (hb_face_t                             *face,
// 							hb_aat_layout_feature_type_t           feature_type,
// 							unsigned int                           start_offset,
// 							unsigned int                          *selector_count, /* IN/OUT.  May be NULL. */
// 							hb_aat_layout_feature_selector_info_t *selectors,      /* OUT.     May be NULL. */
// 							unsigned int                          *default_index   /* OUT.     May be NULL. */)
//  {
//    return face.table.feat.get_selector_infos (feature_type, start_offset, selector_count, selectors, default_index);
//  }
