package harfbuzz

// Code generated by langs/gen.go. DO NOT EDIT

var ot_languages =[...]LangTag{
  {"aa",	newTag('A','F','R',' ')},	/* Afar */
  {"aae",	newTag('S','Q','I',' ')},	/* Arbëreshë Albanian -> Albanian */
  {"aao",	newTag('A','R','A',' ')},	/* Algerian Saharan Arabic -> Arabic */
  {"aat",	newTag('S','Q','I',' ')},	/* Arvanitika Albanian -> Albanian */
  {"ab",	newTag('A','B','K',' ')},	/* Abkhazian */
  {"aba",	0	},	/* Abé != Abaza */
  {"abh",	newTag('A','R','A',' ')},	/* Tajiki Arabic -> Arabic */
  {"abq",	newTag('A','B','A',' ')},	/* Abaza */
  {"abs",	newTag('C','P','P',' ')},	/* Ambonese Malay -> Creoles */
  {"abv",	newTag('A','R','A',' ')},	/* Baharna Arabic -> Arabic */
  {"acf",	newTag('F','A','N',' ')},	/* Saint Lucian Creole French -> French Antillean */
  {"acf",	newTag('C','P','P',' ')},	/* Saint Lucian Creole French -> Creoles */
/*{"ach",	newTag('A','C','H',' ')},*/	/* Acoli -> Acholi */
  {"acm",	newTag('A','R','A',' ')},	/* Mesopotamian Arabic -> Arabic */
  {"acq",	newTag('A','R','A',' ')},	/* Ta'izzi-Adeni Arabic -> Arabic */
  {"acr",	newTag('A','C','R',' ')},	/* Achi */
  {"acr",	newTag('M','Y','N',' ')},	/* Achi -> Mayan */
  {"acw",	newTag('A','R','A',' ')},	/* Hijazi Arabic -> Arabic */
  {"acx",	newTag('A','R','A',' ')},	/* Omani Arabic -> Arabic */
  {"acy",	newTag('A','R','A',' ')},	/* Cypriot Arabic -> Arabic */
  {"ada",	newTag('D','N','G',' ')},	/* Adangme -> Dangme */
  {"adf",	newTag('A','R','A',' ')},	/* Dhofari Arabic -> Arabic */
  {"adp",	newTag('D','Z','N',' ')},	/* Adap (retired code) (retired code) -> Dzongkha */
/*{"ady",	newTag('A','D','Y',' ')},*/	/* Adyghe */
  {"aeb",	newTag('A','R','A',' ')},	/* Tunisian Arabic -> Arabic */
  {"aec",	newTag('A','R','A',' ')},	/* Saidi Arabic -> Arabic */
  {"af",	newTag('A','F','K',' ')},	/* Afrikaans */
  {"afb",	newTag('A','R','A',' ')},	/* Gulf Arabic -> Arabic */
  {"afk",	0	},	/* Nanubae != Afrikaans */
  {"afs",	newTag('C','P','P',' ')},	/* Afro-Seminole Creole -> Creoles */
  {"agu",	newTag('M','Y','N',' ')},	/* Aguacateco -> Mayan */
  {"agw",	0	},	/* Kahua != Agaw */
  {"ahg",	newTag('A','G','W',' ')},	/* Qimant -> Agaw */
  {"aht",	newTag('A','T','H',' ')},	/* Ahtena -> Athapaskan */
  {"aig",	newTag('C','P','P',' ')},	/* Antigua and Barbuda Creole English -> Creoles */
  {"aii",	newTag('S','W','A',' ')},	/* Assyrian Neo-Aramaic -> Swadaya Aramaic */
  {"aii",	newTag('S','Y','R',' ')},	/* Assyrian Neo-Aramaic -> Syriac */
/*{"aio",	newTag('A','I','O',' ')},*/	/* Aiton */
  {"aiw",	newTag('A','R','I',' ')},	/* Aari */
  {"ajp",	newTag('A','R','A',' ')},	/* South Levantine Arabic -> Arabic */
  {"ak",	newTag('A','K','A',' ')},	/* Akan [macrolanguage] */
  {"akb",	newTag('A','K','B',' ')},	/* Batak Angkola */
  {"akb",	newTag('B','T','K',' ')},	/* Batak Angkola -> Batak */
  {"aln",	newTag('S','Q','I',' ')},	/* Gheg Albanian -> Albanian */
  {"als",	newTag('S','Q','I',' ')},	/* Tosk Albanian -> Albanian */
/*{"alt",	newTag('A','L','T',' ')},*/	/* Southern Altai -> Altai */
  {"am",	newTag('A','M','H',' ')},	/* Amharic */
  {"amf",	newTag('H','B','N',' ')},	/* Hamer-Banna -> Hammer-Banna */
  {"amw",	newTag('S','Y','R',' ')},	/* Western Neo-Aramaic -> Syriac */
  {"an",	newTag('A','R','G',' ')},	/* Aragonese */
/*{"ang",	newTag('A','N','G',' ')},*/	/* Old English (ca. 450-1100) -> Anglo-Saxon */
  {"aoa",	newTag('C','P','P',' ')},	/* Angolar -> Creoles */
  {"apa",	newTag('A','T','H',' ')},	/* Apache [family] -> Athapaskan */
  {"apc",	newTag('A','R','A',' ')},	/* North Levantine Arabic -> Arabic */
  {"apd",	newTag('A','R','A',' ')},	/* Sudanese Arabic -> Arabic */
  {"apj",	newTag('A','T','H',' ')},	/* Jicarilla Apache -> Athapaskan */
  {"apk",	newTag('A','T','H',' ')},	/* Kiowa Apache -> Athapaskan */
  {"apl",	newTag('A','T','H',' ')},	/* Lipan Apache -> Athapaskan */
  {"apm",	newTag('A','T','H',' ')},	/* Mescalero-Chiricahua Apache -> Athapaskan */
  {"apw",	newTag('A','T','H',' ')},	/* Western Apache -> Athapaskan */
  {"ar",	newTag('A','R','A',' ')},	/* Arabic [macrolanguage] */
  {"arb",	newTag('A','R','A',' ')},	/* Standard Arabic -> Arabic */
  {"ari",	0	},	/* Arikara != Aari */
  {"ark",	0	},	/* Arikapú != Rakhine */
  {"arn",	newTag('M','A','P',' ')},	/* Mapudungun */
  {"arq",	newTag('A','R','A',' ')},	/* Algerian Arabic -> Arabic */
  {"ars",	newTag('A','R','A',' ')},	/* Najdi Arabic -> Arabic */
  {"ary",	newTag('M','O','R',' ')},	/* Moroccan Arabic ->  */
  {"ary",	newTag('A','R','A',' ')},	/* Moroccan Arabic -> Arabic */
  {"arz",	newTag('A','R','A',' ')},	/* Egyptian Arabic -> Arabic */
  {"as",	newTag('A','S','M',' ')},	/* Assamese */
/*{"ast",	newTag('A','S','T',' ')},*/	/* Asturian */
/*{"ath",	newTag('A','T','H',' ')},*/	/* Athapascan [family] -> Athapaskan */
  {"atj",	newTag('R','C','R',' ')},	/* Atikamekw -> R-Cree */
  {"atv",	newTag('A','L','T',' ')},	/* Northern Altai -> Altai */
  {"auj",	newTag('B','B','R',' ')},	/* Awjilah -> Berber */
  {"auz",	newTag('A','R','A',' ')},	/* Uzbeki Arabic -> Arabic */
  {"av",	newTag('A','V','R',' ')},	/* Avaric -> Avar */
  {"avl",	newTag('A','R','A',' ')},	/* Eastern Egyptian Bedawi Arabic -> Arabic */
/*{"awa",	newTag('A','W','A',' ')},*/	/* Awadhi */
  {"ay",	newTag('A','Y','M',' ')},	/* Aymara [macrolanguage] */
  {"ayc",	newTag('A','Y','M',' ')},	/* Southern Aymara -> Aymara */
  {"ayh",	newTag('A','R','A',' ')},	/* Hadrami Arabic -> Arabic */
  {"ayl",	newTag('A','R','A',' ')},	/* Libyan Arabic -> Arabic */
  {"ayn",	newTag('A','R','A',' ')},	/* Sanaani Arabic -> Arabic */
  {"ayp",	newTag('A','R','A',' ')},	/* North Mesopotamian Arabic -> Arabic */
  {"ayr",	newTag('A','Y','M',' ')},	/* Central Aymara -> Aymara */
  {"az",	newTag('A','Z','E',' ')},	/* Azerbaijani [macrolanguage] */
  {"azb",	newTag('A','Z','B',' ')},	/* South Azerbaijani -> Torki */
  {"azb",	newTag('A','Z','E',' ')},	/* South Azerbaijani -> Azerbaijani */
  {"azd",	newTag('N','A','H',' ')},	/* Eastern Durango Nahuatl -> Nahuatl */
  {"azj",	newTag('A','Z','E',' ')},	/* North Azerbaijani -> Azerbaijani */
  {"azn",	newTag('N','A','H',' ')},	/* Western Durango Nahuatl -> Nahuatl */
  {"azz",	newTag('N','A','H',' ')},	/* Highland Puebla Nahuatl -> Nahuatl */
  {"ba",	newTag('B','S','H',' ')},	/* Bashkir */
  {"bad",	newTag('B','A','D','0')},	/* Banda [family] */
  {"bag",	0	},	/* Tuki != Baghelkhandi */
  {"bah",	newTag('C','P','P',' ')},	/* Bahamas Creole English -> Creoles */
  {"bai",	newTag('B','M','L',' ')},	/* Bamileke [family] */
  {"bal",	newTag('B','L','I',' ')},	/* Baluchi [macrolanguage] */
/*{"ban",	newTag('B','A','N',' ')},*/	/* Balinese */
/*{"bar",	newTag('B','A','R',' ')},*/	/* Bavarian */
  {"bau",	0	},	/* Bada (Nigeria) != Baulé */
  {"bbc",	newTag('B','B','C',' ')},	/* Batak Toba */
  {"bbc",	newTag('B','T','K',' ')},	/* Batak Toba -> Batak */
  {"bbj",	newTag('B','M','L',' ')},	/* Ghomálá' -> Bamileke */
  {"bbp",	newTag('B','A','D','0')},	/* West Central Banda -> Banda */
  {"bbr",	0	},	/* Girawa != Berber */
  {"bbz",	newTag('A','R','A',' ')},	/* Babalia Creole Arabic (retired code) (retired code) -> Arabic */
  {"bcc",	newTag('B','L','I',' ')},	/* Southern Balochi -> Baluchi */
  {"bch",	0	},	/* Bariai != Bench */
  {"bci",	newTag('B','A','U',' ')},	/* Baoulé -> Baulé */
  {"bcl",	newTag('B','I','K',' ')},	/* Central Bikol -> Bikol */
  {"bcq",	newTag('B','C','H',' ')},	/* Bench */
  {"bcr",	newTag('A','T','H',' ')},	/* Babine -> Athapaskan */
/*{"bdy",	newTag('B','D','Y',' ')},*/	/* Bandjalang */
  {"be",	newTag('B','E','L',' ')},	/* Belarusian -> Belarussian */
  {"bea",	newTag('A','T','H',' ')},	/* Beaver -> Athapaskan */
  {"beb",	newTag('B','T','I',' ')},	/* Bebele -> Beti */
/*{"bem",	newTag('B','E','M',' ')},*/	/* Bemba (Zambia) */
  {"ber",	newTag('B','B','R',' ')},	/* Berber [family] */
  {"bew",	newTag('C','P','P',' ')},	/* Betawi -> Creoles */
  {"bfl",	newTag('B','A','D','0')},	/* Banda-Ndélé -> Banda */
  {"bfq",	newTag('B','A','D',' ')},	/* Badaga */
  {"bft",	newTag('B','L','T',' ')},	/* Balti */
  {"bfu",	newTag('L','A','H',' ')},	/* Gahri -> Lahuli */
  {"bfy",	newTag('B','A','G',' ')},	/* Bagheli -> Baghelkhandi */
  {"bg",	newTag('B','G','R',' ')},	/* Bulgarian */
/*{"bgc",	newTag('B','G','C',' ')},*/	/* Haryanvi */
  {"bgn",	newTag('B','L','I',' ')},	/* Western Balochi -> Baluchi */
  {"bgp",	newTag('B','L','I',' ')},	/* Eastern Balochi -> Baluchi */
  {"bgq",	newTag('B','G','Q',' ')},	/* Bagri */
  {"bgq",	newTag('R','A','J',' ')},	/* Bagri -> Rajasthani */
  {"bgr",	newTag('Q','I','N',' ')},	/* Bawm Chin -> Chin */
  {"bhb",	newTag('B','H','I',' ')},	/* Bhili */
/*{"bhi",	newTag('B','H','I',' ')},*/	/* Bhilali -> Bhili */
  {"bhk",	newTag('B','I','K',' ')},	/* Albay Bicolano (retired code) (retired code) -> Bikol */
/*{"bho",	newTag('B','H','O',' ')},*/	/* Bhojpuri */
  {"bhr",	newTag('M','L','G',' ')},	/* Bara Malagasy -> Malagasy */
  {"bi",	newTag('B','I','S',' ')},	/* Bislama */
  {"bi",	newTag('C','P','P',' ')},	/* Bislama -> Creoles */
/*{"bik",	newTag('B','I','K',' ')},*/	/* Bikol [macrolanguage] */
  {"bil",	0	},	/* Bile != Bilen */
  {"bin",	newTag('E','D','O',' ')},	/* Edo */
  {"biu",	newTag('Q','I','N',' ')},	/* Biete -> Chin */
/*{"bjj",	newTag('B','J','J',' ')},*/	/* Kanauji */
  {"bjn",	newTag('M','L','Y',' ')},	/* Banjar -> Malay */
  {"bjo",	newTag('B','A','D','0')},	/* Mid-Southern Banda -> Banda */
  {"bjq",	newTag('M','L','G',' ')},	/* Southern Betsimisaraka Malagasy (retired code) (retired code) -> Malagasy */
  {"bjs",	newTag('C','P','P',' ')},	/* Bajan -> Creoles */
  {"bjt",	newTag('B','L','N',' ')},	/* Balanta-Ganja -> Balante */
  {"bkf",	0	},	/* Beeke != Blackfoot */
  {"bko",	newTag('B','M','L',' ')},	/* Kwa' -> Bamileke */
  {"bla",	newTag('B','K','F',' ')},	/* Siksika -> Blackfoot */
  {"ble",	newTag('B','L','N',' ')},	/* Balanta-Kentohe -> Balante */
  {"bli",	0	},	/* Bolia != Baluchi */
  {"blk",	newTag('B','L','K',' ')},	/* Pa’o Karen */
  {"blk",	newTag('K','R','N',' ')},	/* Pa'o Karen -> Karen */
  {"bln",	newTag('B','I','K',' ')},	/* Southern Catanduanes Bikol -> Bikol */
  {"blt",	0	},	/* Tai Dam != Balti */
  {"bm",	newTag('B','M','B',' ')},	/* Bambara (Bamanankan) */
  {"bmb",	0	},	/* Bembe != Bambara (Bamanankan) */
  {"bml",	0	},	/* Bomboli != Bamileke */
  {"bmm",	newTag('M','L','G',' ')},	/* Northern Betsimisaraka Malagasy -> Malagasy */
  {"bn",	newTag('B','E','N',' ')},	/* Bengali */
  {"bo",	newTag('T','I','B',' ')},	/* Tibetan */
  {"bpd",	newTag('B','A','D','0')},	/* Banda-Banda -> Banda */
  {"bpl",	newTag('C','P','P',' ')},	/* Broome Pearling Lugger Pidgin -> Creoles */
  {"bpq",	newTag('C','P','P',' ')},	/* Banda Malay -> Creoles */
/*{"bpy",	newTag('B','P','Y',' ')},*/	/* Bishnupriya -> Bishnupriya Manipuri */
  {"bqi",	newTag('L','R','C',' ')},	/* Bakhtiari -> Luri */
  {"bqk",	newTag('B','A','D','0')},	/* Banda-Mbrès -> Banda */
  {"br",	newTag('B','R','E',' ')},	/* Breton */
  {"bra",	newTag('B','R','I',' ')},	/* Braj -> Braj Bhasha */
  {"brc",	newTag('C','P','P',' ')},	/* Berbice Creole Dutch -> Creoles */
/*{"brh",	newTag('B','R','H',' ')},*/	/* Brahui */
  {"bri",	0	},	/* Mokpwe != Braj Bhasha */
  {"brm",	0	},	/* Barambu != Burmese */
/*{"brx",	newTag('B','R','X',' ')},*/	/* Bodo (India) */
  {"bs",	newTag('B','O','S',' ')},	/* Bosnian */
  {"bsh",	0	},	/* Kati != Bashkir */
/*{"bsk",	newTag('B','S','K',' ')},*/	/* Burushaski */
  {"btb",	newTag('B','T','I',' ')},	/* Beti (Cameroon) (retired code) (retired code) */
  {"btd",	newTag('B','T','D',' ')},	/* Batak Dairi (Pakpak) */
  {"btd",	newTag('B','T','K',' ')},	/* Batak Dairi -> Batak */
  {"bti",	0	},	/* Burate != Beti */
  {"btj",	newTag('M','L','Y',' ')},	/* Bacanese Malay -> Malay */
/*{"btk",	newTag('B','T','K',' ')},*/	/* Batak [family] */
  {"btm",	newTag('B','T','M',' ')},	/* Batak Mandailing */
  {"btm",	newTag('B','T','K',' ')},	/* Batak Mandailing -> Batak */
  {"bto",	newTag('B','I','K',' ')},	/* Rinconada Bikol -> Bikol */
  {"bts",	newTag('B','T','S',' ')},	/* Batak Simalungun */
  {"bts",	newTag('B','T','K',' ')},	/* Batak Simalungun -> Batak */
  {"btx",	newTag('B','T','X',' ')},	/* Batak Karo */
  {"btx",	newTag('B','T','K',' ')},	/* Batak Karo -> Batak */
  {"btz",	newTag('B','T','Z',' ')},	/* Batak Alas-Kluet */
  {"btz",	newTag('B','T','K',' ')},	/* Batak Alas-Kluet -> Batak */
/*{"bug",	newTag('B','U','G',' ')},*/	/* Buginese -> Bugis */
  {"bum",	newTag('B','T','I',' ')},	/* Bulu (Cameroon) -> Beti */
  {"bve",	newTag('M','L','Y',' ')},	/* Berau Malay -> Malay */
  {"bvu",	newTag('M','L','Y',' ')},	/* Bukit Malay -> Malay */
  {"bwe",	newTag('K','R','N',' ')},	/* Bwe Karen -> Karen */
  {"bxk",	newTag('L','U','H',' ')},	/* Bukusu -> Luyia */
  {"bxo",	newTag('C','P','P',' ')},	/* Barikanchi -> Creoles */
  {"bxp",	newTag('B','T','I',' ')},	/* Bebil -> Beti */
  {"bxr",	newTag('R','B','U',' ')},	/* Russia Buriat -> Russian Buriat */
  {"byn",	newTag('B','I','L',' ')},	/* Bilin -> Bilen */
  {"byv",	newTag('B','Y','V',' ')},	/* Medumba */
  {"byv",	newTag('B','M','L',' ')},	/* Medumba -> Bamileke */
  {"bzc",	newTag('M','L','G',' ')},	/* Southern Betsimisaraka Malagasy -> Malagasy */
  {"bzj",	newTag('C','P','P',' ')},	/* Belize Kriol English -> Creoles */
  {"bzk",	newTag('C','P','P',' ')},	/* Nicaragua Creole English -> Creoles */
  {"ca",	newTag('C','A','T',' ')},	/* Catalan */
  {"caa",	newTag('M','Y','N',' ')},	/* Chortí -> Mayan */
  {"cac",	newTag('M','Y','N',' ')},	/* Chuj -> Mayan */
  {"caf",	newTag('C','R','R',' ')},	/* Southern Carrier -> Carrier */
  {"caf",	newTag('A','T','H',' ')},	/* Southern Carrier -> Athapaskan */
  {"cak",	newTag('C','A','K',' ')},	/* Kaqchikel */
  {"cak",	newTag('M','Y','N',' ')},	/* Kaqchikel -> Mayan */
  {"cbk",	newTag('C','B','K',' ')},	/* Chavacano -> Zamboanga Chavacano */
  {"cbk",	newTag('C','P','P',' ')},	/* Chavacano -> Creoles */
  {"cbl",	newTag('Q','I','N',' ')},	/* Bualkhaw Chin -> Chin */
  {"ccl",	newTag('C','P','P',' ')},	/* Cutchi-Swahili -> Creoles */
  {"ccm",	newTag('C','P','P',' ')},	/* Malaccan Creole Malay -> Creoles */
  {"cco",	newTag('C','C','H','N')},	/* Comaltepec Chinantec -> Chinantec */
  {"ccq",	newTag('A','R','K',' ')},	/* Chaungtha (retired code) (retired code) -> Rakhine */
  {"cdo",	newTag('Z','H','S',' ')},	/* Min Dong Chinese -> Chinese, Simplified */
  {"ce",	newTag('C','H','E',' ')},	/* Chechen */
/*{"ceb",	newTag('C','E','B',' ')},*/	/* Cebuano */
  {"cek",	newTag('Q','I','N',' ')},	/* Eastern Khumi Chin -> Chin */
  {"cey",	newTag('Q','I','N',' ')},	/* Ekai Chin -> Chin */
  {"cfm",	newTag('H','A','L',' ')},	/* Halam (Falam Chin) */
  {"cfm",	newTag('Q','I','N',' ')},	/* Falam Chin -> Chin */
/*{"cgg",	newTag('C','G','G',' ')},*/	/* Chiga */
  {"ch",	newTag('C','H','A',' ')},	/* Chamorro */
  {"chf",	newTag('M','Y','N',' ')},	/* Tabasco Chontal -> Mayan */
  {"chg",	0	},	/* Chagatai != Chaha Gurage */
  {"chh",	0	},	/* Chinook != Chattisgarhi */
  {"chj",	newTag('C','C','H','N')},	/* Ojitlán Chinantec -> Chinantec */
  {"chk",	newTag('C','H','K','0')},	/* Chuukese */
  {"chn",	newTag('C','P','P',' ')},	/* Chinook jargon -> Creoles */
/*{"cho",	newTag('C','H','O',' ')},*/	/* Choctaw */
  {"chp",	newTag('C','H','P',' ')},	/* Chipewyan */
  {"chp",	newTag('S','A','Y',' ')},	/* Chipewyan -> Sayisi */
  {"chp",	newTag('A','T','H',' ')},	/* Chipewyan -> Athapaskan */
  {"chq",	newTag('C','C','H','N')},	/* Quiotepec Chinantec -> Chinantec */
/*{"chr",	newTag('C','H','R',' ')},*/	/* Cherokee */
/*{"chy",	newTag('C','H','Y',' ')},*/	/* Cheyenne */
  {"chz",	newTag('C','C','H','N')},	/* Ozumacín Chinantec -> Chinantec */
  {"ciw",	newTag('O','J','B',' ')},	/* Chippewa -> Ojibway */
/*{"cja",	newTag('C','J','A',' ')},*/	/* Western Cham */
/*{"cjm",	newTag('C','J','M',' ')},*/	/* Eastern Cham */
  {"cjy",	newTag('Z','H','S',' ')},	/* Jinyu Chinese -> Chinese, Simplified */
  {"cka",	newTag('Q','I','N',' ')},	/* Khumi Awa Chin (retired code) (retired code) -> Chin */
  {"ckb",	newTag('K','U','R',' ')},	/* Central Kurdish -> Kurdish */
  {"ckn",	newTag('Q','I','N',' ')},	/* Kaang Chin -> Chin */
  {"cks",	newTag('C','P','P',' ')},	/* Tayo -> Creoles */
  {"ckt",	newTag('C','H','K',' ')},	/* Chukot -> Chukchi */
  {"ckz",	newTag('M','Y','N',' ')},	/* Cakchiquel-Quiché Mixed Language -> Mayan */
  {"clc",	newTag('A','T','H',' ')},	/* Chilcotin -> Athapaskan */
  {"cld",	newTag('S','Y','R',' ')},	/* Chaldean Neo-Aramaic -> Syriac */
  {"cle",	newTag('C','C','H','N')},	/* Lealao Chinantec -> Chinantec */
  {"clj",	newTag('Q','I','N',' ')},	/* Laitu Chin -> Chin */
  {"clt",	newTag('Q','I','N',' ')},	/* Lautu Chin -> Chin */
  {"cmn",	newTag('Z','H','S',' ')},	/* Mandarin Chinese -> Chinese, Simplified */
  {"cmr",	newTag('Q','I','N',' ')},	/* Mro-Khimi Chin -> Chin */
  {"cnb",	newTag('Q','I','N',' ')},	/* Chinbon Chin -> Chin */
  {"cnh",	newTag('Q','I','N',' ')},	/* Hakha Chin -> Chin */
  {"cnk",	newTag('Q','I','N',' ')},	/* Khumi Chin -> Chin */
  {"cnl",	newTag('C','C','H','N')},	/* Lalana Chinantec -> Chinantec */
  {"cnp",	newTag('Z','H','S',' ')},	/* Northern Ping Chinese -> Chinese, Simplified */
  {"cnr",	newTag('S','R','B',' ')},	/* Montenegrin -> Serbian */
  {"cnt",	newTag('C','C','H','N')},	/* Tepetotutla Chinantec -> Chinantec */
  {"cnu",	newTag('B','B','R',' ')},	/* Chenoua -> Berber */
  {"cnw",	newTag('Q','I','N',' ')},	/* Ngawn Chin -> Chin */
  {"co",	newTag('C','O','S',' ')},	/* Corsican */
  {"coa",	newTag('M','L','Y',' ')},	/* Cocos Islands Malay -> Malay */
  {"cob",	newTag('M','Y','N',' ')},	/* Chicomuceltec -> Mayan */
/*{"cop",	newTag('C','O','P',' ')},*/	/* Coptic */
  {"coq",	newTag('A','T','H',' ')},	/* Coquille -> Athapaskan */
  {"cpa",	newTag('C','C','H','N')},	/* Palantla Chinantec -> Chinantec */
  {"cpe",	newTag('C','P','P',' ')},	/* English-based creoles and pidgins [family] -> Creoles */
  {"cpf",	newTag('C','P','P',' ')},	/* French-based creoles and pidgins [family] -> Creoles */
  {"cpi",	newTag('C','P','P',' ')},	/* Chinese Pidgin English -> Creoles */
/*{"cpp",	newTag('C','P','P',' ')},*/	/* Portuguese-based creoles and pidgins [family] -> Creoles */
  {"cpx",	newTag('Z','H','S',' ')},	/* Pu-Xian Chinese -> Chinese, Simplified */
  {"cqd",	newTag('H','M','N',' ')},	/* Chuanqiandian Cluster Miao -> Hmong */
  {"cqu",	newTag('Q','U','H',' ')},	/* Chilean Quechua (retired code) (retired code) -> Quechua (Bolivia) */
  {"cqu",	newTag('Q','U','Z',' ')},	/* Chilean Quechua (retired code) (retired code) -> Quechua */
  {"cr",	newTag('C','R','E',' ')},	/* Cree [macrolanguage] */
  {"crh",	newTag('C','R','T',' ')},	/* Crimean Tatar */
  {"cri",	newTag('C','P','P',' ')},	/* Sãotomense -> Creoles */
  {"crj",	newTag('E','C','R',' ')},	/* Southern East Cree -> Eastern Cree */
  {"crj",	newTag('Y','C','R',' ')},	/* Southern East Cree -> Y-Cree */
  {"crj",	newTag('C','R','E',' ')},	/* Southern East Cree -> Cree */
  {"crk",	newTag('W','C','R',' ')},	/* Plains Cree -> West-Cree */
  {"crk",	newTag('Y','C','R',' ')},	/* Plains Cree -> Y-Cree */
  {"crk",	newTag('C','R','E',' ')},	/* Plains Cree -> Cree */
  {"crl",	newTag('E','C','R',' ')},	/* Northern East Cree -> Eastern Cree */
  {"crl",	newTag('Y','C','R',' ')},	/* Northern East Cree -> Y-Cree */
  {"crl",	newTag('C','R','E',' ')},	/* Northern East Cree -> Cree */
  {"crm",	newTag('M','C','R',' ')},	/* Moose Cree */
  {"crm",	newTag('L','C','R',' ')},	/* Moose Cree -> L-Cree */
  {"crm",	newTag('C','R','E',' ')},	/* Moose Cree -> Cree */
  {"crp",	newTag('C','P','P',' ')},	/* Creoles and pidgins [family] -> Creoles */
  {"crr",	0	},	/* Carolina Algonquian != Carrier */
  {"crs",	newTag('C','P','P',' ')},	/* Seselwa Creole French -> Creoles */
  {"crt",	0	},	/* Iyojwa'ja Chorote != Crimean Tatar */
  {"crx",	newTag('C','R','R',' ')},	/* Carrier */
  {"crx",	newTag('A','T','H',' ')},	/* Carrier -> Athapaskan */
  {"cs",	newTag('C','S','Y',' ')},	/* Czech */
  {"csa",	newTag('C','C','H','N')},	/* Chiltepec Chinantec -> Chinantec */
/*{"csb",	newTag('C','S','B',' ')},*/	/* Kashubian */
  {"csh",	newTag('Q','I','N',' ')},	/* Asho Chin -> Chin */
  {"csj",	newTag('Q','I','N',' ')},	/* Songlai Chin -> Chin */
  {"csl",	0	},	/* Chinese Sign Language != Church Slavonic */
  {"cso",	newTag('C','C','H','N')},	/* Sochiapam Chinantec -> Chinantec */
  {"csp",	newTag('Z','H','S',' ')},	/* Southern Ping Chinese -> Chinese, Simplified */
  {"csv",	newTag('Q','I','N',' ')},	/* Sumtu Chin -> Chin */
  {"csw",	newTag('N','C','R',' ')},	/* Swampy Cree -> N-Cree */
  {"csw",	newTag('N','H','C',' ')},	/* Swampy Cree -> Norway House Cree */
  {"csw",	newTag('C','R','E',' ')},	/* Swampy Cree -> Cree */
  {"csy",	newTag('Q','I','N',' ')},	/* Siyin Chin -> Chin */
  {"ctc",	newTag('A','T','H',' ')},	/* Chetco -> Athapaskan */
  {"ctd",	newTag('Q','I','N',' ')},	/* Tedim Chin -> Chin */
  {"cte",	newTag('C','C','H','N')},	/* Tepinapa Chinantec -> Chinantec */
/*{"ctg",	newTag('C','T','G',' ')},*/	/* Chittagonian */
  {"cth",	newTag('Q','I','N',' ')},	/* Thaiphum Chin -> Chin */
  {"ctl",	newTag('C','C','H','N')},	/* Tlacoatzintepec Chinantec -> Chinantec */
  {"cts",	newTag('B','I','K',' ')},	/* Northern Catanduanes Bikol -> Bikol */
  {"ctu",	newTag('M','Y','N',' ')},	/* Chol -> Mayan */
  {"cu",	newTag('C','S','L',' ')},	/* Church Slavonic */
  {"cuc",	newTag('C','C','H','N')},	/* Usila Chinantec -> Chinantec */
/*{"cuk",	newTag('C','U','K',' ')},*/	/* San Blas Kuna */
  {"cv",	newTag('C','H','U',' ')},	/* Chuvash */
  {"cvn",	newTag('C','C','H','N')},	/* Valle Nacional Chinantec -> Chinantec */
  {"cwd",	newTag('D','C','R',' ')},	/* Woods Cree */
  {"cwd",	newTag('T','C','R',' ')},	/* Woods Cree -> TH-Cree */
  {"cwd",	newTag('C','R','E',' ')},	/* Woods Cree -> Cree */
  {"cy",	newTag('W','E','L',' ')},	/* Welsh */
  {"czh",	newTag('Z','H','S',' ')},	/* Huizhou Chinese -> Chinese, Simplified */
  {"czo",	newTag('Z','H','S',' ')},	/* Min Zhong Chinese -> Chinese, Simplified */
  {"czt",	newTag('Q','I','N',' ')},	/* Zotung Chin -> Chin */
  {"da",	newTag('D','A','N',' ')},	/* Danish */
  {"dao",	newTag('Q','I','N',' ')},	/* Daai Chin -> Chin */
  {"dap",	newTag('N','I','S',' ')},	/* Nisi (India) (retired code) (retired code) */
/*{"dar",	newTag('D','A','R',' ')},*/	/* Dargwa */
/*{"dax",	newTag('D','A','X',' ')},*/	/* Dayi */
  {"dcr",	newTag('C','P','P',' ')},	/* Negerhollands -> Creoles */
  {"de",	newTag('D','E','U',' ')},	/* German */
  {"den",	newTag('S','L','A',' ')},	/* Slave (Athapascan) [macrolanguage] -> Slavey */
  {"den",	newTag('A','T','H',' ')},	/* Slave (Athapascan) [macrolanguage] -> Athapaskan */
  {"dep",	newTag('C','P','P',' ')},	/* Pidgin Delaware -> Creoles */
  {"dgo",	newTag('D','G','O',' ')},	/* Dogri (individual language) */
  {"dgo",	newTag('D','G','R',' ')},	/* Dogri (macrolanguage) */
  {"dgr",	newTag('A','T','H',' ')},	/* Dogrib -> Athapaskan */
  {"dhd",	newTag('M','A','W',' ')},	/* Dhundari -> Marwari */
/*{"dhg",	newTag('D','H','G',' ')},*/	/* Dhangu */
  {"dhv",	0	},	/* Dehu != Divehi (Dhivehi, Maldivian) (deprecated) */
  {"dib",	newTag('D','N','K',' ')},	/* South Central Dinka -> Dinka */
  {"dik",	newTag('D','N','K',' ')},	/* Southwestern Dinka -> Dinka */
  {"din",	newTag('D','N','K',' ')},	/* Dinka [macrolanguage] */
  {"dip",	newTag('D','N','K',' ')},	/* Northeastern Dinka -> Dinka */
  {"diq",	newTag('D','I','Q',' ')},	/* Dimli */
  {"diq",	newTag('Z','Z','A',' ')},	/* Dimli -> Zazaki */
  {"diw",	newTag('D','N','K',' ')},	/* Northwestern Dinka -> Dinka */
  {"dje",	newTag('D','J','R',' ')},	/* Zarma */
  {"djk",	newTag('C','P','P',' ')},	/* Eastern Maroon Creole -> Creoles */
  {"djr",	newTag('D','J','R','0')},	/* Djambarrpuyngu */
  {"dks",	newTag('D','N','K',' ')},	/* Southeastern Dinka -> Dinka */
  {"dng",	newTag('D','U','N',' ')},	/* Dungan */
/*{"dnj",	newTag('D','N','J',' ')},*/	/* Dan */
  {"dnk",	0	},	/* Dengka != Dinka */
  {"doi",	newTag('D','G','R',' ')},	/* Dogri (macrolanguage) [macrolanguage] */
  {"drh",	newTag('M','N','G',' ')},	/* Darkhat (retired code) (retired code) -> Mongolian */
  {"dri",	0	},	/* C'Lela != Dari */
  {"drw",	newTag('D','R','I',' ')},	/* Darwazi (retired code) (retired code) -> Dari */
  {"drw",	newTag('F','A','R',' ')},	/* Darwazi (retired code) (retired code) -> Persian */
  {"dsb",	newTag('L','S','B',' ')},	/* Lower Sorbian */
  {"dty",	newTag('N','E','P',' ')},	/* Dotyali -> Nepali */
/*{"duj",	newTag('D','U','J',' ')},*/	/* Dhuwal (retired code) (retired code) */
  {"dun",	0	},	/* Dusun Deyah != Dungan */
  {"dup",	newTag('M','L','Y',' ')},	/* Duano -> Malay */
  {"dv",	newTag('D','I','V',' ')},	/* Divehi (Dhivehi, Maldivian) */
  {"dv",	newTag('D','H','V',' ')},	/* Divehi (Dhivehi, Maldivian) (deprecated) */
  {"dwk",	newTag('K','U','I',' ')},	/* Dawik Kui -> Kui */
  {"dwu",	newTag('D','U','J',' ')},	/* Dhuwal */
  {"dwy",	newTag('D','U','J',' ')},	/* Dhuwaya -> Dhuwal */
  {"dyu",	newTag('J','U','L',' ')},	/* Dyula -> Jula */
  {"dz",	newTag('D','Z','N',' ')},	/* Dzongkha */
  {"dzn",	0	},	/* Dzando != Dzongkha */
  {"ecr",	0	},	/* Eteocretan != Eastern Cree */
  {"ee",	newTag('E','W','E',' ')},	/* Ewe */
/*{"efi",	newTag('E','F','I',' ')},*/	/* Efik */
  {"ekk",	newTag('E','T','I',' ')},	/* Standard Estonian -> Estonian */
  {"eky",	newTag('K','R','N',' ')},	/* Eastern Kayah -> Karen */
  {"el",	newTag('E','L','L',' ')},	/* Modern Greek (1453-) -> Greek */
  {"emk",	newTag('E','M','K',' ')},	/* Eastern Maninkakan */
  {"emk",	newTag('M','N','K',' ')},	/* Eastern Maninkakan -> Maninka */
  {"emy",	newTag('M','Y','N',' ')},	/* Epigraphic Mayan -> Mayan */
  {"en",	newTag('E','N','G',' ')},	/* English */
  {"enb",	newTag('K','A','L',' ')},	/* Markweeta -> Kalenjin */
  {"enf",	newTag('F','N','E',' ')},	/* Forest Enets */
  {"enh",	newTag('T','N','E',' ')},	/* Tundra Enets */
  {"eo",	newTag('N','T','O',' ')},	/* Esperanto */
  {"es",	newTag('E','S','P',' ')},	/* Spanish */
  {"esg",	newTag('G','O','N',' ')},	/* Aheri Gondi -> Gondi */
  {"esi",	newTag('I','P','K',' ')},	/* North Alaskan Inupiatun -> Inupiat */
  {"esk",	newTag('I','P','K',' ')},	/* Northwest Alaska Inupiatun -> Inupiat */
/*{"esu",	newTag('E','S','U',' ')},*/	/* Central Yupik */
  {"et",	newTag('E','T','I',' ')},	/* Estonian [macrolanguage] */
  {"eto",	newTag('B','T','I',' ')},	/* Eton (Cameroon) -> Beti */
  {"eu",	newTag('E','U','Q',' ')},	/* Basque */
  {"euq",	0	},	/* Basque [family] != Basque */
  {"eve",	newTag('E','V','N',' ')},	/* Even */
  {"evn",	newTag('E','V','K',' ')},	/* Evenki */
  {"ewo",	newTag('B','T','I',' ')},	/* Ewondo -> Beti */
  {"eyo",	newTag('K','A','L',' ')},	/* Keiyo -> Kalenjin */
  {"fa",	newTag('F','A','R',' ')},	/* Persian [macrolanguage] */
  {"fab",	newTag('C','P','P',' ')},	/* Fa d'Ambu -> Creoles */
  {"fan",	newTag('F','A','N','0')},	/* Fang (Equatorial Guinea) */
  {"fan",	newTag('B','T','I',' ')},	/* Fang (Equatorial Guinea) -> Beti */
  {"far",	0	},	/* Fataleka != Persian */
  {"fat",	newTag('F','A','T',' ')},	/* Fanti */
  {"fat",	newTag('A','K','A',' ')},	/* Fanti -> Akan */
  {"fbl",	newTag('B','I','K',' ')},	/* West Albay Bikol -> Bikol */
  {"ff",	newTag('F','U','L',' ')},	/* Fulah [macrolanguage] */
  {"ffm",	newTag('F','U','L',' ')},	/* Maasina Fulfulde -> Fulah */
  {"fi",	newTag('F','I','N',' ')},	/* Finnish */
  {"fil",	newTag('P','I','L',' ')},	/* Filipino */
  {"fj",	newTag('F','J','I',' ')},	/* Fijian */
  {"flm",	newTag('H','A','L',' ')},	/* Halam (Falam Chin) (retired code) */
  {"flm",	newTag('Q','I','N',' ')},	/* Falam Chin (retired code) -> Chin */
  {"fmp",	newTag('F','M','P',' ')},	/* Fe’fe’ */
  {"fmp",	newTag('B','M','L',' ')},	/* Fe'fe' -> Bamileke */
  {"fng",	newTag('C','P','P',' ')},	/* Fanagalo -> Creoles */
  {"fo",	newTag('F','O','S',' ')},	/* Faroese */
/*{"fon",	newTag('F','O','N',' ')},*/	/* Fon */
  {"fos",	0	},	/* Siraya != Faroese */
  {"fpe",	newTag('C','P','P',' ')},	/* Fernando Po Creole English -> Creoles */
  {"fr",	newTag('F','R','A',' ')},	/* French */
/*{"frc",	newTag('F','R','C',' ')},*/	/* Cajun French */
/*{"frp",	newTag('F','R','P',' ')},*/	/* Arpitan */
  {"fub",	newTag('F','U','L',' ')},	/* Adamawa Fulfulde -> Fulah */
  {"fuc",	newTag('F','U','L',' ')},	/* Pulaar -> Fulah */
  {"fue",	newTag('F','U','L',' ')},	/* Borgu Fulfulde -> Fulah */
  {"fuf",	newTag('F','T','A',' ')},	/* Pular -> Futa */
  {"fuf",	newTag('F','U','L',' ')},	/* Pular -> Fulah */
  {"fuh",	newTag('F','U','L',' ')},	/* Western Niger Fulfulde -> Fulah */
  {"fui",	newTag('F','U','L',' ')},	/* Bagirmi Fulfulde -> Fulah */
  {"fuq",	newTag('F','U','L',' ')},	/* Central-Eastern Niger Fulfulde -> Fulah */
  {"fur",	newTag('F','R','L',' ')},	/* Friulian */
  {"fuv",	newTag('F','U','V',' ')},	/* Nigerian Fulfulde */
  {"fuv",	newTag('F','U','L',' ')},	/* Nigerian Fulfulde -> Fulah */
  {"fy",	newTag('F','R','I',' ')},	/* Western Frisian -> Frisian */
  {"ga",	newTag('I','R','I',' ')},	/* Irish */
  {"gaa",	newTag('G','A','D',' ')},	/* Ga */
  {"gac",	newTag('C','P','P',' ')},	/* Mixed Great Andamanese -> Creoles */
  {"gad",	0	},	/* Gaddang != Ga */
  {"gae",	0	},	/* Guarequena != Scottish Gaelic (Gaelic) */
/*{"gag",	newTag('G','A','G',' ')},*/	/* Gagauz */
  {"gal",	0	},	/* Galolen != Galician */
  {"gan",	newTag('Z','H','S',' ')},	/* Gan Chinese -> Chinese, Simplified */
  {"gaw",	0	},	/* Nobonob != Garhwali */
  {"gax",	newTag('O','R','O',' ')},	/* Borana-Arsi-Guji Oromo -> Oromo */
  {"gaz",	newTag('O','R','O',' ')},	/* West Central Oromo -> Oromo */
  {"gbm",	newTag('G','A','W',' ')},	/* Garhwali */
  {"gce",	newTag('A','T','H',' ')},	/* Galice -> Athapaskan */
  {"gcf",	newTag('C','P','P',' ')},	/* Guadeloupean Creole French -> Creoles */
  {"gcl",	newTag('C','P','P',' ')},	/* Grenadian Creole English -> Creoles */
  {"gcr",	newTag('C','P','P',' ')},	/* Guianese Creole French -> Creoles */
  {"gd",	newTag('G','A','E',' ')},	/* Scottish Gaelic (Gaelic) */
  {"gda",	newTag('R','A','J',' ')},	/* Gade Lohar -> Rajasthani */
/*{"gez",	newTag('G','E','Z',' ')},*/	/* Geez */
  {"ggo",	newTag('G','O','N',' ')},	/* Southern Gondi (retired code) (retired code) -> Gondi */
  {"gha",	newTag('B','B','R',' ')},	/* Ghadamès -> Berber */
  {"ghk",	newTag('K','R','N',' ')},	/* Geko Karen -> Karen */
  {"gho",	newTag('B','B','R',' ')},	/* Ghomara -> Berber */
  {"gib",	newTag('C','P','P',' ')},	/* Gibanawa -> Creoles */
/*{"gih",	newTag('G','I','H',' ')},*/	/* Githabul */
  {"gil",	newTag('G','I','L','0')},	/* Kiribati (Gilbertese) */
  {"gju",	newTag('R','A','J',' ')},	/* Gujari -> Rajasthani */
  {"gkp",	newTag('G','K','P',' ')},	/* Guinea Kpelle -> Kpelle (Guinea) */
  {"gkp",	newTag('K','P','L',' ')},	/* Guinea Kpelle -> Kpelle */
  {"gl",	newTag('G','A','L',' ')},	/* Galician */
  {"gld",	newTag('N','A','N',' ')},	/* Nanai */
/*{"glk",	newTag('G','L','K',' ')},*/	/* Gilaki */
  {"gmz",	0	},	/* Mgbolizhia != Gumuz */
  {"gn",	newTag('G','U','A',' ')},	/* Guarani [macrolanguage] */
  {"gnb",	newTag('Q','I','N',' ')},	/* Gangte -> Chin */
/*{"gnn",	newTag('G','N','N',' ')},*/	/* Gumatj */
  {"gno",	newTag('G','O','N',' ')},	/* Northern Gondi -> Gondi */
  {"gnw",	newTag('G','U','A',' ')},	/* Western Bolivian Guaraní -> Guarani */
/*{"gog",	newTag('G','O','G',' ')},*/	/* Gogo */
  {"gom",	newTag('K','O','K',' ')},	/* Goan Konkani -> Konkani */
/*{"gon",	newTag('G','O','N',' ')},*/	/* Gondi [macrolanguage] */
  {"goq",	newTag('C','P','P',' ')},	/* Gorap -> Creoles */
  {"gox",	newTag('B','A','D','0')},	/* Gobu -> Banda */
  {"gpe",	newTag('C','P','P',' ')},	/* Ghanaian Pidgin English -> Creoles */
  {"gro",	0	},	/* Groma != Garo */
  {"grr",	newTag('B','B','R',' ')},	/* Taznatit -> Berber */
  {"grt",	newTag('G','R','O',' ')},	/* Garo */
  {"gru",	newTag('S','O','G',' ')},	/* Kistane -> Sodo Gurage */
  {"gsw",	newTag('A','L','S',' ')},	/* Alsatian */
  {"gu",	newTag('G','U','J',' ')},	/* Gujarati */
  {"gua",	0	},	/* Shiki != Guarani */
/*{"guc",	newTag('G','U','C',' ')},*/	/* Wayuu */
/*{"guf",	newTag('G','U','F',' ')},*/	/* Gupapuyngu */
  {"gug",	newTag('G','U','A',' ')},	/* Paraguayan Guaraní -> Guarani */
  {"gui",	newTag('G','U','A',' ')},	/* Eastern Bolivian Guaraní -> Guarani */
  {"guk",	newTag('G','M','Z',' ')},	/* Gumuz */
  {"gul",	newTag('C','P','P',' ')},	/* Sea Island Creole English -> Creoles */
  {"gun",	newTag('G','U','A',' ')},	/* Mbyá Guaraní -> Guarani */
/*{"guz",	newTag('G','U','Z',' ')},*/	/* Gusii */
  {"gv",	newTag('M','N','X',' ')},	/* Manx */
  {"gwi",	newTag('A','T','H',' ')},	/* Gwichʼin -> Athapaskan */
  {"gyn",	newTag('C','P','P',' ')},	/* Guyanese Creole English -> Creoles */
  {"ha",	newTag('H','A','U',' ')},	/* Hausa */
  {"haa",	newTag('A','T','H',' ')},	/* Han -> Athapaskan */
  {"hae",	newTag('O','R','O',' ')},	/* Eastern Oromo -> Oromo */
  {"hai",	0	},	/* Haida [macrolanguage] != Haitian (Haitian Creole) */
  {"hak",	newTag('Z','H','S',' ')},	/* Hakka Chinese -> Chinese, Simplified */
  {"hal",	0	},	/* Halang != Halam (Falam Chin) */
  {"har",	newTag('H','R','I',' ')},	/* Harari */
/*{"haw",	newTag('H','A','W',' ')},*/	/* Hawaiian */
/*{"hay",	newTag('H','A','Y',' ')},*/	/* Haya */
/*{"haz",	newTag('H','A','Z',' ')},*/	/* Hazaragi */
  {"hbn",	0	},	/* Heiban != Hammer-Banna */
  {"hca",	newTag('C','P','P',' ')},	/* Andaman Creole Hindi -> Creoles */
  {"he",	newTag('I','W','R',' ')},	/* Hebrew */
  {"hea",	newTag('H','M','N',' ')},	/* Northern Qiandong Miao -> Hmong */
  {"hi",	newTag('H','I','N',' ')},	/* Hindi */
/*{"hil",	newTag('H','I','L',' ')},*/	/* Hiligaynon */
  {"hji",	newTag('M','L','Y',' ')},	/* Haji -> Malay */
  {"hlt",	newTag('Q','I','N',' ')},	/* Matu Chin -> Chin */
  {"hma",	newTag('H','M','N',' ')},	/* Southern Mashan Hmong -> Hmong */
  {"hmc",	newTag('H','M','N',' ')},	/* Central Huishui Hmong -> Hmong */
  {"hmd",	newTag('H','M','N',' ')},	/* Large Flowery Miao -> Hmong */
  {"hme",	newTag('H','M','N',' ')},	/* Eastern Huishui Hmong -> Hmong */
  {"hmg",	newTag('H','M','N',' ')},	/* Southwestern Guiyang Hmong -> Hmong */
  {"hmh",	newTag('H','M','N',' ')},	/* Southwestern Huishui Hmong -> Hmong */
  {"hmi",	newTag('H','M','N',' ')},	/* Northern Huishui Hmong -> Hmong */
  {"hmj",	newTag('H','M','N',' ')},	/* Ge -> Hmong */
  {"hml",	newTag('H','M','N',' ')},	/* Luopohe Hmong -> Hmong */
  {"hmm",	newTag('H','M','N',' ')},	/* Central Mashan Hmong -> Hmong */
/*{"hmn",	newTag('H','M','N',' ')},*/	/* Hmong [macrolanguage] */
  {"hmp",	newTag('H','M','N',' ')},	/* Northern Mashan Hmong -> Hmong */
  {"hmq",	newTag('H','M','N',' ')},	/* Eastern Qiandong Miao -> Hmong */
  {"hmr",	newTag('Q','I','N',' ')},	/* Hmar -> Chin */
  {"hms",	newTag('H','M','N',' ')},	/* Southern Qiandong Miao -> Hmong */
  {"hmw",	newTag('H','M','N',' ')},	/* Western Mashan Hmong -> Hmong */
  {"hmy",	newTag('H','M','N',' ')},	/* Southern Guiyang Hmong -> Hmong */
  {"hmz",	newTag('H','M','N',' ')},	/* Hmong Shua -> Hmong */
/*{"hnd",	newTag('H','N','D',' ')},*/	/* Southern Hindko -> Hindko */
  {"hne",	newTag('C','H','H',' ')},	/* Chhattisgarhi -> Chattisgarhi */
  {"hnj",	newTag('H','M','N',' ')},	/* Hmong Njua -> Hmong */
  {"hno",	newTag('H','N','D',' ')},	/* Northern Hindko -> Hindko */
  {"ho",	newTag('H','M','O',' ')},	/* Hiri Motu */
  {"ho",	newTag('C','P','P',' ')},	/* Hiri Motu -> Creoles */
  {"hoc",	newTag('H','O',' ',' ')},	/* Ho */
  {"hoi",	newTag('A','T','H',' ')},	/* Holikachuk -> Athapaskan */
  {"hoj",	newTag('H','A','R',' ')},	/* Hadothi -> Harauti */
  {"hoj",	newTag('R','A','J',' ')},	/* Hadothi -> Rajasthani */
  {"hr",	newTag('H','R','V',' ')},	/* Croatian */
  {"hra",	newTag('Q','I','N',' ')},	/* Hrangkhol -> Chin */
  {"hrm",	newTag('H','M','N',' ')},	/* Horned Miao -> Hmong */
  {"hsb",	newTag('U','S','B',' ')},	/* Upper Sorbian */
  {"hsn",	newTag('Z','H','S',' ')},	/* Xiang Chinese -> Chinese, Simplified */
  {"ht",	newTag('H','A','I',' ')},	/* Haitian (Haitian Creole) */
  {"ht",	newTag('C','P','P',' ')},	/* Haitian -> Creoles */
  {"hu",	newTag('H','U','N',' ')},	/* Hungarian */
  {"huj",	newTag('H','M','N',' ')},	/* Northern Guiyang Hmong -> Hmong */
  {"hup",	newTag('A','T','H',' ')},	/* Hupa -> Athapaskan */
  {"hus",	newTag('M','Y','N',' ')},	/* Huastec -> Mayan */
  {"hwc",	newTag('C','P','P',' ')},	/* Hawai'i Creole English -> Creoles */
  {"hy",	newTag('H','Y','E','0')},	/* Armenian -> Armenian East */
  {"hy",	newTag('H','Y','E',' ')},	/* Armenian */
  {"hyw",	newTag('H','Y','E',' ')},	/* Western Armenian -> Armenian */
  {"hz",	newTag('H','E','R',' ')},	/* Herero */
  {"ia",	newTag('I','N','A',' ')},	/* Interlingua (International Auxiliary Language Association) */
/*{"iba",	newTag('I','B','A',' ')},*/	/* Iban */
/*{"ibb",	newTag('I','B','B',' ')},*/	/* Ibibio */
  {"iby",	newTag('I','J','O',' ')},	/* Ibani -> Ijo */
  {"icr",	newTag('C','P','P',' ')},	/* Islander Creole English -> Creoles */
  {"id",	newTag('I','N','D',' ')},	/* Indonesian */
  {"id",	newTag('M','L','Y',' ')},	/* Indonesian -> Malay */
  {"ida",	newTag('L','U','H',' ')},	/* Idakho-Isukha-Tiriki -> Luyia */
  {"idb",	newTag('C','P','P',' ')},	/* Indo-Portuguese -> Creoles */
  {"ie",	newTag('I','L','E',' ')},	/* Interlingue */
  {"ig",	newTag('I','B','O',' ')},	/* Igbo */
  {"igb",	newTag('E','B','I',' ')},	/* Ebira */
  {"ihb",	newTag('C','P','P',' ')},	/* Iha Based Pidgin -> Creoles */
  {"ii",	newTag('Y','I','M',' ')},	/* Sichuan Yi -> Yi Modern */
  {"ijc",	newTag('I','J','O',' ')},	/* Izon -> Ijo */
  {"ije",	newTag('I','J','O',' ')},	/* Biseni -> Ijo */
  {"ijn",	newTag('I','J','O',' ')},	/* Kalabari -> Ijo */
/*{"ijo",	newTag('I','J','O',' ')},*/	/* Ijo [family] */
  {"ijs",	newTag('I','J','O',' ')},	/* Southeast Ijo -> Ijo */
  {"ik",	newTag('I','P','K',' ')},	/* Inupiaq [macrolanguage] -> Inupiat */
  {"ike",	newTag('I','N','U',' ')},	/* Eastern Canadian Inuktitut -> Inuktitut */
  {"ikt",	newTag('I','N','U',' ')},	/* Inuinnaqtun -> Inuktitut */
/*{"ilo",	newTag('I','L','O',' ')},*/	/* Iloko -> Ilokano */
  {"in",	newTag('I','N','D',' ')},	/* Indonesian (retired code) (retired code) */
  {"in",	newTag('M','L','Y',' ')},	/* Indonesian (retired code) (retired code) -> Malay */
  {"ing",	newTag('A','T','H',' ')},	/* Degexit'an -> Athapaskan */
  {"inh",	newTag('I','N','G',' ')},	/* Ingush */
  {"io",	newTag('I','D','O',' ')},	/* Ido */
  {"iri",	0	},	/* Rigwe != Irish */
  {"is",	newTag('I','S','L',' ')},	/* Icelandic */
  {"ism",	0	},	/* Masimasi != Inari Sami */
  {"it",	newTag('I','T','A',' ')},	/* Italian */
  {"itz",	newTag('M','Y','N',' ')},	/* Itzá -> Mayan */
  {"iu",	newTag('I','N','U',' ')},	/* Inuktitut [macrolanguage] */
  {"iw",	newTag('I','W','R',' ')},	/* Hebrew (retired code) (retired code) */
  {"ixl",	newTag('M','Y','N',' ')},	/* Ixil -> Mayan */
  {"ja",	newTag('J','A','N',' ')},	/* Japanese */
  {"jac",	newTag('M','Y','N',' ')},	/* Popti' -> Mayan */
  {"jak",	newTag('M','L','Y',' ')},	/* Jakun -> Malay */
  {"jam",	newTag('J','A','M',' ')},	/* Jamaican Creole English -> Jamaican Creole */
  {"jam",	newTag('C','P','P',' ')},	/* Jamaican Creole English -> Creoles */
  {"jan",	0	},	/* Jandai != Japanese */
  {"jax",	newTag('M','L','Y',' ')},	/* Jambi Malay -> Malay */
  {"jbe",	newTag('B','B','R',' ')},	/* Judeo-Berber -> Berber */
  {"jbn",	newTag('B','B','R',' ')},	/* Nafusi -> Berber */
/*{"jbo",	newTag('J','B','O',' ')},*/	/* Lojban */
/*{"jct",	newTag('J','C','T',' ')},*/	/* Krymchak */
  {"jgo",	newTag('B','M','L',' ')},	/* Ngomba -> Bamileke */
  {"ji",	newTag('J','I','I',' ')},	/* Yiddish (retired code) (retired code) */
  {"jii",	0	},	/* Jiiddu != Yiddish */
  {"jkm",	newTag('K','R','N',' ')},	/* Mobwa Karen -> Karen */
  {"jkp",	newTag('K','R','N',' ')},	/* Paku Karen -> Karen */
  {"jud",	0	},	/* Worodougou != Ladino */
  {"jul",	0	},	/* Jirel != Jula */
  {"jv",	newTag('J','A','V',' ')},	/* Javanese */
  {"jvd",	newTag('C','P','P',' ')},	/* Javindo -> Creoles */
  {"jw",	newTag('J','A','V',' ')},	/* Javanese (retired code) (retired code) */
  {"ka",	newTag('K','A','T',' ')},	/* Georgian */
  {"kaa",	newTag('K','R','K',' ')},	/* Karakalpak */
  {"kab",	newTag('K','A','B','0')},	/* Kabyle */
  {"kab",	newTag('B','B','R',' ')},	/* Kabyle -> Berber */
  {"kac",	0	},	/* Kachin != Kachchi */
  {"kam",	newTag('K','M','B',' ')},	/* Kamba (Kenya) */
  {"kar",	newTag('K','R','N',' ')},	/* Karen [family] */
  {"kbd",	newTag('K','A','B',' ')},	/* Kabardian */
  {"kby",	newTag('K','N','R',' ')},	/* Manga Kanuri -> Kanuri */
  {"kca",	newTag('K','H','K',' ')},	/* Khanty -> Khanty-Kazim */
  {"kca",	newTag('K','H','S',' ')},	/* Khanty -> Khanty-Shurishkar */
  {"kca",	newTag('K','H','V',' ')},	/* Khanty -> Khanty-Vakhi */
  {"kcn",	newTag('C','P','P',' ')},	/* Nubi -> Creoles */
/*{"kde",	newTag('K','D','E',' ')},*/	/* Makonde */
  {"kdr",	newTag('K','R','M',' ')},	/* Karaim */
  {"kdt",	newTag('K','U','Y',' ')},	/* Kuy */
  {"kea",	newTag('K','E','A',' ')},	/* Kabuverdianu (Crioulo) */
  {"kea",	newTag('C','P','P',' ')},	/* Kabuverdianu -> Creoles */
  {"keb",	0	},	/* Kélé != Kebena */
  {"kek",	newTag('K','E','K',' ')},	/* Kekchí */
  {"kek",	newTag('M','Y','N',' ')},	/* Kekchí -> Mayan */
  {"kex",	newTag('K','K','N',' ')},	/* Kukna -> Kokni */
  {"kfa",	newTag('K','O','D',' ')},	/* Kodava -> Kodagu */
  {"kfr",	newTag('K','A','C',' ')},	/* Kachhi -> Kachchi */
  {"kfx",	newTag('K','U','L',' ')},	/* Kullu Pahari -> Kulvi */
  {"kfy",	newTag('K','M','N',' ')},	/* Kumaoni */
  {"kg",	newTag('K','O','N','0')},	/* Kongo [macrolanguage] */
  {"kge",	0	},	/* Komering != Khutsuri Georgian */
  {"kha",	newTag('K','S','I',' ')},	/* Khasi */
  {"khb",	newTag('X','B','D',' ')},	/* Lü */
  {"khk",	newTag('M','N','G',' ')},	/* Halh Mongolian -> Mongolian */
  {"khn",	0	},	/* Khandesi != Khamti Shan (Microsoft fonts) */
  {"khs",	0	},	/* Kasua != Khanty-Shurishkar */
  {"kht",	newTag('K','H','T',' ')},	/* Khamti -> Khamti Shan */
  {"kht",	newTag('K','H','N',' ')},	/* Khamti -> Khamti Shan (Microsoft fonts) */
  {"khv",	0	},	/* Khvarshi != Khanty-Vakhi */
/*{"khw",	newTag('K','H','W',' ')},*/	/* Khowar */
  {"ki",	newTag('K','I','K',' ')},	/* Kikuyu (Gikuyu) */
  {"kis",	0	},	/* Kis != Kisii */
  {"kiu",	newTag('K','I','U',' ')},	/* Kirmanjki */
  {"kiu",	newTag('Z','Z','A',' ')},	/* Kirmanjki -> Zazaki */
  {"kj",	newTag('K','U','A',' ')},	/* Kuanyama */
  {"kjb",	newTag('M','Y','N',' ')},	/* Q'anjob'al -> Mayan */
/*{"kjd",	newTag('K','J','D',' ')},*/	/* Southern Kiwai */
  {"kjh",	newTag('K','H','A',' ')},	/* Khakas -> Khakass */
  {"kjp",	newTag('K','J','P',' ')},	/* Pwo Eastern Karen -> Eastern Pwo Karen */
  {"kjp",	newTag('K','R','N',' ')},	/* Pwo Eastern Karen -> Karen */
  {"kjt",	newTag('K','R','N',' ')},	/* Phrae Pwo Karen -> Karen */
/*{"kjz",	newTag('K','J','Z',' ')},*/	/* Bumthangkha */
  {"kk",	newTag('K','A','Z',' ')},	/* Kazakh */
  {"kkn",	0	},	/* Kon Keu != Kokni */
  {"kkz",	newTag('A','T','H',' ')},	/* Kaska -> Athapaskan */
  {"kl",	newTag('G','R','N',' ')},	/* Greenlandic */
  {"klm",	0	},	/* Migum != Kalmyk */
  {"kln",	newTag('K','A','L',' ')},	/* Kalenjin [macrolanguage] */
  {"km",	newTag('K','H','M',' ')},	/* Khmer */
  {"kmb",	newTag('M','B','N',' ')},	/* Kimbundu -> Mbundu */
  {"kmn",	0	},	/* Awtuw != Kumaoni */
  {"kmo",	0	},	/* Kwoma != Komo */
  {"kmr",	newTag('K','U','R',' ')},	/* Northern Kurdish -> Kurdish */
  {"kms",	0	},	/* Kamasau != Komso */
  {"kmv",	newTag('C','P','P',' ')},	/* Karipúna Creole French -> Creoles */
  {"kmw",	newTag('K','M','O',' ')},	/* Komo (Democratic Republic of Congo) */
/*{"kmz",	newTag('K','M','Z',' ')},*/	/* Khorasani Turkish -> Khorasani Turkic */
  {"kn",	newTag('K','A','N',' ')},	/* Kannada */
  {"knc",	newTag('K','N','R',' ')},	/* Central Kanuri -> Kanuri */
  {"kng",	newTag('K','O','N','0')},	/* Koongo -> Kongo */
  {"knj",	newTag('M','Y','N',' ')},	/* Western Kanjobal -> Mayan */
  {"knn",	newTag('K','O','K',' ')},	/* Konkani */
  {"knr",	0	},	/* Kaningra != Kanuri */
  {"ko",	newTag('K','O','R',' ')},	/* Korean */
  {"ko",	newTag('K','O','H',' ')},	/* Korean -> Korean Old Hangul */
  {"kod",	0	},	/* Kodi != Kodagu */
  {"koh",	0	},	/* Koyo != Korean Old Hangul */
  {"koi",	newTag('K','O','P',' ')},	/* Komi-Permyak */
  {"koi",	newTag('K','O','M',' ')},	/* Komi-Permyak -> Komi */
/*{"kok",	newTag('K','O','K',' ')},*/	/* Konkani [macrolanguage] */
  {"kop",	0	},	/* Waube != Komi-Permyak */
/*{"kos",	newTag('K','O','S',' ')},*/	/* Kosraean */
  {"koy",	newTag('A','T','H',' ')},	/* Koyukon -> Athapaskan */
  {"koz",	0	},	/* Korak != Komi-Zyrian */
  {"kpe",	newTag('K','P','L',' ')},	/* Kpelle [macrolanguage] */
  {"kpl",	0	},	/* Kpala != Kpelle */
  {"kpp",	newTag('K','R','N',' ')},	/* Paku Karen (retired code) (retired code) -> Karen */
  {"kpv",	newTag('K','O','Z',' ')},	/* Komi-Zyrian */
  {"kpv",	newTag('K','O','M',' ')},	/* Komi-Zyrian -> Komi */
  {"kpy",	newTag('K','Y','K',' ')},	/* Koryak */
  {"kqs",	newTag('K','I','S',' ')},	/* Northern Kissi -> Kisii */
  {"kqy",	newTag('K','R','T',' ')},	/* Koorete */
  {"kr",	newTag('K','N','R',' ')},	/* Kanuri [macrolanguage] */
  {"krc",	newTag('K','A','R',' ')},	/* Karachay-Balkar -> Karachay */
  {"krc",	newTag('B','A','L',' ')},	/* Karachay-Balkar -> Balkar */
  {"kri",	newTag('K','R','I',' ')},	/* Krio */
  {"kri",	newTag('C','P','P',' ')},	/* Krio -> Creoles */
  {"krk",	0	},	/* Kerek != Karakalpak */
/*{"krl",	newTag('K','R','L',' ')},*/	/* Karelian */
  {"krm",	0	},	/* Krim (retired code) (retired code) != Karaim */
  {"krn",	0	},	/* Sapo != Karen */
  {"krt",	newTag('K','N','R',' ')},	/* Tumari Kanuri -> Kanuri */
  {"kru",	newTag('K','U','U',' ')},	/* Kurukh */
  {"ks",	newTag('K','S','H',' ')},	/* Kashmiri */
  {"ksh",	newTag('K','S','H','0')},	/* Kölsch -> Ripuarian */
  {"ksi",	0	},	/* Krisa != Khasi */
  {"ksm",	0	},	/* Kumba != Kildin Sami */
  {"kss",	newTag('K','I','S',' ')},	/* Southern Kisi -> Kisii */
  {"ksw",	newTag('K','S','W',' ')},	/* S’gaw Karen */
  {"ksw",	newTag('K','R','N',' ')},	/* S'gaw Karen -> Karen */
  {"ktb",	newTag('K','E','B',' ')},	/* Kambaata -> Kebena */
  {"ktu",	newTag('K','O','N',' ')},	/* Kituba (Democratic Republic of Congo) -> Kikongo */
  {"ktw",	newTag('A','T','H',' ')},	/* Kato -> Athapaskan */
  {"ku",	newTag('K','U','R',' ')},	/* Kurdish [macrolanguage] */
  {"kui",	0	},	/* Kuikúro-Kalapálo != Kui */
  {"kul",	0	},	/* Kulere != Kulvi */
/*{"kum",	newTag('K','U','M',' ')},*/	/* Kumyk */
  {"kuu",	newTag('A','T','H',' ')},	/* Upper Kuskokwim -> Athapaskan */
  {"kuw",	newTag('B','A','D','0')},	/* Kpagua -> Banda */
  {"kuy",	0	},	/* Kuuku-Ya'u != Kuy */
  {"kv",	newTag('K','O','M',' ')},	/* Komi [macrolanguage] */
  {"kvb",	newTag('M','L','Y',' ')},	/* Kubu -> Malay */
  {"kvl",	newTag('K','R','N',' ')},	/* Kayaw -> Karen */
  {"kvq",	newTag('K','R','N',' ')},	/* Geba Karen -> Karen */
  {"kvr",	newTag('M','L','Y',' ')},	/* Kerinci -> Malay */
  {"kvt",	newTag('K','R','N',' ')},	/* Lahta Karen -> Karen */
  {"kvu",	newTag('K','R','N',' ')},	/* Yinbaw Karen -> Karen */
  {"kvy",	newTag('K','R','N',' ')},	/* Yintale Karen -> Karen */
  {"kw",	newTag('C','O','R',' ')},	/* Cornish */
  {"kww",	newTag('C','P','P',' ')},	/* Kwinti -> Creoles */
  {"kwy",	newTag('K','O','N','0')},	/* San Salvador Kongo -> Kongo */
  {"kxc",	newTag('K','M','S',' ')},	/* Konso -> Komso */
  {"kxd",	newTag('M','L','Y',' ')},	/* Brunei -> Malay */
  {"kxf",	newTag('K','R','N',' ')},	/* Manumanaw Karen -> Karen */
  {"kxk",	newTag('K','R','N',' ')},	/* Zayein Karen -> Karen */
  {"kxl",	newTag('K','U','U',' ')},	/* Nepali Kurux (retired code) (retired code) -> Kurukh */
  {"kxu",	newTag('K','U','I',' ')},	/* Kui (India) (retired code) (retired code) */
  {"ky",	newTag('K','I','R',' ')},	/* Kirghiz (Kyrgyz) */
  {"kyk",	0	},	/* Kamayo != Koryak */
  {"kyu",	newTag('K','Y','U',' ')},	/* Western Kayah */
  {"kyu",	newTag('K','R','N',' ')},	/* Western Kayah -> Karen */
  {"la",	newTag('L','A','T',' ')},	/* Latin */
  {"lac",	newTag('M','Y','N',' ')},	/* Lacandon -> Mayan */
  {"lad",	newTag('J','U','D',' ')},	/* Ladino */
  {"lah",	0	},	/* Lahnda [macrolanguage] != Lahuli */
  {"lak",	0	},	/* Laka (Nigeria) != Lak */
  {"lam",	0	},	/* Lamba != Lambani */
  {"laz",	0	},	/* Aribwatsa != Laz */
  {"lb",	newTag('L','T','Z',' ')},	/* Luxembourgish */
  {"lbe",	newTag('L','A','K',' ')},	/* Lak */
  {"lbj",	newTag('L','D','K',' ')},	/* Ladakhi */
  {"lbl",	newTag('B','I','K',' ')},	/* Libon Bikol -> Bikol */
  {"lce",	newTag('M','L','Y',' ')},	/* Loncong -> Malay */
  {"lcf",	newTag('M','L','Y',' ')},	/* Lubu -> Malay */
  {"ldi",	newTag('K','O','N','0')},	/* Laari -> Kongo */
  {"ldk",	0	},	/* Leelau != Ladakhi */
/*{"lez",	newTag('L','E','Z',' ')},*/	/* Lezghian -> Lezgi */
  {"lg",	newTag('L','U','G',' ')},	/* Ganda */
  {"li",	newTag('L','I','M',' ')},	/* Limburgish */
  {"lif",	newTag('L','M','B',' ')},	/* Limbu */
/*{"lij",	newTag('L','I','J',' ')},*/	/* Ligurian */
  {"lir",	newTag('C','P','P',' ')},	/* Liberian English -> Creoles */
/*{"lis",	newTag('L','I','S',' ')},*/	/* Lisu */
  {"liw",	newTag('M','L','Y',' ')},	/* Col -> Malay */
  {"liy",	newTag('B','A','D','0')},	/* Banda-Bambari -> Banda */
/*{"ljp",	newTag('L','J','P',' ')},*/	/* Lampung Api -> Lampung */
  {"lkb",	newTag('L','U','H',' ')},	/* Kabras -> Luyia */
/*{"lki",	newTag('L','K','I',' ')},*/	/* Laki */
  {"lko",	newTag('L','U','H',' ')},	/* Khayo -> Luyia */
  {"lks",	newTag('L','U','H',' ')},	/* Kisa -> Luyia */
  {"lld",	newTag('L','A','D',' ')},	/* Ladin */
  {"lma",	0	},	/* East Limba != Low Mari */
  {"lmb",	0	},	/* Merei != Limbu */
  {"lmn",	newTag('L','A','M',' ')},	/* Lambadi -> Lambani */
/*{"lmo",	newTag('L','M','O',' ')},*/	/* Lombard */
  {"lmw",	0	},	/* Lake Miwok != Lomwe */
  {"ln",	newTag('L','I','N',' ')},	/* Lingala */
  {"lna",	newTag('B','A','D','0')},	/* Langbashe -> Banda */
  {"lnl",	newTag('B','A','D','0')},	/* South Central Banda -> Banda */
  {"lo",	newTag('L','A','O',' ')},	/* Lao */
/*{"lom",	newTag('L','O','M',' ')},*/	/* Loma (Liberia) */
  {"lou",	newTag('C','P','P',' ')},	/* Louisiana Creole -> Creoles */
/*{"lrc",	newTag('L','R','C',' ')},*/	/* Northern Luri -> Luri */
  {"lri",	newTag('L','U','H',' ')},	/* Marachi -> Luyia */
  {"lrm",	newTag('L','U','H',' ')},	/* Marama -> Luyia */
  {"lrt",	newTag('C','P','P',' ')},	/* Larantuka Malay -> Creoles */
  {"lsm",	newTag('L','U','H',' ')},	/* Saamia -> Luyia */
  {"lt",	newTag('L','T','H',' ')},	/* Lithuanian */
  {"ltg",	newTag('L','V','I',' ')},	/* Latgalian -> Latvian */
  {"lth",	0	},	/* Thur != Lithuanian */
  {"lto",	newTag('L','U','H',' ')},	/* Tsotso -> Luyia */
  {"lts",	newTag('L','U','H',' ')},	/* Tachoni -> Luyia */
  {"lu",	newTag('L','U','B',' ')},	/* Luba-Katanga */
/*{"lua",	newTag('L','U','A',' ')},*/	/* Luba-Lulua */
/*{"luo",	newTag('L','U','O',' ')},*/	/* Luo (Kenya and Tanzania) */
  {"lus",	newTag('M','I','Z',' ')},	/* Lushai -> Mizo */
  {"lus",	newTag('Q','I','N',' ')},	/* Lushai -> Chin */
  {"luy",	newTag('L','U','H',' ')},	/* Luyia [macrolanguage] */
  {"luz",	newTag('L','R','C',' ')},	/* Southern Luri -> Luri */
  {"lv",	newTag('L','V','I',' ')},	/* Latvian [macrolanguage] */
  {"lvi",	0	},	/* Lavi != Latvian */
  {"lvs",	newTag('L','V','I',' ')},	/* Standard Latvian -> Latvian */
  {"lwg",	newTag('L','U','H',' ')},	/* Wanga -> Luyia */
  {"lzh",	newTag('Z','H','T',' ')},	/* Literary Chinese -> Chinese, Traditional */
  {"lzz",	newTag('L','A','Z',' ')},	/* Laz */
/*{"mad",	newTag('M','A','D',' ')},*/	/* Madurese -> Madura */
/*{"mag",	newTag('M','A','G',' ')},*/	/* Magahi */
  {"mai",	newTag('M','T','H',' ')},	/* Maithili */
  {"maj",	0	},	/* Jalapa De Díaz Mazatec != Majang */
  {"mak",	newTag('M','K','R',' ')},	/* Makasar */
  {"mam",	newTag('M','A','M',' ')},	/* Mam */
  {"mam",	newTag('M','Y','N',' ')},	/* Mam -> Mayan */
  {"man",	newTag('M','N','K',' ')},	/* Mandingo [macrolanguage] -> Maninka */
  {"map",	0	},	/* Austronesian [family] != Mapudungun */
  {"maw",	0	},	/* Mampruli != Marwari */
  {"max",	newTag('M','L','Y',' ')},	/* North Moluccan Malay -> Malay */
  {"max",	newTag('C','P','P',' ')},	/* North Moluccan Malay -> Creoles */
  {"mbf",	newTag('C','P','P',' ')},	/* Baba Malay -> Creoles */
  {"mbn",	0	},	/* Macaguán != Mbundu */
/*{"mbo",	newTag('M','B','O',' ')},*/	/* Mbo (Cameroon) */
  {"mch",	0	},	/* Maquiritari != Manchu */
  {"mcm",	newTag('C','P','P',' ')},	/* Malaccan Creole Portuguese -> Creoles */
  {"mcr",	0	},	/* Menya != Moose Cree */
  {"mct",	newTag('B','T','I',' ')},	/* Mengisa -> Beti */
  {"mde",	0	},	/* Maba (Chad) != Mende */
  {"mdf",	newTag('M','O','K',' ')},	/* Moksha */
/*{"mdr",	newTag('M','D','R',' ')},*/	/* Mandar */
  {"mdy",	newTag('M','L','E',' ')},	/* Male (Ethiopia) */
  {"men",	newTag('M','D','E',' ')},	/* Mende (Sierra Leone) */
  {"meo",	newTag('M','L','Y',' ')},	/* Kedah Malay -> Malay */
/*{"mer",	newTag('M','E','R',' ')},*/	/* Meru */
  {"mfa",	newTag('M','F','A',' ')},	/* Pattani Malay */
  {"mfa",	newTag('M','L','Y',' ')},	/* Pattani Malay -> Malay */
  {"mfb",	newTag('M','L','Y',' ')},	/* Bangka -> Malay */
  {"mfe",	newTag('M','F','E',' ')},	/* Morisyen */
  {"mfe",	newTag('C','P','P',' ')},	/* Morisyen -> Creoles */
  {"mfp",	newTag('C','P','P',' ')},	/* Makassar Malay -> Creoles */
  {"mg",	newTag('M','L','G',' ')},	/* Malagasy [macrolanguage] */
  {"mh",	newTag('M','A','H',' ')},	/* Marshallese */
  {"mhc",	newTag('M','Y','N',' ')},	/* Mocho -> Mayan */
  {"mhr",	newTag('L','M','A',' ')},	/* Eastern Mari -> Low Mari */
  {"mhv",	newTag('A','R','K',' ')},	/* Arakanese (retired code) -> Rakhine */
  {"mi",	newTag('M','R','I',' ')},	/* Maori */
  {"min",	newTag('M','I','N',' ')},	/* Minangkabau */
  {"min",	newTag('M','L','Y',' ')},	/* Minangkabau -> Malay */
  {"miz",	0	},	/* Coatzospan Mixtec != Mizo */
  {"mk",	newTag('M','K','D',' ')},	/* Macedonian */
  {"mkn",	newTag('C','P','P',' ')},	/* Kupang Malay -> Creoles */
  {"mkr",	0	},	/* Malas != Makasar */
  {"mku",	newTag('M','N','K',' ')},	/* Konyanka Maninka -> Maninka */
/*{"mkw",	newTag('M','K','W',' ')},*/	/* Kituba (Congo) */
  {"ml",	newTag('M','A','L',' ')},	/* Malayalam -> Malayalam Traditional */
  {"ml",	newTag('M','L','R',' ')},	/* Malayalam -> Malayalam Reformed */
  {"mle",	0	},	/* Manambu != Male */
  {"mln",	0	},	/* Malango != Malinke */
  {"mlq",	newTag('M','L','N',' ')},	/* Western Maninkakan -> Malinke */
  {"mlq",	newTag('M','N','K',' ')},	/* Western Maninkakan -> Maninka */
  {"mlr",	0	},	/* Vame != Malayalam Reformed */
  {"mmr",	newTag('H','M','N',' ')},	/* Western Xiangxi Miao -> Hmong */
  {"mn",	newTag('M','N','G',' ')},	/* Mongolian [macrolanguage] */
  {"mnc",	newTag('M','C','H',' ')},	/* Manchu */
  {"mnd",	0	},	/* Mondé != Mandinka */
  {"mng",	0	},	/* Eastern Mnong != Mongolian */
  {"mnh",	newTag('B','A','D','0')},	/* Mono (Democratic Republic of Congo) -> Banda */
/*{"mni",	newTag('M','N','I',' ')},*/	/* Manipuri */
  {"mnk",	newTag('M','N','D',' ')},	/* Mandinka */
  {"mnk",	newTag('M','N','K',' ')},	/* Mandinka -> Maninka */
  {"mnp",	newTag('Z','H','S',' ')},	/* Min Bei Chinese -> Chinese, Simplified */
  {"mns",	newTag('M','A','N',' ')},	/* Mansi */
  {"mnw",	newTag('M','O','N',' ')},	/* Mon */
  {"mnx",	0	},	/* Manikion != Manx */
  {"mo",	newTag('M','O','L',' ')},	/* Moldavian (retired code) (retired code) */
  {"mod",	newTag('C','P','P',' ')},	/* Mobilian -> Creoles */
/*{"moh",	newTag('M','O','H',' ')},*/	/* Mohawk */
  {"mok",	0	},	/* Morori != Moksha */
  {"mop",	newTag('M','Y','N',' ')},	/* Mopán Maya -> Mayan */
/*{"mos",	newTag('M','O','S',' ')},*/	/* Mossi */
  {"mpe",	newTag('M','A','J',' ')},	/* Majang */
  {"mqg",	newTag('M','L','Y',' ')},	/* Kota Bangun Kutai Malay -> Malay */
  {"mr",	newTag('M','A','R',' ')},	/* Marathi */
  {"mrh",	newTag('Q','I','N',' ')},	/* Mara Chin -> Chin */
  {"mrj",	newTag('H','M','A',' ')},	/* Western Mari -> High Mari */
  {"ms",	newTag('M','L','Y',' ')},	/* Malay [macrolanguage] */
  {"msc",	newTag('M','N','K',' ')},	/* Sankaran Maninka -> Maninka */
  {"msh",	newTag('M','L','G',' ')},	/* Masikoro Malagasy -> Malagasy */
  {"msi",	newTag('M','L','Y',' ')},	/* Sabah Malay -> Malay */
  {"msi",	newTag('C','P','P',' ')},	/* Sabah Malay -> Creoles */
  {"mt",	newTag('M','T','S',' ')},	/* Maltese */
  {"mth",	0	},	/* Munggui != Maithili */
  {"mtr",	newTag('M','A','W',' ')},	/* Mewari -> Marwari */
  {"mts",	0	},	/* Yora != Maltese */
  {"mud",	newTag('C','P','P',' ')},	/* Mednyj Aleut -> Creoles */
  {"mui",	newTag('M','L','Y',' ')},	/* Musi -> Malay */
  {"mun",	0	},	/* Munda [family] != Mundari */
  {"mup",	newTag('R','A','J',' ')},	/* Malvi -> Rajasthani */
  {"muq",	newTag('H','M','N',' ')},	/* Eastern Xiangxi Miao -> Hmong */
/*{"mus",	newTag('M','U','S',' ')},*/	/* Creek -> Muscogee */
  {"mvb",	newTag('A','T','H',' ')},	/* Mattole -> Athapaskan */
  {"mve",	newTag('M','A','W',' ')},	/* Marwari (Pakistan) */
  {"mvf",	newTag('M','N','G',' ')},	/* Peripheral Mongolian -> Mongolian */
  {"mwk",	newTag('M','N','K',' ')},	/* Kita Maninkakan -> Maninka */
/*{"mwl",	newTag('M','W','L',' ')},*/	/* Mirandese */
  {"mwq",	newTag('Q','I','N',' ')},	/* Mün Chin -> Chin */
  {"mwr",	newTag('M','A','W',' ')},	/* Marwari [macrolanguage] */
  {"mww",	newTag('M','W','W',' ')},	/* Hmong Daw */
  {"mww",	newTag('H','M','N',' ')},	/* Hmong Daw -> Hmong */
  {"my",	newTag('B','R','M',' ')},	/* Burmese */
  {"mym",	newTag('M','E','N',' ')},	/* Me’en */
/*{"myn",	newTag('M','Y','N',' ')},*/	/* Mayan [family] */
  {"myq",	newTag('M','N','K',' ')},	/* Forest Maninka (retired code) (retired code) -> Maninka */
  {"myv",	newTag('E','R','Z',' ')},	/* Erzya */
  {"mzb",	newTag('B','B','R',' ')},	/* Tumzabt -> Berber */
/*{"mzn",	newTag('M','Z','N',' ')},*/	/* Mazanderani */
  {"mzs",	newTag('C','P','P',' ')},	/* Macanese -> Creoles */
  {"na",	newTag('N','A','U',' ')},	/* Nauru -> Nauruan */
  {"nag",	newTag('N','A','G',' ')},	/* Naga Pidgin -> Naga-Assamese */
  {"nag",	newTag('C','P','P',' ')},	/* Naga Pidgin -> Creoles */
/*{"nah",	newTag('N','A','H',' ')},*/	/* Nahuatl [family] */
  {"nan",	newTag('Z','H','S',' ')},	/* Min Nan Chinese -> Chinese, Simplified */
/*{"nap",	newTag('N','A','P',' ')},*/	/* Neapolitan */
  {"nas",	0	},	/* Naasioi != Naskapi */
  {"naz",	newTag('N','A','H',' ')},	/* Coatepec Nahuatl -> Nahuatl */
  {"nb",	newTag('N','O','R',' ')},	/* Norwegian Bokmål -> Norwegian */
  {"nch",	newTag('N','A','H',' ')},	/* Central Huasteca Nahuatl -> Nahuatl */
  {"nci",	newTag('N','A','H',' ')},	/* Classical Nahuatl -> Nahuatl */
  {"ncj",	newTag('N','A','H',' ')},	/* Northern Puebla Nahuatl -> Nahuatl */
  {"ncl",	newTag('N','A','H',' ')},	/* Michoacán Nahuatl -> Nahuatl */
  {"ncr",	0	},	/* Ncane != N-Cree */
  {"ncx",	newTag('N','A','H',' ')},	/* Central Puebla Nahuatl -> Nahuatl */
  {"nd",	newTag('N','D','B',' ')},	/* North Ndebele -> Ndebele */
  {"ndb",	0	},	/* Kenswei Nsei != Ndebele */
/*{"ndc",	newTag('N','D','C',' ')},*/	/* Ndau */
  {"ndg",	0	},	/* Ndengereko != Ndonga */
/*{"nds",	newTag('N','D','S',' ')},*/	/* Low Saxon */
  {"ne",	newTag('N','E','P',' ')},	/* Nepali [macrolanguage] */
  {"nef",	newTag('C','P','P',' ')},	/* Nefamese -> Creoles */
/*{"new",	newTag('N','E','W',' ')},*/	/* Newari */
  {"ng",	newTag('N','D','G',' ')},	/* Ndonga */
/*{"nga",	newTag('N','G','A',' ')},*/	/* Ngbaka */
  {"ngl",	newTag('L','M','W',' ')},	/* Lomwe */
  {"ngm",	newTag('C','P','P',' ')},	/* Ngatik Men's Creole -> Creoles */
  {"ngo",	newTag('S','X','T',' ')},	/* Ngoni -> Sutu */
  {"ngu",	newTag('N','A','H',' ')},	/* Guerrero Nahuatl -> Nahuatl */
  {"nhc",	newTag('N','A','H',' ')},	/* Tabasco Nahuatl -> Nahuatl */
  {"nhd",	newTag('G','U','A',' ')},	/* Chiripá -> Guarani */
  {"nhe",	newTag('N','A','H',' ')},	/* Eastern Huasteca Nahuatl -> Nahuatl */
  {"nhg",	newTag('N','A','H',' ')},	/* Tetelcingo Nahuatl -> Nahuatl */
  {"nhi",	newTag('N','A','H',' ')},	/* Zacatlán-Ahuacatlán-Tepetzintla Nahuatl -> Nahuatl */
  {"nhk",	newTag('N','A','H',' ')},	/* Isthmus-Cosoleacaque Nahuatl -> Nahuatl */
  {"nhm",	newTag('N','A','H',' ')},	/* Morelos Nahuatl -> Nahuatl */
  {"nhn",	newTag('N','A','H',' ')},	/* Central Nahuatl -> Nahuatl */
  {"nhp",	newTag('N','A','H',' ')},	/* Isthmus-Pajapan Nahuatl -> Nahuatl */
  {"nhq",	newTag('N','A','H',' ')},	/* Huaxcaleca Nahuatl -> Nahuatl */
  {"nht",	newTag('N','A','H',' ')},	/* Ometepec Nahuatl -> Nahuatl */
  {"nhv",	newTag('N','A','H',' ')},	/* Temascaltepec Nahuatl -> Nahuatl */
  {"nhw",	newTag('N','A','H',' ')},	/* Western Huasteca Nahuatl -> Nahuatl */
  {"nhx",	newTag('N','A','H',' ')},	/* Isthmus-Mecayapan Nahuatl -> Nahuatl */
  {"nhy",	newTag('N','A','H',' ')},	/* Northern Oaxaca Nahuatl -> Nahuatl */
  {"nhz",	newTag('N','A','H',' ')},	/* Santa María La Alta Nahuatl -> Nahuatl */
  {"niq",	newTag('K','A','L',' ')},	/* Nandi -> Kalenjin */
  {"nis",	0	},	/* Nimi != Nisi */
/*{"niu",	newTag('N','I','U',' ')},*/	/* Niuean */
  {"niv",	newTag('G','I','L',' ')},	/* Gilyak */
  {"njt",	newTag('C','P','P',' ')},	/* Ndyuka-Trio Pidgin -> Creoles */
  {"njz",	newTag('N','I','S',' ')},	/* Nyishi -> Nisi */
  {"nko",	0	},	/* Nkonya != N’Ko */
  {"nkx",	newTag('I','J','O',' ')},	/* Nkoroo -> Ijo */
  {"nl",	newTag('N','L','D',' ')},	/* Dutch */
  {"nla",	newTag('B','M','L',' ')},	/* Ngombale -> Bamileke */
  {"nle",	newTag('L','U','H',' ')},	/* East Nyala -> Luyia */
  {"nln",	newTag('N','A','H',' ')},	/* Durango Nahuatl (retired code) (retired code) -> Nahuatl */
  {"nlv",	newTag('N','A','H',' ')},	/* Orizaba Nahuatl -> Nahuatl */
  {"nn",	newTag('N','Y','N',' ')},	/* Norwegian Nynorsk (Nynorsk, Norwegian) */
  {"nn",	newTag('N','O','R',' ')},	/* Norwegian Nynorsk -> Norwegian */
  {"nnh",	newTag('B','M','L',' ')},	/* Ngiemboon -> Bamileke */
  {"nnz",	newTag('B','M','L',' ')},	/* Nda'nda' -> Bamileke */
  {"no",	newTag('N','O','R',' ')},	/* Norwegian [macrolanguage] */
  {"nod",	newTag('N','T','A',' ')},	/* Northern Thai -> Northern Tai */
/*{"noe",	newTag('N','O','E',' ')},*/	/* Nimadi */
/*{"nog",	newTag('N','O','G',' ')},*/	/* Nogai */
/*{"nov",	newTag('N','O','V',' ')},*/	/* Novial */
  {"npi",	newTag('N','E','P',' ')},	/* Nepali */
  {"npl",	newTag('N','A','H',' ')},	/* Southeastern Puebla Nahuatl -> Nahuatl */
  {"nqo",	newTag('N','K','O',' ')},	/* N’Ko */
  {"nr",	newTag('N','D','B',' ')},	/* South Ndebele -> Ndebele */
  {"nsk",	newTag('N','A','S',' ')},	/* Naskapi */
  {"nsm",	0	},	/* Sumi Naga != Northern Sami */
/*{"nso",	newTag('N','S','O',' ')},*/	/* Northern Sotho */
  {"nsu",	newTag('N','A','H',' ')},	/* Sierra Negra Nahuatl -> Nahuatl */
  {"nto",	0	},	/* Ntomba != Esperanto */
  {"nue",	newTag('B','A','D','0')},	/* Ngundu -> Banda */
  {"nuu",	newTag('B','A','D','0')},	/* Ngbundu -> Banda */
  {"nuz",	newTag('N','A','H',' ')},	/* Tlamacazapa Nahuatl -> Nahuatl */
  {"nv",	newTag('N','A','V',' ')},	/* Navajo */
  {"nv",	newTag('A','T','H',' ')},	/* Navajo -> Athapaskan */
  {"nwe",	newTag('B','M','L',' ')},	/* Ngwe -> Bamileke */
  {"ny",	newTag('C','H','I',' ')},	/* Chichewa (Chewa, Nyanja) */
  {"nyd",	newTag('L','U','H',' ')},	/* Nyore -> Luyia */
/*{"nym",	newTag('N','Y','M',' ')},*/	/* Nyamwezi */
  {"nyn",	newTag('N','K','L',' ')},	/* Nyankole */
/*{"nza",	newTag('N','Z','A',' ')},*/	/* Tigon Mbembe -> Mbembe Tigon */
  {"oc",	newTag('O','C','I',' ')},	/* Occitan (post 1500) */
  {"oj",	newTag('O','J','B',' ')},	/* Ojibwa [macrolanguage] -> Ojibway */
/*{"ojb",	newTag('O','J','B',' ')},*/	/* Northwestern Ojibwa -> Ojibway */
  {"ojc",	newTag('O','J','B',' ')},	/* Central Ojibwa -> Ojibway */
  {"ojg",	newTag('O','J','B',' ')},	/* Eastern Ojibwa -> Ojibway */
  {"ojs",	newTag('O','C','R',' ')},	/* Severn Ojibwa -> Oji-Cree */
  {"ojs",	newTag('O','J','B',' ')},	/* Severn Ojibwa -> Ojibway */
  {"ojw",	newTag('O','J','B',' ')},	/* Western Ojibwa -> Ojibway */
  {"okd",	newTag('I','J','O',' ')},	/* Okodia -> Ijo */
  {"oki",	newTag('K','A','L',' ')},	/* Okiek -> Kalenjin */
  {"okm",	newTag('K','O','H',' ')},	/* Middle Korean (10th-16th cent.) -> Korean Old Hangul */
  {"okr",	newTag('I','J','O',' ')},	/* Kirike -> Ijo */
  {"om",	newTag('O','R','O',' ')},	/* Oromo [macrolanguage] */
  {"onx",	newTag('C','P','P',' ')},	/* Onin Based Pidgin -> Creoles */
  {"oor",	newTag('C','P','P',' ')},	/* Oorlams -> Creoles */
  {"orc",	newTag('O','R','O',' ')},	/* Orma -> Oromo */
  {"orn",	newTag('M','L','Y',' ')},	/* Orang Kanaq -> Malay */
  {"oro",	0	},	/* Orokolo != Oromo */
  {"orr",	newTag('I','J','O',' ')},	/* Oruma -> Ijo */
  {"ors",	newTag('M','L','Y',' ')},	/* Orang Seletar -> Malay */
  {"os",	newTag('O','S','S',' ')},	/* Ossetian */
  {"otw",	newTag('O','J','B',' ')},	/* Ottawa -> Ojibway */
  {"oua",	newTag('B','B','R',' ')},	/* Tagargrent -> Berber */
  {"pa",	newTag('P','A','N',' ')},	/* Punjabi */
  {"paa",	0	},	/* Papuan [family] != Palestinian Aramaic */
/*{"pag",	newTag('P','A','G',' ')},*/	/* Pangasinan */
  {"pal",	0	},	/* Pahlavi != Pali */
/*{"pam",	newTag('P','A','M',' ')},*/	/* Pampanga -> Pampangan */
  {"pap",	newTag('P','A','P','0')},	/* Papiamento -> Papiamentu */
  {"pap",	newTag('C','P','P',' ')},	/* Papiamento -> Creoles */
  {"pas",	0	},	/* Papasena != Pashto */
/*{"pau",	newTag('P','A','U',' ')},*/	/* Palauan */
  {"pbt",	newTag('P','A','S',' ')},	/* Southern Pashto -> Pashto */
  {"pbu",	newTag('P','A','S',' ')},	/* Northern Pashto -> Pashto */
/*{"pcc",	newTag('P','C','C',' ')},*/	/* Bouyei */
/*{"pcd",	newTag('P','C','D',' ')},*/	/* Picard */
  {"pce",	newTag('P','L','G',' ')},	/* Ruching Palaung -> Palaung */
  {"pck",	newTag('Q','I','N',' ')},	/* Paite Chin -> Chin */
  {"pcm",	newTag('C','P','P',' ')},	/* Nigerian Pidgin -> Creoles */
/*{"pdc",	newTag('P','D','C',' ')},*/	/* Pennsylvania German */
  {"pdu",	newTag('K','R','N',' ')},	/* Kayan -> Karen */
  {"pea",	newTag('C','P','P',' ')},	/* Peranakan Indonesian -> Creoles */
  {"pel",	newTag('M','L','Y',' ')},	/* Pekal -> Malay */
  {"pes",	newTag('F','A','R',' ')},	/* Iranian Persian -> Persian */
  {"pey",	newTag('C','P','P',' ')},	/* Petjo -> Creoles */
  {"pga",	newTag('A','R','A',' ')},	/* Sudanese Creole Arabic -> Arabic */
  {"pga",	newTag('C','P','P',' ')},	/* Sudanese Creole Arabic -> Creoles */
/*{"phk",	newTag('P','H','K',' ')},*/	/* Phake */
  {"pi",	newTag('P','A','L',' ')},	/* Pali */
  {"pih",	newTag('P','I','H',' ')},	/* Pitcairn-Norfolk -> Norfolk */
  {"pih",	newTag('C','P','P',' ')},	/* Pitcairn-Norfolk -> Creoles */
  {"pil",	0	},	/* Yom != Filipino */
  {"pis",	newTag('C','P','P',' ')},	/* Pijin -> Creoles */
  {"pkh",	newTag('Q','I','N',' ')},	/* Pankhu -> Chin */
  {"pko",	newTag('K','A','L',' ')},	/* Pökoot -> Kalenjin */
  {"pl",	newTag('P','L','K',' ')},	/* Polish */
  {"plg",	0	},	/* Pilagá != Palaung */
  {"plk",	0	},	/* Kohistani Shina != Polish */
  {"pll",	newTag('P','L','G',' ')},	/* Shwe Palaung -> Palaung */
  {"pln",	newTag('C','P','P',' ')},	/* Palenquero -> Creoles */
  {"plp",	newTag('P','A','P',' ')},	/* Palpa (retired code) (retired code) */
  {"plt",	newTag('M','L','G',' ')},	/* Plateau Malagasy -> Malagasy */
  {"pml",	newTag('C','P','P',' ')},	/* Lingua Franca -> Creoles */
/*{"pms",	newTag('P','M','S',' ')},*/	/* Piemontese */
  {"pmy",	newTag('C','P','P',' ')},	/* Papuan Malay -> Creoles */
/*{"pnb",	newTag('P','N','B',' ')},*/	/* Western Panjabi */
  {"poc",	newTag('M','Y','N',' ')},	/* Poqomam -> Mayan */
  {"poh",	newTag('P','O','H',' ')},	/* Poqomchi' -> Pocomchi */
  {"poh",	newTag('M','Y','N',' ')},	/* Poqomchi' -> Mayan */
/*{"pon",	newTag('P','O','N',' ')},*/	/* Pohnpeian */
  {"pov",	newTag('C','P','P',' ')},	/* Upper Guinea Crioulo -> Creoles */
  {"ppa",	newTag('B','A','G',' ')},	/* Pao (retired code) (retired code) -> Baghelkhandi */
  {"pre",	newTag('C','P','P',' ')},	/* Principense -> Creoles */
/*{"pro",	newTag('P','R','O',' ')},*/	/* Old Provençal (to 1500) -> Provençal / Old Provençal */
  {"prs",	newTag('D','R','I',' ')},	/* Dari */
  {"prs",	newTag('F','A','R',' ')},	/* Dari -> Persian */
  {"ps",	newTag('P','A','S',' ')},	/* Pashto [macrolanguage] */
  {"pse",	newTag('M','L','Y',' ')},	/* Central Malay -> Malay */
  {"pst",	newTag('P','A','S',' ')},	/* Central Pashto -> Pashto */
  {"pt",	newTag('P','T','G',' ')},	/* Portuguese */
  {"pub",	newTag('Q','I','N',' ')},	/* Purum -> Chin */
  {"puz",	newTag('Q','I','N',' ')},	/* Purum Naga (retired code) (retired code) -> Chin */
  {"pwo",	newTag('P','W','O',' ')},	/* Pwo Western Karen -> Western Pwo Karen */
  {"pwo",	newTag('K','R','N',' ')},	/* Pwo Western Karen -> Karen */
  {"pww",	newTag('K','R','N',' ')},	/* Pwo Northern Karen -> Karen */
  {"qu",	newTag('Q','U','Z',' ')},	/* Quechua [macrolanguage] */
  {"qub",	newTag('Q','W','H',' ')},	/* Huallaga Huánuco Quechua -> Quechua (Peru) */
  {"qub",	newTag('Q','U','Z',' ')},	/* Huallaga Huánuco Quechua -> Quechua */
  {"quc",	newTag('Q','U','C',' ')},	/* K’iche’ */
  {"quc",	newTag('M','Y','N',' ')},	/* K'iche' -> Mayan */
  {"qud",	newTag('Q','V','I',' ')},	/* Calderón Highland Quichua -> Quechua (Ecuador) */
  {"qud",	newTag('Q','U','Z',' ')},	/* Calderón Highland Quichua -> Quechua */
  {"quf",	newTag('Q','U','Z',' ')},	/* Lambayeque Quechua -> Quechua */
  {"qug",	newTag('Q','V','I',' ')},	/* Chimborazo Highland Quichua -> Quechua (Ecuador) */
  {"qug",	newTag('Q','U','Z',' ')},	/* Chimborazo Highland Quichua -> Quechua */
  {"quh",	newTag('Q','U','H',' ')},	/* South Bolivian Quechua -> Quechua (Bolivia) */
  {"quh",	newTag('Q','U','Z',' ')},	/* South Bolivian Quechua -> Quechua */
  {"quk",	newTag('Q','U','Z',' ')},	/* Chachapoyas Quechua -> Quechua */
  {"qul",	newTag('Q','U','H',' ')},	/* North Bolivian Quechua -> Quechua (Bolivia) */
  {"qul",	newTag('Q','U','Z',' ')},	/* North Bolivian Quechua -> Quechua */
  {"qum",	newTag('M','Y','N',' ')},	/* Sipacapense -> Mayan */
  {"qup",	newTag('Q','V','I',' ')},	/* Southern Pastaza Quechua -> Quechua (Ecuador) */
  {"qup",	newTag('Q','U','Z',' ')},	/* Southern Pastaza Quechua -> Quechua */
  {"qur",	newTag('Q','W','H',' ')},	/* Yanahuanca Pasco Quechua -> Quechua (Peru) */
  {"qur",	newTag('Q','U','Z',' ')},	/* Yanahuanca Pasco Quechua -> Quechua */
  {"qus",	newTag('Q','U','H',' ')},	/* Santiago del Estero Quichua -> Quechua (Bolivia) */
  {"qus",	newTag('Q','U','Z',' ')},	/* Santiago del Estero Quichua -> Quechua */
  {"quv",	newTag('M','Y','N',' ')},	/* Sacapulteco -> Mayan */
  {"quw",	newTag('Q','V','I',' ')},	/* Tena Lowland Quichua -> Quechua (Ecuador) */
  {"quw",	newTag('Q','U','Z',' ')},	/* Tena Lowland Quichua -> Quechua */
  {"qux",	newTag('Q','W','H',' ')},	/* Yauyos Quechua -> Quechua (Peru) */
  {"qux",	newTag('Q','U','Z',' ')},	/* Yauyos Quechua -> Quechua */
  {"quy",	newTag('Q','U','Z',' ')},	/* Ayacucho Quechua -> Quechua */
/*{"quz",	newTag('Q','U','Z',' ')},*/	/* Cusco Quechua -> Quechua */
  {"qva",	newTag('Q','W','H',' ')},	/* Ambo-Pasco Quechua -> Quechua (Peru) */
  {"qva",	newTag('Q','U','Z',' ')},	/* Ambo-Pasco Quechua -> Quechua */
  {"qvc",	newTag('Q','U','Z',' ')},	/* Cajamarca Quechua -> Quechua */
  {"qve",	newTag('Q','U','Z',' ')},	/* Eastern Apurímac Quechua -> Quechua */
  {"qvh",	newTag('Q','W','H',' ')},	/* Huamalíes-Dos de Mayo Huánuco Quechua -> Quechua (Peru) */
  {"qvh",	newTag('Q','U','Z',' ')},	/* Huamalíes-Dos de Mayo Huánuco Quechua -> Quechua */
  {"qvi",	newTag('Q','V','I',' ')},	/* Imbabura Highland Quichua -> Quechua (Ecuador) */
  {"qvi",	newTag('Q','U','Z',' ')},	/* Imbabura Highland Quichua -> Quechua */
  {"qvj",	newTag('Q','V','I',' ')},	/* Loja Highland Quichua -> Quechua (Ecuador) */
  {"qvj",	newTag('Q','U','Z',' ')},	/* Loja Highland Quichua -> Quechua */
  {"qvl",	newTag('Q','W','H',' ')},	/* Cajatambo North Lima Quechua -> Quechua (Peru) */
  {"qvl",	newTag('Q','U','Z',' ')},	/* Cajatambo North Lima Quechua -> Quechua */
  {"qvm",	newTag('Q','W','H',' ')},	/* Margos-Yarowilca-Lauricocha Quechua -> Quechua (Peru) */
  {"qvm",	newTag('Q','U','Z',' ')},	/* Margos-Yarowilca-Lauricocha Quechua -> Quechua */
  {"qvn",	newTag('Q','W','H',' ')},	/* North Junín Quechua -> Quechua (Peru) */
  {"qvn",	newTag('Q','U','Z',' ')},	/* North Junín Quechua -> Quechua */
  {"qvo",	newTag('Q','V','I',' ')},	/* Napo Lowland Quechua -> Quechua (Ecuador) */
  {"qvo",	newTag('Q','U','Z',' ')},	/* Napo Lowland Quechua -> Quechua */
  {"qvp",	newTag('Q','W','H',' ')},	/* Pacaraos Quechua -> Quechua (Peru) */
  {"qvp",	newTag('Q','U','Z',' ')},	/* Pacaraos Quechua -> Quechua */
  {"qvs",	newTag('Q','U','Z',' ')},	/* San Martín Quechua -> Quechua */
  {"qvw",	newTag('Q','W','H',' ')},	/* Huaylla Wanca Quechua -> Quechua (Peru) */
  {"qvw",	newTag('Q','U','Z',' ')},	/* Huaylla Wanca Quechua -> Quechua */
  {"qvz",	newTag('Q','V','I',' ')},	/* Northern Pastaza Quichua -> Quechua (Ecuador) */
  {"qvz",	newTag('Q','U','Z',' ')},	/* Northern Pastaza Quichua -> Quechua */
  {"qwa",	newTag('Q','W','H',' ')},	/* Corongo Ancash Quechua -> Quechua (Peru) */
  {"qwa",	newTag('Q','U','Z',' ')},	/* Corongo Ancash Quechua -> Quechua */
  {"qwc",	newTag('Q','U','Z',' ')},	/* Classical Quechua -> Quechua */
  {"qwh",	newTag('Q','W','H',' ')},	/* Huaylas Ancash Quechua -> Quechua (Peru) */
  {"qwh",	newTag('Q','U','Z',' ')},	/* Huaylas Ancash Quechua -> Quechua */
  {"qws",	newTag('Q','W','H',' ')},	/* Sihuas Ancash Quechua -> Quechua (Peru) */
  {"qws",	newTag('Q','U','Z',' ')},	/* Sihuas Ancash Quechua -> Quechua */
  {"qwt",	newTag('A','T','H',' ')},	/* Kwalhioqua-Tlatskanai -> Athapaskan */
  {"qxa",	newTag('Q','W','H',' ')},	/* Chiquián Ancash Quechua -> Quechua (Peru) */
  {"qxa",	newTag('Q','U','Z',' ')},	/* Chiquián Ancash Quechua -> Quechua */
  {"qxc",	newTag('Q','W','H',' ')},	/* Chincha Quechua -> Quechua (Peru) */
  {"qxc",	newTag('Q','U','Z',' ')},	/* Chincha Quechua -> Quechua */
  {"qxh",	newTag('Q','W','H',' ')},	/* Panao Huánuco Quechua -> Quechua (Peru) */
  {"qxh",	newTag('Q','U','Z',' ')},	/* Panao Huánuco Quechua -> Quechua */
  {"qxl",	newTag('Q','V','I',' ')},	/* Salasaca Highland Quichua -> Quechua (Ecuador) */
  {"qxl",	newTag('Q','U','Z',' ')},	/* Salasaca Highland Quichua -> Quechua */
  {"qxn",	newTag('Q','W','H',' ')},	/* Northern Conchucos Ancash Quechua -> Quechua (Peru) */
  {"qxn",	newTag('Q','U','Z',' ')},	/* Northern Conchucos Ancash Quechua -> Quechua */
  {"qxo",	newTag('Q','W','H',' ')},	/* Southern Conchucos Ancash Quechua -> Quechua (Peru) */
  {"qxo",	newTag('Q','U','Z',' ')},	/* Southern Conchucos Ancash Quechua -> Quechua */
  {"qxp",	newTag('Q','U','Z',' ')},	/* Puno Quechua -> Quechua */
  {"qxr",	newTag('Q','V','I',' ')},	/* Cañar Highland Quichua -> Quechua (Ecuador) */
  {"qxr",	newTag('Q','U','Z',' ')},	/* Cañar Highland Quichua -> Quechua */
  {"qxt",	newTag('Q','W','H',' ')},	/* Santa Ana de Tusi Pasco Quechua -> Quechua (Peru) */
  {"qxt",	newTag('Q','U','Z',' ')},	/* Santa Ana de Tusi Pasco Quechua -> Quechua */
  {"qxu",	newTag('Q','U','Z',' ')},	/* Arequipa-La Unión Quechua -> Quechua */
  {"qxw",	newTag('Q','W','H',' ')},	/* Jauja Wanca Quechua -> Quechua (Peru) */
  {"qxw",	newTag('Q','U','Z',' ')},	/* Jauja Wanca Quechua -> Quechua */
  {"rag",	newTag('L','U','H',' ')},	/* Logooli -> Luyia */
/*{"raj",	newTag('R','A','J',' ')},*/	/* Rajasthani [macrolanguage] */
  {"ral",	newTag('Q','I','N',' ')},	/* Ralte -> Chin */
/*{"rar",	newTag('R','A','R',' ')},*/	/* Rarotongan */
  {"rbb",	newTag('P','L','G',' ')},	/* Rumai Palaung -> Palaung */
  {"rbl",	newTag('B','I','K',' ')},	/* Miraya Bikol -> Bikol */
  {"rcf",	newTag('C','P','P',' ')},	/* Réunion Creole French -> Creoles */
/*{"rej",	newTag('R','E','J',' ')},*/	/* Rejang */
/*{"ria",	newTag('R','I','A',' ')},*/	/* Riang (India) */
  {"rif",	newTag('R','I','F',' ')},	/* Tarifit */
  {"rif",	newTag('B','B','R',' ')},	/* Tarifit -> Berber */
/*{"rit",	newTag('R','I','T',' ')},*/	/* Ritharrngu -> Ritarungo */
  {"rki",	newTag('A','R','K',' ')},	/* Rakhine */
/*{"rkw",	newTag('R','K','W',' ')},*/	/* Arakwal */
  {"rm",	newTag('R','M','S',' ')},	/* Romansh */
  {"rmc",	newTag('R','O','Y',' ')},	/* Carpathian Romani -> Romany */
  {"rmf",	newTag('R','O','Y',' ')},	/* Kalo Finnish Romani -> Romany */
  {"rml",	newTag('R','O','Y',' ')},	/* Baltic Romani -> Romany */
  {"rmn",	newTag('R','O','Y',' ')},	/* Balkan Romani -> Romany */
  {"rmo",	newTag('R','O','Y',' ')},	/* Sinte Romani -> Romany */
  {"rms",	0	},	/* Romanian Sign Language != Romansh */
  {"rmw",	newTag('R','O','Y',' ')},	/* Welsh Romani -> Romany */
  {"rmy",	newTag('R','M','Y',' ')},	/* Vlax Romani */
  {"rmy",	newTag('R','O','Y',' ')},	/* Vlax Romani -> Romany */
  {"rmz",	newTag('A','R','K',' ')},	/* Marma -> Rakhine */
  {"rn",	newTag('R','U','N',' ')},	/* Rundi */
  {"ro",	newTag('R','O','M',' ')},	/* Romanian */
  {"rom",	newTag('R','O','Y',' ')},	/* Romany [macrolanguage] */
  {"rop",	newTag('C','P','P',' ')},	/* Kriol -> Creoles */
  {"rtc",	newTag('Q','I','N',' ')},	/* Rungtu Chin -> Chin */
/*{"rtm",	newTag('R','T','M',' ')},*/	/* Rotuman */
  {"ru",	newTag('R','U','S',' ')},	/* Russian */
  {"rue",	newTag('R','S','Y',' ')},	/* Rusyn */
/*{"rup",	newTag('R','U','P',' ')},*/	/* Aromanian */
  {"rw",	newTag('R','U','A',' ')},	/* Kinyarwanda */
  {"rwr",	newTag('M','A','W',' ')},	/* Marwari (India) */
  {"sa",	newTag('S','A','N',' ')},	/* Sanskrit */
  {"sad",	0	},	/* Sandawe != Sadri */
  {"sah",	newTag('Y','A','K',' ')},	/* Yakut -> Sakha */
  {"sam",	newTag('P','A','A',' ')},	/* Samaritan Aramaic -> Palestinian Aramaic */
/*{"sas",	newTag('S','A','S',' ')},*/	/* Sasak */
/*{"sat",	newTag('S','A','T',' ')},*/	/* Santali */
  {"say",	0	},	/* Saya != Sayisi */
  {"sc",	newTag('S','R','D',' ')},	/* Sardinian [macrolanguage] */
  {"scf",	newTag('C','P','P',' ')},	/* San Miguel Creole French -> Creoles */
  {"sch",	newTag('Q','I','N',' ')},	/* Sakachep -> Chin */
  {"sci",	newTag('C','P','P',' ')},	/* Sri Lankan Creole Malay -> Creoles */
  {"sck",	newTag('S','A','D',' ')},	/* Sadri */
/*{"scn",	newTag('S','C','N',' ')},*/	/* Sicilian */
/*{"sco",	newTag('S','C','O',' ')},*/	/* Scots */
  {"scs",	newTag('S','C','S',' ')},	/* North Slavey */
  {"scs",	newTag('S','L','A',' ')},	/* North Slavey -> Slavey */
  {"scs",	newTag('A','T','H',' ')},	/* North Slavey -> Athapaskan */
  {"sd",	newTag('S','N','D',' ')},	/* Sindhi */
  {"sdc",	newTag('S','R','D',' ')},	/* Sassarese Sardinian -> Sardinian */
  {"sdh",	newTag('K','U','R',' ')},	/* Southern Kurdish -> Kurdish */
  {"sdn",	newTag('S','R','D',' ')},	/* Gallurese Sardinian -> Sardinian */
  {"sds",	newTag('B','B','R',' ')},	/* Sened -> Berber */
  {"se",	newTag('N','S','M',' ')},	/* Northern Sami */
  {"seh",	newTag('S','N','A',' ')},	/* Sena */
  {"sek",	newTag('A','T','H',' ')},	/* Sekani -> Athapaskan */
/*{"sel",	newTag('S','E','L',' ')},*/	/* Selkup */
  {"sez",	newTag('Q','I','N',' ')},	/* Senthang Chin -> Chin */
  {"sfm",	newTag('H','M','N',' ')},	/* Small Flowery Miao -> Hmong */
  {"sg",	newTag('S','G','O',' ')},	/* Sango */
/*{"sga",	newTag('S','G','A',' ')},*/	/* Old Irish (to 900) */
  {"sgc",	newTag('K','A','L',' ')},	/* Kipsigis -> Kalenjin */
  {"sgo",	0	},	/* Songa (retired code) (retired code) != Sango */
/*{"sgs",	newTag('S','G','S',' ')},*/	/* Samogitian */
  {"sgw",	newTag('C','H','G',' ')},	/* Sebat Bet Gurage -> Chaha Gurage */
  {"shi",	newTag('S','H','I',' ')},	/* Tachelhit */
  {"shi",	newTag('B','B','R',' ')},	/* Tachelhit -> Berber */
  {"shl",	newTag('Q','I','N',' ')},	/* Shendu -> Chin */
/*{"shn",	newTag('S','H','N',' ')},*/	/* Shan */
  {"shu",	newTag('A','R','A',' ')},	/* Chadian Arabic -> Arabic */
  {"shy",	newTag('B','B','R',' ')},	/* Tachawit -> Berber */
  {"si",	newTag('S','N','H',' ')},	/* Sinhala (Sinhalese) */
  {"sib",	0	},	/* Sebop != Sibe */
/*{"sid",	newTag('S','I','D',' ')},*/	/* Sidamo */
  {"sig",	0	},	/* Paasaal != Silte Gurage */
  {"siz",	newTag('B','B','R',' ')},	/* Siwi -> Berber */
  {"sjd",	newTag('K','S','M',' ')},	/* Kildin Sami */
  {"sjo",	newTag('S','I','B',' ')},	/* Xibe -> Sibe */
  {"sjs",	newTag('B','B','R',' ')},	/* Senhaja De Srair -> Berber */
  {"sk",	newTag('S','K','Y',' ')},	/* Slovak */
  {"skg",	newTag('M','L','G',' ')},	/* Sakalava Malagasy -> Malagasy */
  {"skr",	newTag('S','R','K',' ')},	/* Saraiki */
  {"sks",	0	},	/* Maia != Skolt Sami */
  {"skw",	newTag('C','P','P',' ')},	/* Skepi Creole Dutch -> Creoles */
  {"sky",	0	},	/* Sikaiana != Slovak */
  {"sl",	newTag('S','L','V',' ')},	/* Slovenian */
  {"sla",	0	},	/* Slavic [family] != Slavey */
  {"sm",	newTag('S','M','O',' ')},	/* Samoan */
  {"sma",	newTag('S','S','M',' ')},	/* Southern Sami */
  {"smj",	newTag('L','S','M',' ')},	/* Lule Sami */
  {"sml",	0	},	/* Central Sama != Somali */
  {"smn",	newTag('I','S','M',' ')},	/* Inari Sami */
  {"sms",	newTag('S','K','S',' ')},	/* Skolt Sami */
  {"smt",	newTag('Q','I','N',' ')},	/* Simte -> Chin */
  {"sn",	newTag('S','N','A','0')},	/* Shona */
  {"snh",	0	},	/* Shinabo (retired code) (retired code) != Sinhala (Sinhalese) */
/*{"snk",	newTag('S','N','K',' ')},*/	/* Soninke */
  {"so",	newTag('S','M','L',' ')},	/* Somali */
  {"sog",	0	},	/* Sogdian != Sodo Gurage */
/*{"sop",	newTag('S','O','P',' ')},*/	/* Songe */
  {"spy",	newTag('K','A','L',' ')},	/* Sabaot -> Kalenjin */
  {"sq",	newTag('S','Q','I',' ')},	/* Albanian [macrolanguage] */
  {"sr",	newTag('S','R','B',' ')},	/* Serbian */
  {"srb",	0	},	/* Sora != Serbian */
  {"src",	newTag('S','R','D',' ')},	/* Logudorese Sardinian -> Sardinian */
  {"srk",	0	},	/* Serudung Murut != Saraiki */
  {"srm",	newTag('C','P','P',' ')},	/* Saramaccan -> Creoles */
  {"srn",	newTag('C','P','P',' ')},	/* Sranan Tongo -> Creoles */
  {"sro",	newTag('S','R','D',' ')},	/* Campidanese Sardinian -> Sardinian */
/*{"srr",	newTag('S','R','R',' ')},*/	/* Serer */
  {"srs",	newTag('A','T','H',' ')},	/* Sarsi -> Athapaskan */
  {"ss",	newTag('S','W','Z',' ')},	/* Swati */
  {"ssh",	newTag('A','R','A',' ')},	/* Shihhi Arabic -> Arabic */
  {"ssl",	0	},	/* Western Sisaala != South Slavey */
  {"ssm",	0	},	/* Semnam != Southern Sami */
  {"st",	newTag('S','O','T',' ')},	/* Southern Sotho */
  {"sta",	newTag('C','P','P',' ')},	/* Settla -> Creoles */
/*{"stq",	newTag('S','T','Q',' ')},*/	/* Saterfriesisch -> Saterland Frisian */
  {"stv",	newTag('S','I','G',' ')},	/* Silt'e -> Silte Gurage */
  {"su",	newTag('S','U','N',' ')},	/* Sundanese */
/*{"suk",	newTag('S','U','K',' ')},*/	/* Sukuma */
  {"suq",	newTag('S','U','R',' ')},	/* Suri */
  {"sur",	0	},	/* Mwaghavul != Suri */
  {"sv",	newTag('S','V','E',' ')},	/* Swedish */
/*{"sva",	newTag('S','V','A',' ')},*/	/* Svan */
  {"svc",	newTag('C','P','P',' ')},	/* Vincentian Creole English -> Creoles */
  {"sve",	0	},	/* Serili != Swedish */
  {"sw",	newTag('S','W','K',' ')},	/* Swahili [macrolanguage] */
  {"swb",	newTag('C','M','R',' ')},	/* Maore Comorian -> Comorian */
  {"swc",	newTag('S','W','K',' ')},	/* Congo Swahili -> Swahili */
  {"swh",	newTag('S','W','K',' ')},	/* Swahili */
  {"swk",	0	},	/* Malawi Sena != Swahili */
  {"swn",	newTag('B','B','R',' ')},	/* Sawknah -> Berber */
  {"swv",	newTag('M','A','W',' ')},	/* Shekhawati -> Marwari */
/*{"sxu",	newTag('S','X','U',' ')},*/	/* Upper Saxon */
  {"syc",	newTag('S','Y','R',' ')},	/* Classical Syriac -> Syriac */
/*{"syl",	newTag('S','Y','L',' ')},*/	/* Sylheti */
/*{"syr",	newTag('S','Y','R',' ')},*/	/* Syriac [macrolanguage] */
/*{"szl",	newTag('S','Z','L',' ')},*/	/* Silesian */
  {"ta",	newTag('T','A','M',' ')},	/* Tamil */
  {"taa",	newTag('A','T','H',' ')},	/* Lower Tanana -> Athapaskan */
/*{"tab",	newTag('T','A','B',' ')},*/	/* Tabassaran -> Tabasaran */
  {"taj",	0	},	/* Eastern Tamang != Tajiki */
  {"taq",	newTag('T','M','H',' ')},	/* Tamasheq -> Tamashek */
  {"taq",	newTag('B','B','R',' ')},	/* Tamasheq -> Berber */
  {"tas",	newTag('C','P','P',' ')},	/* Tay Boi -> Creoles */
  {"tau",	newTag('A','T','H',' ')},	/* Upper Tanana -> Athapaskan */
  {"tcb",	newTag('A','T','H',' ')},	/* Tanacross -> Athapaskan */
  {"tce",	newTag('A','T','H',' ')},	/* Southern Tutchone -> Athapaskan */
  {"tch",	newTag('C','P','P',' ')},	/* Turks And Caicos Creole English -> Creoles */
  {"tcp",	newTag('Q','I','N',' ')},	/* Tawr Chin -> Chin */
  {"tcs",	newTag('C','P','P',' ')},	/* Torres Strait Creole -> Creoles */
  {"tcy",	newTag('T','U','L',' ')},	/* Tulu -> Tumbuka */
  {"tcz",	newTag('Q','I','N',' ')},	/* Thado Chin -> Chin */
/*{"tdd",	newTag('T','D','D',' ')},*/	/* Tai Nüa -> Dehong Dai */
  {"tdx",	newTag('M','L','G',' ')},	/* Tandroy-Mahafaly Malagasy -> Malagasy */
  {"te",	newTag('T','E','L',' ')},	/* Telugu */
  {"tec",	newTag('K','A','L',' ')},	/* Terik -> Kalenjin */
  {"tem",	newTag('T','M','N',' ')},	/* Timne -> Temne */
/*{"tet",	newTag('T','E','T',' ')},*/	/* Tetum */
  {"tez",	newTag('B','B','R',' ')},	/* Tetserret -> Berber */
  {"tfn",	newTag('A','T','H',' ')},	/* Tanaina -> Athapaskan */
  {"tg",	newTag('T','A','J',' ')},	/* Tajik -> Tajiki */
  {"tgh",	newTag('C','P','P',' ')},	/* Tobagonian Creole English -> Creoles */
  {"tgj",	newTag('N','I','S',' ')},	/* Tagin -> Nisi */
  {"tgn",	0	},	/* Tandaganon != Tongan */
  {"tgr",	0	},	/* Tareng != Tigre */
  {"tgx",	newTag('A','T','H',' ')},	/* Tagish -> Athapaskan */
  {"tgy",	0	},	/* Togoyo != Tigrinya */
  {"th",	newTag('T','H','A',' ')},	/* Thai */
  {"tht",	newTag('A','T','H',' ')},	/* Tahltan -> Athapaskan */
  {"thv",	newTag('T','M','H',' ')},	/* Tahaggart Tamahaq -> Tamashek */
  {"thv",	newTag('B','B','R',' ')},	/* Tahaggart Tamahaq -> Berber */
  {"thz",	newTag('T','M','H',' ')},	/* Tayart Tamajeq -> Tamashek */
  {"thz",	newTag('B','B','R',' ')},	/* Tayart Tamajeq -> Berber */
  {"ti",	newTag('T','G','Y',' ')},	/* Tigrinya */
  {"tia",	newTag('B','B','R',' ')},	/* Tidikelt Tamazight -> Berber */
  {"tig",	newTag('T','G','R',' ')},	/* Tigre */
/*{"tiv",	newTag('T','I','V',' ')},*/	/* Tiv */
  {"tjo",	newTag('B','B','R',' ')},	/* Temacine Tamazight -> Berber */
  {"tk",	newTag('T','K','M',' ')},	/* Turkmen */
  {"tkg",	newTag('M','L','G',' ')},	/* Tesaka Malagasy -> Malagasy */
  {"tkm",	0	},	/* Takelma != Turkmen */
  {"tl",	newTag('T','G','L',' ')},	/* Tagalog */
  {"tmg",	newTag('C','P','P',' ')},	/* Ternateño -> Creoles */
  {"tmh",	newTag('T','M','H',' ')},	/* Tamashek [macrolanguage] */
  {"tmh",	newTag('B','B','R',' ')},	/* Tamashek [macrolanguage] -> Berber */
  {"tmn",	0	},	/* Taman (Indonesia) != Temne */
  {"tmw",	newTag('M','L','Y',' ')},	/* Temuan -> Malay */
  {"tn",	newTag('T','N','A',' ')},	/* Tswana */
  {"tna",	0	},	/* Tacana != Tswana */
  {"tne",	0	},	/* Tinoc Kallahan (retired code) (retired code) != Tundra Enets */
  {"tnf",	newTag('D','R','I',' ')},	/* Tangshewi (retired code) (retired code) -> Dari */
  {"tnf",	newTag('F','A','R',' ')},	/* Tangshewi (retired code) (retired code) -> Persian */
  {"tng",	0	},	/* Tobanga != Tonga */
  {"to",	newTag('T','G','N',' ')},	/* Tonga (Tonga Islands) -> Tongan */
  {"tod",	newTag('T','O','D','0')},	/* Toma */
  {"toi",	newTag('T','N','G',' ')},	/* Tonga (Zambia) */
  {"toj",	newTag('M','Y','N',' ')},	/* Tojolabal -> Mayan */
  {"tol",	newTag('A','T','H',' ')},	/* Tolowa -> Athapaskan */
  {"tor",	newTag('B','A','D','0')},	/* Togbo-Vara Banda -> Banda */
  {"tpi",	newTag('T','P','I',' ')},	/* Tok Pisin */
  {"tpi",	newTag('C','P','P',' ')},	/* Tok Pisin -> Creoles */
  {"tr",	newTag('T','R','K',' ')},	/* Turkish */
  {"trf",	newTag('C','P','P',' ')},	/* Trinidadian Creole English -> Creoles */
  {"trk",	0	},	/* Turkic [family] != Turkish */
  {"tru",	newTag('T','U','A',' ')},	/* Turoyo -> Turoyo Aramaic */
  {"tru",	newTag('S','Y','R',' ')},	/* Turoyo -> Syriac */
  {"ts",	newTag('T','S','G',' ')},	/* Tsonga */
  {"tsg",	0	},	/* Tausug != Tsonga */
/*{"tsj",	newTag('T','S','J',' ')},*/	/* Tshangla */
  {"tt",	newTag('T','A','T',' ')},	/* Tatar */
  {"ttc",	newTag('M','Y','N',' ')},	/* Tektiteko -> Mayan */
  {"ttm",	newTag('A','T','H',' ')},	/* Northern Tutchone -> Athapaskan */
  {"ttq",	newTag('T','M','H',' ')},	/* Tawallammat Tamajaq -> Tamashek */
  {"ttq",	newTag('B','B','R',' ')},	/* Tawallammat Tamajaq -> Berber */
  {"tua",	0	},	/* Wiarumus != Turoyo Aramaic */
  {"tul",	0	},	/* Tula != Tumbuka */
/*{"tum",	newTag('T','U','M',' ')},*/	/* Tumbuka -> Tulu */
  {"tuu",	newTag('A','T','H',' ')},	/* Tututni -> Athapaskan */
  {"tuv",	0	},	/* Turkana != Tuvin */
  {"tuy",	newTag('K','A','L',' ')},	/* Tugen -> Kalenjin */
/*{"tvl",	newTag('T','V','L',' ')},*/	/* Tuvalu */
  {"tvy",	newTag('C','P','P',' ')},	/* Timor Pidgin -> Creoles */
  {"tw",	newTag('T','W','I',' ')},	/* Twi */
  {"tw",	newTag('A','K','A',' ')},	/* Twi -> Akan */
  {"txc",	newTag('A','T','H',' ')},	/* Tsetsaut -> Athapaskan */
  {"txy",	newTag('M','L','G',' ')},	/* Tanosy Malagasy -> Malagasy */
  {"ty",	newTag('T','H','T',' ')},	/* Tahitian */
  {"tyv",	newTag('T','U','V',' ')},	/* Tuvinian -> Tuvin */
/*{"tyz",	newTag('T','Y','Z',' ')},*/	/* Tày */
  {"tzh",	newTag('M','Y','N',' ')},	/* Tzeltal -> Mayan */
  {"tzj",	newTag('M','Y','N',' ')},	/* Tz'utujil -> Mayan */
  {"tzm",	newTag('T','Z','M',' ')},	/* Central Atlas Tamazight -> Tamazight */
  {"tzm",	newTag('B','B','R',' ')},	/* Central Atlas Tamazight -> Berber */
  {"tzo",	newTag('T','Z','O',' ')},	/* Tzotzil */
  {"tzo",	newTag('M','Y','N',' ')},	/* Tzotzil -> Mayan */
  {"ubl",	newTag('B','I','K',' ')},	/* Buhi'non Bikol -> Bikol */
/*{"udm",	newTag('U','D','M',' ')},*/	/* Udmurt */
  {"ug",	newTag('U','Y','G',' ')},	/* Uyghur */
  {"uk",	newTag('U','K','R',' ')},	/* Ukrainian */
  {"uki",	newTag('K','U','I',' ')},	/* Kui (India) */
  {"uln",	newTag('C','P','P',' ')},	/* Unserdeutsch -> Creoles */
/*{"umb",	newTag('U','M','B',' ')},*/	/* Umbundu */
  {"unr",	newTag('M','U','N',' ')},	/* Mundari */
  {"ur",	newTag('U','R','D',' ')},	/* Urdu */
  {"urk",	newTag('M','L','Y',' ')},	/* Urak Lawoi' -> Malay */
  {"usp",	newTag('M','Y','N',' ')},	/* Uspanteco -> Mayan */
  {"uz",	newTag('U','Z','B',' ')},	/* Uzbek [macrolanguage] */
  {"uzn",	newTag('U','Z','B',' ')},	/* Northern Uzbek -> Uzbek */
  {"uzs",	newTag('U','Z','B',' ')},	/* Southern Uzbek -> Uzbek */
  {"vap",	newTag('Q','I','N',' ')},	/* Vaiphei -> Chin */
  {"ve",	newTag('V','E','N',' ')},	/* Venda */
/*{"vec",	newTag('V','E','C',' ')},*/	/* Venetian */
  {"vi",	newTag('V','I','T',' ')},	/* Vietnamese */
  {"vic",	newTag('C','P','P',' ')},	/* Virgin Islands Creole English -> Creoles */
  {"vit",	0	},	/* Viti != Vietnamese */
  {"vkk",	newTag('M','L','Y',' ')},	/* Kaur -> Malay */
  {"vkp",	newTag('C','P','P',' ')},	/* Korlai Creole Portuguese -> Creoles */
  {"vkt",	newTag('M','L','Y',' ')},	/* Tenggarong Kutai Malay -> Malay */
  {"vls",	newTag('F','L','E',' ')},	/* Vlaams -> Dutch (Flemish) */
  {"vmw",	newTag('M','A','K',' ')},	/* Makhuwa */
  {"vo",	newTag('V','O','L',' ')},	/* Volapük */
/*{"vro",	newTag('V','R','O',' ')},*/	/* Võro */
  {"wa",	newTag('W','L','N',' ')},	/* Walloon */
  {"wag",	0	},	/* Wa'ema != Wagdi */
/*{"war",	newTag('W','A','R',' ')},*/	/* Waray (Philippines) -> Waray-Waray */
  {"wbm",	newTag('W','A',' ',' ')},	/* Wa */
  {"wbr",	newTag('W','A','G',' ')},	/* Wagdi */
  {"wbr",	newTag('R','A','J',' ')},	/* Wagdi -> Rajasthani */
  {"wea",	newTag('K','R','N',' ')},	/* Wewaw -> Karen */
  {"wes",	newTag('C','P','P',' ')},	/* Cameroon Pidgin -> Creoles */
  {"weu",	newTag('Q','I','N',' ')},	/* Rawngtu Chin -> Chin */
  {"wlc",	newTag('C','M','R',' ')},	/* Mwali Comorian -> Comorian */
  {"wle",	newTag('S','I','G',' ')},	/* Wolane -> Silte Gurage */
  {"wlk",	newTag('A','T','H',' ')},	/* Wailaki -> Athapaskan */
  {"wni",	newTag('C','M','R',' ')},	/* Ndzwani Comorian -> Comorian */
  {"wo",	newTag('W','L','F',' ')},	/* Wolof */
  {"wry",	newTag('M','A','W',' ')},	/* Merwari -> Marwari */
  {"wsg",	newTag('G','O','N',' ')},	/* Adilabad Gondi -> Gondi */
/*{"wtm",	newTag('W','T','M',' ')},*/	/* Mewati */
  {"wuu",	newTag('Z','H','S',' ')},	/* Wu Chinese -> Chinese, Simplified */
  {"xal",	newTag('K','L','M',' ')},	/* Kalmyk */
  {"xal",	newTag('T','O','D',' ')},	/* Kalmyk -> Todo */
  {"xan",	newTag('S','E','K',' ')},	/* Xamtanga -> Sekota */
  {"xbd",	0	},	/* Bindal != Lü */
  {"xh",	newTag('X','H','S',' ')},	/* Xhosa */
/*{"xjb",	newTag('X','J','B',' ')},*/	/* Minjungbal -> Minjangbal */
/*{"xkf",	newTag('X','K','F',' ')},*/	/* Khengkha */
  {"xmg",	newTag('B','M','L',' ')},	/* Mengaka -> Bamileke */
  {"xmm",	newTag('M','L','Y',' ')},	/* Manado Malay -> Malay */
  {"xmm",	newTag('C','P','P',' ')},	/* Manado Malay -> Creoles */
  {"xmv",	newTag('M','L','G',' ')},	/* Antankarana Malagasy -> Malagasy */
  {"xmw",	newTag('M','L','G',' ')},	/* Tsimihety Malagasy -> Malagasy */
  {"xnr",	newTag('D','G','R',' ')},	/* Kangri -> Dogri (macrolanguage) */
/*{"xog",	newTag('X','O','G',' ')},*/	/* Soga */
  {"xpe",	newTag('X','P','E',' ')},	/* Liberia Kpelle -> Kpelle (Liberia) */
  {"xpe",	newTag('K','P','L',' ')},	/* Liberia Kpelle -> Kpelle */
  {"xsl",	newTag('S','S','L',' ')},	/* South Slavey */
  {"xsl",	newTag('S','L','A',' ')},	/* South Slavey -> Slavey */
  {"xsl",	newTag('A','T','H',' ')},	/* South Slavey -> Athapaskan */
  {"xst",	newTag('S','I','G',' ')},	/* Silt'e (retired code) -> Silte Gurage */
  {"xup",	newTag('A','T','H',' ')},	/* Upper Umpqua -> Athapaskan */
  {"xwo",	newTag('T','O','D',' ')},	/* Written Oirat -> Todo */
  {"yaj",	newTag('B','A','D','0')},	/* Banda-Yangere -> Banda */
  {"yak",	0	},	/* Yakama != Sakha */
/*{"yao",	newTag('Y','A','O',' ')},*/	/* Yao */
/*{"yap",	newTag('Y','A','P',' ')},*/	/* Yapese */
  {"yba",	0	},	/* Yala != Yoruba */
  {"ybb",	newTag('B','M','L',' ')},	/* Yemba -> Bamileke */
  {"ybd",	newTag('A','R','K',' ')},	/* Yangbye (retired code) (retired code) -> Rakhine */
  {"ydd",	newTag('J','I','I',' ')},	/* Eastern Yiddish -> Yiddish */
  {"yi",	newTag('J','I','I',' ')},	/* Yiddish [macrolanguage] */
  {"yih",	newTag('J','I','I',' ')},	/* Western Yiddish -> Yiddish */
  {"yim",	0	},	/* Yimchungru Naga != Yi Modern */
  {"yo",	newTag('Y','B','A',' ')},	/* Yoruba */
  {"yos",	newTag('Q','I','N',' ')},	/* Yos (retired code) (retired code) -> Chin */
  {"yua",	newTag('M','Y','N',' ')},	/* Yucateco -> Mayan */
  {"yue",	newTag('Z','H','H',' ')},	/* Yue Chinese -> Chinese, Traditional, Hong Kong SAR */
  {"za",	newTag('Z','H','A',' ')},	/* Zhuang [macrolanguage] */
  {"zch",	newTag('Z','H','A',' ')},	/* Central Hongshuihe Zhuang -> Zhuang */
  {"zdj",	newTag('C','M','R',' ')},	/* Ngazidja Comorian -> Comorian */
/*{"zea",	newTag('Z','E','A',' ')},*/	/* Zeeuws -> Zealandic */
  {"zeh",	newTag('Z','H','A',' ')},	/* Eastern Hongshuihe Zhuang -> Zhuang */
  {"zen",	newTag('B','B','R',' ')},	/* Zenaga -> Berber */
  {"zgb",	newTag('Z','H','A',' ')},	/* Guibei Zhuang -> Zhuang */
  {"zgh",	newTag('Z','G','H',' ')},	/* Standard Moroccan Tamazight */
  {"zgh",	newTag('B','B','R',' ')},	/* Standard Moroccan Tamazight -> Berber */
  {"zgm",	newTag('Z','H','A',' ')},	/* Minz Zhuang -> Zhuang */
  {"zgn",	newTag('Z','H','A',' ')},	/* Guibian Zhuang -> Zhuang */
  {"zh",	newTag('Z','H','S',' ')},	/* Chinese, Simplified [macrolanguage] */
  {"zhd",	newTag('Z','H','A',' ')},	/* Dai Zhuang -> Zhuang */
  {"zhn",	newTag('Z','H','A',' ')},	/* Nong Zhuang -> Zhuang */
  {"zlj",	newTag('Z','H','A',' ')},	/* Liujiang Zhuang -> Zhuang */
  {"zlm",	newTag('M','L','Y',' ')},	/* Malay */
  {"zln",	newTag('Z','H','A',' ')},	/* Lianshan Zhuang -> Zhuang */
  {"zlq",	newTag('Z','H','A',' ')},	/* Liuqian Zhuang -> Zhuang */
  {"zmi",	newTag('M','L','Y',' ')},	/* Negeri Sembilan Malay -> Malay */
  {"zmz",	newTag('B','A','D','0')},	/* Mbandja -> Banda */
  {"znd",	0	},	/* Zande [family] != Zande */
  {"zne",	newTag('Z','N','D',' ')},	/* Zande */
  {"zom",	newTag('Q','I','N',' ')},	/* Zou -> Chin */
  {"zqe",	newTag('Z','H','A',' ')},	/* Qiubei Zhuang -> Zhuang */
  {"zsm",	newTag('M','L','Y',' ')},	/* Standard Malay -> Malay */
  {"zu",	newTag('Z','U','L',' ')},	/* Zulu */
  {"zum",	newTag('L','R','C',' ')},	/* Kumzari -> Luri */
  {"zyb",	newTag('Z','H','A',' ')},	/* Yongbei Zhuang -> Zhuang */
  {"zyg",	newTag('Z','H','A',' ')},	/* Yang Zhuang -> Zhuang */
  {"zyj",	newTag('Z','H','A',' ')},	/* Youjiang Zhuang -> Zhuang */
  {"zyn",	newTag('Z','H','A',' ')},	/* Yongnan Zhuang -> Zhuang */
  {"zyp",	newTag('Q','I','N',' ')},	/* Zyphe Chin -> Chin */
/*{"zza",	newTag('Z','Z','A',' ')},*/	/* Zazaki [macrolanguage] */
  {"zzj",	newTag('Z','H','A',' ')},	/* Zuojiang Zhuang -> Zhuang */
  {"||",	newTag('O','R','I',' ')},	/*  -> Odia (formerly Oriya) */
}

